In [162]:
import os
import re
import boto3
import json
import time
import requests
import datetime

import pandas as pd
import numpy as np

from sagemaker.session import Session
from difflib import SequenceMatcher
from bs4 import BeautifulSoup

## Accounting term matching
**Check to see if we report totals (e.g. Total Liability & Shareholder Equity) or sub-totals (e.g. Total Financial Instruments), these figure are not needed for construction of the unstructured database (avoid classification issue)**

In [261]:
# numpy exception for handling invalid log10 RunTime error (we opt to not show)
# switch 'ignore' to 'warn', if you would like to flag the RunTime error 
np.seterr(invalid = 'ignore') 

def multiple_check(x1:float, x2:float):
    """
    Determine whether the two values are the same number scaled by 10
    """
    # prevent zero division error since x1 is the denominator and log10 zero division error
    if (x1 == 0) or (x2 == 0): return False
    else:
        # if our backward sum is a multiple of 10, we return True 
        # (e.g. Total Assets (x1) 745.2322 vs Backward Sum (x2) 7452322)
        check1 = np.log10(x2 / x1).is_integer()

        # if our backward sum is a substring of a line item, with a difference of one in length, we return True 
        # (e.g. Total Assets (x1) 174182935 vs Backward Sum (x2) 74182935)
        check2 = (str(x2) in str(x1) ) & (len(str(x2)) == len(str(x1)) - 1)

        if check1 or check2: 
            return True
        else: 
            return False

def epsilon_error(x1:float, x2:float, tol:float=0.01):
    """
    Determine whether the two values are within a similar epsilon bound. We default our error tolerance
    to 0.01, implying that if two numbers are within a specified toleracnce (default 1% ) of one another 
    """
    if (x1 == 0) or (x2 == 0): return False
    else:
        # first we convert the numeric quantities into strings
        current = str(x1)
        lookback = str(x2)

        # we only want to check against the relative difference if one element in the number is read wrong
        if len(current) == len(lookback):

            # we iterate linearly through each string and check to see the positional match 
            # if we catch and mismatch we flag it with a 1, othewise skip with 0
            changes = [0 if (current[i] == lookback[i]) else 1 for i in range(len(current))]

            # check set differences produce a set with exactly 1 in length
            if sum(changes) == 1:

                diff = abs(x1 - x2)      # compute numeric differences

                # check to see whether an accounting condition was met wihtin a boundary condition
                if abs(diff / x1) <= tol:
                    return True

        return False

In [269]:
def totals_check(df:pd.DataFrame) -> tuple:
    """
    Checks to see if a line row meets the conditon of a total, if true we remove these rows as we make 
    have checked the terms before have meet our conditions (these include major and minor totals)
    ------------------------------------------------------------------------------------
    :param: (type pandas.DataFrame)
        A DataFrame that represents the Asset or Liability & Equity portion of the balance sheet
        
    :return: (type tuple)
        Return a cleaned DataFrame that strips the rows that represent totals
    """
    m, n = df.shape                  # unpack the shape of dataframe
    data_col = df.columns[1]         # the values column for balance sheet
    
    total_flag = 2       # default 2 (no measure found), 1 (sum is correct), 0 (sum is not correct)
    total_amt = np.nan
    
    # iterate through each of the line items
    for i in range(m):
        
        # check the value of line items at a given index (forward index)
        item1 = df.loc[i].values[1]
        name = df.loc[i].values[0]
        
        # ------------------------------------------------------------------
        # Perform regex search to determine "special" total rows
        # ------------------------------------------------------------------
        a_check = re.search('total assets', name, flags=re.I)
        le_check = re.search('(?=.*(liability|liabilities))(?=.*(equity|deficit|capital))', 
                             name, flags=re.I)
        # ------------------------------------------------------------------
        
        # if we find either total measure we re-write indicators
        if a_check is not None or le_check is not None:
            total_flag = 0; total_amt = item1;
        
        # compute backward sum (lookback index) 
        for j in range(i):
            
            # check whether dataframe empty (if so we skip to avoid fitting errors)
            # NOTE: Index position (i-1)   = line above current line
            #                      (i-j-1) = trailing look up line 'j' lines above the line above current line
            lookback = df.loc[i-j-1:i-1][data_col]
            
            # we check whether the lookback period is empty (if so we most likely deleted the row)
            if not lookback.empty:
                # backward sum for line items (index minus j-periods before)
                item2 = lookback.sum()

                # if we achieve this then we strip totals and break, no need to continue backward sum
                if (item1 == item2) or multiple_check(item1, item2) or epsilon_error(item1, item2, tol=0.01):
                    df = df.drop(index=i)
                    
                    # if we drop the "Total" line-item then we re-assign flag to 1
                    if a_check is not None or le_check is not None:
                        total_flag = 1
                    
                    # Error Handling for row deletions (uncomment for when not in use)
                    print('\tWe dropped row {}, {}, with lookback window of {}.'.format(i, name, j+1))
                    print('\t\tOur row is valued at {}, our lookback sum is {}'.format(item1, item2))
                    
                    # we break from inner loop to avoid key error flag 
                    break     
                
    return (df, total_flag, total_amt)

## Merging PDFs and PNGs 
**Functions to combine PDFs and PNGs where rows may be omitted**

In [215]:
def special_merge(df1:pd.DataFrame, df2:pd.DataFrame, col:str) -> pd.DataFrame:
    """
    Special type of merge for dataframes, combining all unique row items for a specified column. 
    This is designed to combine PDF and PNG balance sheets that differ in one or more rows.
    ------------------------------------------------------------------------------------
    :param: (type pandas.DataFrame)
        A DataFrame that represents either the PDF or PNG retreived from Balance Sheet
    :param: (type pandas.DataFrame)
        A DataFrame that represents either the PDF or PNG retreived from Balance Sheet
    :param: (type str)
        A shared column name that exists in both pandas.DataFrames (i.e. df1, df2)
        
    :return: (type pandas.DataFrame)
        Return a cleaned DataFrame that merges any row that was omitted, changed or missing
    """
    arr1 = df1[col].values
    arr2 = df2[col].values
    concat_pdf = []
    
    # find the sequences that match between either lineitems
    sm = SequenceMatcher(a=arr1, b=arr2)

    # The SequenceMathcer returns a 5-tupled for each correspond "obj"
    # 'replace'     a[i1:i2] should be replaced by b[j1:j2].
    # 'delete'      a[i1:i2] should be deleted. Note that j1 == j2 in this case.
    # 'insert'      b[j1:j2] should be inserted at a[i1:i1]. Note that i1 == i2 in this case.
    # 'equal'       a[i1:i2] == b[j1:j2] (the sub-sequences are equal)
    for (obj, i1, i2, j1, j2) in sm.get_opcodes():
        
        # implies that we want to "replace" the left side elment with the corresponding
        # right side element at the same index position (we perseve both)
        if obj == 'replace':
            concat_pdf.append(df1.iloc[i1:i2])
            concat_pdf.append(df2.iloc[j1:j2])
        
        # implies that we want to "delete" the left side element (we perseve the left side)
        elif obj == 'delete':
            concat_pdf.append(df1.iloc[i1:i2])
            
        elif obj == 'insert':
            concat_pdf.append(df2.iloc[j1:j2])
            
        elif obj == 'equal':
            concat_pdf.append(df1.iloc[i1:i2])
        
    return pd.concat(concat_pdf)

## Unstructured Database construction
**We develop our unstructured database from each of the non-total rows (concating the line items)**

In [3]:
def unstructured_data(df, filing_d, fiscal_y, cik, cik2name:dict) -> pd.DataFrame:
    """
    Forms unstructured row for larger database to be stored in s3 bucket
    ------------------------------------------------------------------------------------------
    Input:
        :param: df (type pandas.DataFrame)
            The balance sheet for a particular  
        :paran: filing_d (type str)
            The filing date for release of X-17A-5 filings for a broker dealer e.g. 2013-03-21
        :paran: fiscal_y (type str)
            The fiscal year for the balance sheet to cover e.g. 2012 (usually 1-year prior to filing date)
        :paran: cik (type str)
            The CIK number for a broker dealer e.g. 887767
        :paran: cik2name (type dict)
            A dictionary that maps CIK to Broker Deale names 
    Output:  
        :return: (type pandas.DataFrame)
             Return a transposed dataframe with additional columns corresponding to filing data
    """
    
    # intialize the first column (line items)
    first_column = df.columns[0]
    
    # clean dataframe should be of size greater than 1
    if len(df.columns) > 1:
        
        # transpose split balance sheet figure (our line items are now columns)
        # we first groupby the first column (this become index) and sum to group congruent names
        row = df.groupby(first_column).sum().T

        # creating additional columns in row
        row['CIK'] = cik                                  # CIK number for firm 
        row['Filing Date'] = filing_d                     # Filing Date for firm filing
        row['Filing Year'] = fiscal_y                     # Year for balance sheet filing
        row['Name'] = cik2name['broker-dealers'][cik]     # returns the name of associated with the CIK
        
        return row
    
    else:
        print('{}-{}.csv - encountered issue reading PDF'.format(cik, filing_d))
        return None

In [217]:
def extra_cols(csv_name:str):
    """
    Check to see whether their exists the presence of a total term from the line items
    ------------------------------------------------------------------------------------------
    Input:
        :param: csv_name (type str)
            The file directory on the s3 where data is stored (e.g. )
    Output:  
        :return: (type tuple)
            Returns a tuple for corresponding (file_name, filing_date, fiscal_year, cik)
    """
    
    file_name = csv_name.split('/')[-1]        # e.g. '1224385-2005-03-01.csv'
    csv_strip = file_name[:-4]                 # ignore last four elements from the back (i.e. .csv)

    # construct a string measure of important data measures 
    data_split = csv_strip.split('-')              
    filing_date = '-'.join(data_split[1:])         # join YYYY-mm-dd component for filing date
    fiscal_year = int(data_split[1]) - 1           # fiscal year are generally the previous year of filing
    cik = data_split[0]                            # extract the CIK number  
    
    return (file_name, filing_date, fiscal_year, cik)

In [5]:
def reorder_columns(df:pd.DataFrame) -> pd.DataFrame:
    """
    Re-order the completed DataFrame by ordering the CIK, Name, Filing Data and Filing Year 
    ------------------------------------------------------------------------------------------
    Input:
        :param: df (type pandas.DataFrame)
            The unstructured database for balance sheet figures
    Output:  
        :return: (type pandas.DataFrame)
            Return a dataframe with dimensions less than or equal to input dataframe (MxN) -> (MxK), 
            where K <= N
    """
    # re-order the CIK and Year columns to appear as the first two columns
    remap = df.columns[~np.isin(df.columns, ['CIK', 'Name', 'Filing Date', 'Filing Year'])]   # select all other columns
    df = df[np.insert(remap, [0, 0, 0, 0], ['CIK', 'Name', 'Filing Date', 'Filing Year'])]    # insert new order

    # filter out columns with NaN values
    filterNaN = df.isnull().all()                      # find if any column is all NaN 
    cleanCols = filterNaN[filterNaN == False].index    # select columns with at least one value

    # clean dataframe for unstructured asset terms
    return df[cleanCols]

## Final Main Execution

In [306]:
if __name__ == "__main__":
    
    # initiate s3 bucket and corresponding data folder
    bucket = "ran-s3-systemic-risk"
    
    pdf_asset_folder = "Output/X-17A-5-SPLIT-PDFS/Assets/"
    pdf_liable_folder = "Output/X-17A-5-SPLIT-PDFS/Liability & Equity/"
    
    png_asset_folder = "Output/X-17A-5-SPLIT-PNGS/Assets/"
    png_liable_folder = "Output/X-17A-5-SPLIT-PNGS/Liability & Equity/"
    
    out_folder = "Output/"

    # Amazon Textract client and Sagemaker session
    s3 = boto3.client('s3')
    session = Session()
    
    # ==============================================================================
    # ALL TEMPORARY FILE INFORMATION 
    # ==============================================================================
    # retrieving CIK-Dealers JSON file from s3 bucket
    s3.download_file(bucket, 'Temp/CIKandDealers.json', 'temp.json')
    with open('temp.json', 'r') as f: cik2brokers = json.loads(f.read())

    # remove local file after it has been created (variable is stored in memory)
    os.remove('temp.json')
    # ==============================================================================
    
    # s3 paths where asset and liability paths are stored
    asset_paths = session.list_s3_files(bucket, pdf_asset_folder)
    liable_paths = session.list_s3_files(bucket, pdf_liable_folder)
    
    # intialize list to store dataframes for asset and liability & equity
    asset_concat = [0] * len(asset_paths)
    liable_concat = [0] * len(liable_paths)
    
    # --------------------------------------------
    # Asset Unstructured Database
    # --------------------------------------------
    print('Assets Unstructured Database')
    for idx, csv in enumerate(asset_paths):
        
        # decompose csv name into corresponding terms
        fileName, filing_date, fiscal_year, cik = extra_cols(csv)
        
        # first load in both the PNG and PDF split balance sheets
        # NOTE: All these balance sheets are cleaned numerical values
        s3.download_file(bucket, csv, 'temp.csv')
        pdf_df = pd.read_csv('temp.csv')
        s3.download_file(bucket, png_asset_folder + fileName, 'temp.csv')
        png_df = pd.read_csv('temp.csv')
        os.remove('temp.csv')
        
        print('Working on {}-{}'.format(cik, filing_date))
        
        # do a special merge that combines unique line items names between PDF & PNG
        temp_df1 = special_merge(pdf_df, png_df, '0')
        
        # run accounting check to remove sub-totals for each respective line-item
        df, total_flag, total_amt = totals_check(temp_df1)
        
        # we have that no "total asset" figure was found
        if total_flag == 2:
            row = pd.DataFrame([['Total asset check', 'Total asset'], 
                                ['Total asset not found', total_amt]], 
                               index=['0', '1']).T
            df = df.append(row)
            
        # we have that "total asset" was found and matches
        elif total_flag == 1:
            row = pd.DataFrame([['Total asset check', 'Total asset'], 
                                ['Total asset found & match', total_amt]], 
                               index=['0', '1']).T
            df= df.append(row)
        
        # we have that "total asset" was found, but did not match correctly
        elif total_flag == 0:
            row = pd.DataFrame(['Total asset check', 'Total asset found & no match'], 
                               index=['0', '1']).T
            df = df.append(row)
        
        # construct row for the unstructured data frame 
        export_df = unstructured_data(df, filing_date, fiscal_year, cik, cik2brokers)
        
        # stores the reported data frame 
        asset_concat[idx] = export_df
     
    print('\n\n\n\n')
        
    # --------------------------------------------
    # Liability & Equity Unstructured Database
    # --------------------------------------------
    print('\nLiability & Equity Unstructured Database')
    for idx, csv in enumerate(liable_paths):
        
        # decompose csv name into corresponding terms
        fileName, filing_date, fiscal_year, cik = extra_cols(csv)
        
        # first load in both the PNG and PDF split balance sheets
        # NOTE: All these balance sheets are cleaned numerical values
        s3.download_file(bucket, csv, 'temp.csv')
        pdf_df = pd.read_csv('temp.csv')
        s3.download_file(bucket, png_asset_folder + fileName, 'temp.csv')
        png_df = pd.read_csv('temp.csv')
        os.remove('temp.csv')
        
        print('Working on {}-{}'.format(cik, filing_date))
        
        # do a special merge that combines unique line items names between PDF & PNG
        temp_df1 = special_merge(pdf_df, png_df, '0')
        
        # run accounting check to remove sub-totals for each respective line-item
        df, total_flag, total_amt = totals_check(temp_df1)
        
        # we have that no "total asset" figure was found
        if total_flag == 2:
            row = pd.DataFrame([["Total liabilities & shareholder's equity check", 
                                 "Total liabilities & shareholder's equity"], 
                                ["Total liabilities & shareholder's equity not found", 
                                 total_amt]], 
                               index=['0', '1']).T
            df = df.append(row)
            
        # we have that "total asset" was found and matches
        elif total_flag == 1:
            row = pd.DataFrame([["Total liabilities & shareholder's equity check", 
                                 "Total liabilities & shareholder's equity"], 
                                ["Total liabilities & shareholder's equity found & match", 
                                 total_amt]], 
                               index=['0', '1']).T
            df= df.append(row)
        
        # we have that "total asset" was found, but did not match correctly
        elif total_flag == 0:
            row = pd.DataFrame(["Total liabilities & shareholder's equity check", 
                                'Total Liability & Equity found & no match'], 
                               index=['0', '1']).T
            df = df.append(row)
        
        # construct row for the unstructured data frame 
        export_df = unstructured_data(df, filing_date, fiscal_year, cik, cik2brokers)
        
        # stores the reported data frame 
        liable_concat[idx] = export_df
    
    # --------------------------------------------
    # Database exportation
    # --------------------------------------------
    
    asset_df = pd.concat(asset_concat)        # asset dataframe combining all rows from 
    asset_df = reorder_columns(asset_df)      # re-order columns for dataframe
    
    # writing data frame to .csv file
    filename1 = 'unstructured_assets.csv'
    asset_df.to_csv(filename1, index=False)
    
    # write .csv file to s3
    with open(filename1, 'rb') as data:
        s3.put_object(Bucket=bucket, Key=out_folder + filename1, Body=data)
    
    liable_df = pd.concat(liable_concat)      # liablity & equity dataframe combining all rows from 
    liable_df = reorder_columns(liable_df)    # re-order columns for dataframe
    
    # writing data frame to .csv file
    filename2 = 'unstructured_liable.csv'
    liable_df.to_csv(filename2, index=False)
    
    # write .csv file to s3
    with open(filename2, 'rb') as data:
        s3.put_object(Bucket=bucket, Key=out_folder + filename2, Body=data)
    
    # remove local file after it has been created
    os.remove(filename1)
    os.remove(filename2)
    
    print('\nWe created an unstructured asset and liability & equity')

Assets Unstructured Database
Working on 1224385-2004-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 21509787000.0, our lookback sum is 21509787000.0
Working on 1224385-2005-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 35611655000.0, our lookback sum is 35611655000.0
Working on 1224385-2006-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 24029490000.0, our lookback sum is 24029490000.0
Working on 1224385-2007-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 20879923000.0, our lookback sum is 20879923000.0
Working on 1224385-2008-02-29
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 21660817000.0, our lookback sum is 21660817000.0
Working on 1224385-2009-03-02
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 9580535000.0, our lookback sum is 9580535000.0
Working on 1224385-2010-03-12
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 17499658000.0, our lookback sum is 17499658000.0
Working on 1224385-2011-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 37609933000.0, our lookback sum is 37609933000.0
Working on 1224385-2012-02-29
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 39534067000.0, our lookback sum is 39534067000.0
Working on 1224385-2013-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 43524084000.0, our lookback sum is 43524084000.0
Working on 1224385-2014-03-04
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 48144895000.0, our lookback sum is 48144895000.0
Working on 1224385-2015-03-02
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 64835741000.0, our lookback sum is 64835741000.0
Working on 1224385-2016-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 90531855000.0, our lookback sum is 90531855000.0
Working on 1224385-2017-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 112940487000.0, our lookback sum is 112940487000.0
Working on 1224385-2018-02-28
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 131402200000.0, our lookback sum is 131402200000.0
Working on 1224385-2019-02-28
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 134323969000.0, our lookback sum is 134323969000.0
Working on 1224385-2020-02-28
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 141834542000.0, our lookback sum is 141834542000.0
Working on 1224385-2021-02-26
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 132758281000.0, our lookback sum is 132758281000.0
Working on 42352-2002-01-30
Working on 42352-2003-01-28

TypeError: expected string or bytes-like object

In [298]:
# work on combining columns that are issued seperately
s3 = boto3.client('s3')
session = Session()
bucket = "ran-s3-systemic-risk"

# e.g. file name = 1224385-2004-03-01, 42352-2003-01-28
s3.download_file(bucket, 'Output/X-17A-5-SPLIT-PDFS/Assets/1224385-2004-03-01.csv', 'temp.csv')
pdf_df = pd.read_csv('temp.csv')
s3.download_file(bucket, 'Output/X-17A-5-SPLIT-PNGS/Assets/1224385-2004-03-01.csv', 'temp.csv')
png_df = pd.read_csv('temp.csv')
os.remove('temp.csv')

In [299]:
pdf_df

                                                    0             1
0                                                Cash  1.760000e+05
1     Cash segregated pursuant to federal regulations  7.500000e+07
2     Securities purchased under agreements to resell  7.944113e+09
3   Securities owned, at market value ($8,769,300 ...  9.075170e+09
4   Receivable from broker-dealers and clearing or...  4.049708e+09
5                           Receivable from customers  5.124600e+07
6                         Accrued interest receivable  4.445700e+07
7   Property, equipment, and leasehold improvement...  1.106700e+07
8                                       Goodwill, net  6.112000e+06
9                                        Other assets  2.527380e+08
10                                       Total assets  2.150979e+10

In [300]:
png_df

                                                    0             1
0                                                Cash  1.760000e+05
1     Cash segregated pursuant to federal regulations  7.500000e+07
2     Securities purchased under agreements to resell  7.944113e+09
3   Securities owned, at market value ($8,769,300 ...  9.075170e+09
4   Receivable from broker-dealers and clearing or...  4.049708e+09
5                           Receivable from customers  5.124600e+07
6                         Accrued interest receivable  4.445700e+07
7   Property, equipment, and leasehold improvement...  1.106700e+07
8                                       Goodwill, net  6.112000e+06
9                                        Other assets  2.527380e+08
10                                       Total assets  2.150979e+10

In [301]:
sample_df, flag, amt = totals_check(special_merge(pdf_df, pdf_df, '0'))

	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 21509787000.0, our lookback sum is 21509787000.0

In [302]:
sample_df

                                                   0             1
0                                               Cash  1.760000e+05
1    Cash segregated pursuant to federal regulations  7.500000e+07
2    Securities purchased under agreements to resell  7.944113e+09
3  Securities owned, at market value ($8,769,300 ...  9.075170e+09
4  Receivable from broker-dealers and clearing or...  4.049708e+09
5                          Receivable from customers  5.124600e+07
6                        Accrued interest receivable  4.445700e+07
7  Property, equipment, and leasehold improvement...  1.106700e+07
8                                      Goodwill, net  6.112000e+06
9                                       Other assets  2.527380e+08

In [303]:
# we have that no "total asset" figure was found
if flag == 2:
    row = pd.DataFrame([['Total asset check', 'Total asset'], 
                        ['Total asset not found', amt]], 
                       index=['0', '1']).T
    sample_df = sample_df.append(row)

# we have that "total asset" was found and matches
elif flag == 1:
    row = pd.DataFrame([['Total asset check', 'Total asset'], 
                        ['Total asset found & match', amt]], 
                       index=['0', '1']).T
    sample_df = sample_df.append(row)
    
elif flag == 0:
    row = pd.DataFrame(['Total asset check', 'Total asset found & no match'], 
                       index=['0', '1']).T
    sample_df =sample_df.append(row)

In [304]:
sample_df

,0,1
0,Cash,176000
1,Cash segregated pursuant to federal regulations,7.5e+07
2,Securities purchased under agreements to resell,7.94411e+09
3,"Securities owned, at market value ($8,769,300 ...",9.07517e+09
4,Receivable from broker-dealers and clearing or...,4.04971e+09
5,Receivable from customers,5.1246e+07
6,Accrued interest receivable,4.4457e+07
7,"Property, equipment, and leasehold improvement...",1.1067e+07
8,"Goodwill, net",6.112e+06
9,Other assets,2.52738e+08
0,Total asset check,Total asset found & match
1,Total asset,2.15098e+10