In [1]:
%pip install fuzzywuzzy
%pip install python-Levenshtein

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0
Note: you may need to restart the kernel to use updated packages.
Collecting python-Levenshtein
  Downloading python-Levenshtein-0.12.2.tar.gz (50 kB)
     |████████████████████████████████| 50 kB 3.2 MB/s eta 0:00:011
Requirement already satisfied: setuptools in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from python-Levenshtein) (49.6.0.post20210108)
Building wheels for collected packages: python-Levenshtein
  Building wheel for python-Levenshtein (setup.py) ... done
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp36-cp36m-linux_x86_64.whl size=155932 sha256=af338f00ba765a62f9b6e87c8e7bb7aa0d37491075d6215ecc927f42ef62d643
  Stored in directory: /home/ec2-user/.cache/pip/wheels/4a/a4/bf/d761b0899395c75fa76d003d607b3869ee47f5035b8afc30a2
Successfully built python-Levenshtein
Installing collected packages: python-Levenshtein
Successfully installed python-Levenshtein-0.12.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import re
import botocore
import boto3
import json
import time
import requests
import datetime

import pandas as pd
import numpy as np

from sagemaker.session import Session
from difflib import SequenceMatcher
from bs4 import BeautifulSoup
from fuzzywuzzy import fuzz

## Accounting term matching
**Check to see if we report totals (e.g. Total Liability & Shareholder Equity) or sub-totals (e.g. Total Financial Instruments), these figure are not needed for construction of the unstructured database (avoid classification issue)**

In [3]:
# numpy exception for handling invalid log10 RunTime error (we opt to not show)
# switch 'ignore' to 'warn', if you would like to flag the RunTime error 
np.seterr(invalid = 'ignore') 

def multiple_check(x1:float, x2:float):
    """
    Determine whether the two values are the same number scaled by 10
    """
    # prevent zero division error since x1 is the denominator and log10 zero division error
    if (x1 == 0) or (x2 == 0): return (x1, False)
    else:
        # if our backward sum is a multiple of 10, we return True 
        # (e.g. Total Assets (x1) 745.2322 vs Backward Sum (x2) 7452322)
        check1 = np.log10(x2 / x1).is_integer()

        # if our backward sum is a substring of a line item, with a difference of one in length, we return True 
        # (e.g. Total Assets (x1) 174182935 vs Backward Sum (x2) 74182935)
        check2 = (str(x2) in str(x1) ) & (len(str(x2)) == len(str(x1)) - 1)

        if check1 or check2:
            return (x2, True)
        else: 
            return (x1, False)

def epsilon_error(x1:float, x2:float, tol:float=0.01):
    """
    Determine whether the two values are within a similar epsilon bound. We default our error tolerance
    to 0.01, implying that if two numbers are within a specified toleracnce (default 1% ) of one another 
    """
    if (x1 == 0) or (x2 == 0): return False
    else:
        # first we convert the numeric quantities into strings
        current = str(x1)
        lookback = str(x2)

        # we only want to check against the relative difference if one element in the number is read wrong
        if len(current) == len(lookback):
            
            # we iterate linearly through each string and check to see the positional match 
            # if we catch a mismatch we flag it with a 1, othewise skip with 0
            changes = [0 if (current[i] == lookback[i]) else 1 for i in range(len(current))]

            # check set differences produce a set with exactly 1 in length
            if sum(changes) == 1:

                diff = abs(x1 - x2)      # compute numeric differences

                # check to see whether an accounting condition was met wihtin a boundary condition
                if abs(diff / x1) <= tol:
                    return True

        return False

In [4]:
def totals_check(df:pd.DataFrame) -> tuple:
    """
    Checks to see if a line row meets the conditon of a total, if true we remove these rows as we make 
    have checked the terms before have meet our conditions (these include major and minor totals)
    ------------------------------------------------------------------------------------
    :param: (type pandas.DataFrame)
        A DataFrame that represents the Asset or Liability & Equity portion of the balance sheet
        
    :return: (type tuple)
        Return a cleaned DataFrame that strips the rows that represent totals
    """
    m, n = df.shape                  # unpack the shape of dataframe
    data_col = df.columns[1]         # the values column for balance sheet
    
    total_flag = 2       # default 2 (no measure found), 1 (sum is correct), 0 (sum is not correct)
    total_amt = np.nan
    
    # iterate through each of the line items
    for i in range(m):
        
        # check the value of line items at a given index (forward index)
        item1 = df.loc[i].values[1]
        name = df.loc[i].values[0]
        
        # ------------------------------------------------------------------
        # Perform regex search to determine "special" total rows
        # ------------------------------------------------------------------
        a_check = re.search('total assets', name, flags=re.I)
        le_check = re.search('(?=.*(liability|liabilities))(?=.*(equity|deficit|capital))', 
                             name, flags=re.I)
        # ------------------------------------------------------------------
        
        # if we find either total measure we re-write indicators
        if a_check is not None or le_check is not None:
            total_flag = 0; total_amt = item1;
        
        # compute backward sum (lookback index) 
        for j in range(i):
            
            # check whether dataframe empty (if so we skip to avoid fitting errors)
            # NOTE: Index position (i-1)   = line above current line
            #                      (i-j-1) = trailing look up line 'j' lines above the line above current line
            lookback = df.loc[i-j-1:i-1][data_col]
            
            # we check whether the lookback period is empty (if so we most likely deleted the row)
            if not lookback.empty:
                # backward sum for line items (index minus j-periods before)
                item2 = lookback.sum()

                # if we achieve this then we strip totals and break, no need to continue backward sum
                check1 = item1 == item2
                val, check2 = multiple_check(item1, item2)
                check3 = epsilon_error(item1, item2, tol=0.01)
                
                if check1 or check2 or check3:
                    df = df.drop(index=i)
                    
                    # if we drop the "Total" line-item then we re-assign flag to 1
                    if a_check is not None or le_check is not None:
                        total_flag = 1
                        total_amt = val
                    
                    # Error Handling for row deletions (uncomment for when not in use)
                    print('\tWe dropped row {}, {}, with lookback window of {}.'.format(i, name, j+1))
                    print('\t\tOur row is valued at {}, our lookback sum is {}'.format(item1, item2))
                    
                    # we break from inner loop to avoid key error flag 
                    break     
                
    return (df, total_flag, total_amt)

## Merging PDFs and PNGs 
**Functions to combine PDFs and PNGs where rows may be omitted**

In [36]:
def special_merge(df1:pd.DataFrame, df2:pd.DataFrame, col:str) -> pd.DataFrame:
    """
    Special type of merge for dataframes, combining all unique row items for a specified column. 
    This is designed to combine PDF and PNG balance sheets that differ in one or more rows.
    ------------------------------------------------------------------------------------
    :param: (type pandas.DataFrame)
        A DataFrame that represents either the PDF or PNG retreived from Balance Sheet
    :param: (type pandas.DataFrame)
        A DataFrame that represents either the PDF or PNG retreived from Balance Sheet
    :param: (type str)
        A shared column name that exists in both pandas.DataFrames (i.e. df1, df2)
        
    :return: (type pandas.DataFrame)
        Return a cleaned DataFrame that merges any row that was omitted, changed or missing
    """
    arr1 = df1[col].values
    arr2 = df2[col].values
    concat_pdf = []
    
    # find the sequences that match between either lineitems
    sm = SequenceMatcher(a=arr1, b=arr2)
    
    # The SequenceMathcer returns a 5-tupled for each correspond "obj"
    # 'replace'     a[i1:i2] should be replaced by b[j1:j2].
    # 'delete'      a[i1:i2] should be deleted. Note that j1 == j2 in this case.
    # 'insert'      b[j1:j2] should be inserted at a[i1:i1]. Note that i1 == i2 in this case.
    # 'equal'       a[i1:i2] == b[j1:j2] (the sub-sequences are equal)
    for (obj, i1, i2, j1, j2) in sm.get_opcodes():
        
        # implies that we want to "replace" the left side elment with the corresponding
        # right side element at the same index position (we perseve both)
        if obj == 'replace':
            
            # check the value of a fuzzy match, only insert both rows if they vastly different
            left_names = arr1[i1:i2]
            right_names = arr2[j1:j2]
            
            # iterate through each of the checks
            for it, (left, right) in enumerate(zip(left_names, right_names)):
                
                # compute the fuzz match between string (how close are these values)
                score = fuzz.partial_ratio(left.lower(), right.lower())

                # if not close in match then we append both values
                if score < 90:
                    concat_pdf.append(df1.iloc[i1:i1+it+1])
                    concat_pdf.append(df2.iloc[j1:j1+it+1])
                else:
                    print(df1.iloc[i1:i1+it+1])
                    concat_pdf.append(df1.iloc[i1:i1+it+1])
        
        # implies that we want to "delete" the left side element (we preserve this side)
        elif obj == 'delete':
            concat_pdf.append(df1.iloc[i1:i2])
        
        # implied that we want to "insert" the right side element (we preserve this side)
        elif obj == 'insert':
            concat_pdf.append(df2.iloc[j1:j2])
            
        elif obj == 'equal':
            concat_pdf.append(df1.iloc[i1:i2])
    
    # return concated pandas.DataFrame and reset index, removing old index
    return pd.concat(concat_pdf).reset_index(drop=True)

## Unstructured Database construction
**We develop our unstructured database from each of the non-total rows (concating the line items)**

In [6]:
def unstructured_data(df, filing_d, fiscal_y, cik, cik2name:dict) -> pd.DataFrame:
    """
    Forms unstructured row for larger database to be stored in s3 bucket
    ------------------------------------------------------------------------------------------
    Input:
        :param: df (type pandas.DataFrame)
            The balance sheet for a particular  
        :paran: filing_d (type str)
            The filing date for release of X-17A-5 filings for a broker dealer e.g. 2013-03-21
        :paran: fiscal_y (type str)
            The fiscal year for the balance sheet to cover e.g. 2012 (usually 1-year prior to filing date)
        :paran: cik (type str)
            The CIK number for a broker dealer e.g. 887767
        :paran: cik2name (type dict)
            A dictionary that maps CIK to Broker Deale names 
    Output:  
        :return: (type pandas.DataFrame)
             Return a transposed dataframe with additional columns corresponding to filing data
    """
    
    # intialize the first column (line items)
    first_column = df.columns[0]
    
    # clean dataframe should be of size greater than 1
    if len(df.columns) > 1:
        
        # transpose split balance sheet figure (our line items are now columns for DataFrame)
        # we first groupby the first column (this become index) and sum to group congruent names
        row = df.groupby(first_column).sum(min_count=1).T
        
        # creating additional columns in row
        row['CIK'] = cik                                  # CIK number for firm 
        row['Filing Date'] = filing_d                     # Filing Date for firm filing
        row['Filing Year'] = fiscal_y                     # Year for balance sheet filing
        row['Name'] = cik2name['broker-dealers'][cik]     # returns the name of associated with the CIK
        
        return row
    
    else:
        print('{}-{}.csv - encountered issue reading PDF'.format(cik, filing_d))
        return None

In [7]:
def extra_cols(csv_name:str):
    """
    Check to see whether their exists the presence of a total term from the line items
    ------------------------------------------------------------------------------------------
    Input:
        :param: csv_name (type str)
            The file directory on the s3 where data is stored (e.g. )
    Output:  
        :return: (type tuple)
            Returns a tuple for corresponding (file_name, filing_date, fiscal_year, cik)
    """
    
    file_name = csv_name.split('/')[-1]        # e.g. '1224385-2005-03-01.csv'
    csv_strip = file_name[:-4]                 # ignore last four elements from the back (i.e. .csv)

    # construct a string measure of important data measures 
    data_split = csv_strip.split('-')              
    filing_date = '-'.join(data_split[1:])         # join YYYY-mm-dd component for filing date
    fiscal_year = int(data_split[1]) - 1           # fiscal year are generally the previous year of filing
    cik = data_split[0]                            # extract the CIK number  
    
    return (file_name, filing_date, fiscal_year, cik)

In [8]:
def reorder_columns(df:pd.DataFrame, col_preserve:list) -> pd.DataFrame:
    """
    Re-order the completed DataFrame by ordering the CIK, Name, Filing Data and Filing Year 
    ------------------------------------------------------------------------------------------
    Input:
        :param: df (type pandas.DataFrame)
            The unstructured database for balance sheet figures
    Output:  
        :return: (type pandas.DataFrame)
            Return a dataframe with dimensions less than or equal to input dataframe (MxN) -> (MxK), 
            where K <= N
    """
    # re-order the CIK and Year columns to appear as the first two columns
    remap = df.columns[~np.isin(df.columns, col_preserve)]                             
    df = df[np.insert(remap,                                       # pass all other columns, not in preserve list
                      np.zeros(len(col_preserve), dtype=int),      # map the location to the first index (i.e. 0)
                      col_preserve)]                               # insert columns we wished to preserve 

    filterNaN = df.isnull().all()                      # find if any column is all NaN 
    cleanCols = filterNaN[filterNaN == False].index    # select columns with at least one value

    # clean dataframe for unstructured asset terms
    return df[cleanCols]

## Final Main Execution

In [9]:
if __name__ == "__main__":
    
    # initiate s3 bucket and corresponding data folder
    bucket = "ran-s3-systemic-risk"
    
    pdf_asset_folder = "Output/X-17A-5-SPLIT-PDFS/Assets/"
    pdf_liable_folder = "Output/X-17A-5-SPLIT-PDFS/Liability & Equity/"
    
    png_asset_folder = "Output/X-17A-5-SPLIT-PNGS/Assets/"
    png_liable_folder = "Output/X-17A-5-SPLIT-PNGS/Liability & Equity/"
    
    out_folder = "Output/"

    # Amazon Textract client and Sagemaker session
    s3 = boto3.client('s3')
    session = Session()
    
    # ==============================================================================
    # ALL TEMPORARY FILE INFORMATION 
    # ==============================================================================
    # retrieving CIK-Dealers JSON file from s3 bucket
    s3.download_file(bucket, 'Temp/CIKandDealers.json', 'temp.json')
    with open('temp.json', 'r') as f: cik2brokers = json.loads(f.read())

    # remove local file after it has been created (variable is stored in memory)
    os.remove('temp.json')
    # ==============================================================================
    
    # s3 paths where asset and liability paths are stored
    asset_paths = session.list_s3_files(bucket, pdf_asset_folder)
    liable_paths = session.list_s3_files(bucket, pdf_liable_folder)
    
    # intialize list to store dataframes for asset and liability & equity
    asset_concat = [0] * len(asset_paths)
    liable_concat = [0] * len(liable_paths)
    
    # --------------------------------------------
    # Asset Unstructured Database
    # --------------------------------------------
    print('Assets Unstructured Database')
    for idx, csv in enumerate(asset_paths):
        
        # decompose csv name into corresponding terms
        fileName, filing_date, fiscal_year, cik = extra_cols(csv)
        
        # first load in both the PNG and PDF split balance sheets
        # NOTE: All these balance sheets are cleaned numerical values
        try:
            s3.download_file(bucket, csv, 'temp.csv')
            pdf_df = pd.read_csv('temp.csv')
            s3.download_file(bucket, png_asset_folder + fileName, 'temp.csv')
            png_df = pd.read_csv('temp.csv')
            os.remove('temp.csv')

            print('Working on {}-{}'.format(cik, filing_date))

            # do a special merge that combines unique line items names between PDF & PNG
            temp_df1 = special_merge(pdf_df, png_df, '0')

            # run accounting check to remove sub-totals for each respective line-item
            df, total_flag, total_amt = totals_check(temp_df1)
            
            # construct row for the unstructured data frame 
            export_df = unstructured_data(df, filing_date, fiscal_year, cik, cik2brokers)
            
            # we have that no "total asset" figure was found
            if total_flag == 2:
                export_df["Total asset check"] = "Total asset not found"
                export_df["Total asset"] = total_amt

            # we have that "total asset" was found and matches
            elif total_flag == 1:
                export_df["Total asset check"] = "Total asset found & match"
                export_df["Total asset"] = total_amt

            # we have that "total asset" was found, but did not match correctly
            elif total_flag == 0:
                export_df["Total asset check"] = "Total asset found & no match"

            # stores the reported data frame 
            asset_concat[idx] = export_df
        
        # in the event we can't download file from s3 (i.e. does not exist, we ignore the )
        except botocore.exceptions.ClientError:
            
            # assign an empty DataFrame and print out error
            asset_concat[idx] = pd.DataFrame()
            
            print('\nCLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR {}\n'.format(fileName))
     
    print('\n\n\n\n')
        
    # --------------------------------------------
    # Liability & Equity Unstructured Database
    # --------------------------------------------
    print('\nLiability & Equity Unstructured Database')
    for idx, csv in enumerate(liable_paths):
        
        # decompose csv name into corresponding terms
        fileName, filing_date, fiscal_year, cik = extra_cols(csv)
        
        try:
            # first load in both the PNG and PDF split balance sheets
            # NOTE: All these balance sheets are cleaned numerical values
            s3.download_file(bucket, csv, 'temp.csv')
            pdf_df = pd.read_csv('temp.csv')
            s3.download_file(bucket, png_liable_folder + fileName, 'temp.csv')
            png_df = pd.read_csv('temp.csv')
            os.remove('temp.csv')

            print('Working on {}-{}'.format(cik, filing_date))

            # do a special merge that combines unique line items names between PDF & PNG
            temp_df1 = special_merge(pdf_df, png_df, '0')

            # run accounting check to remove sub-totals for each respective line-item
            df, total_flag, total_amt = totals_check(temp_df1)
            
            # construct row for the unstructured data frame 
            export_df = unstructured_data(df, filing_date, fiscal_year, cik, cik2brokers)
            
            # we have that no "total asset" figure was found
            if total_flag == 2:
                export_df["Total liabilities & shareholder's equity check"] = "Total liabilities & shareholder's equity not found"
                export_df["Total liabilities & shareholder's equity"] = total_amt

            # we have that "total asset" was found and matches
            elif total_flag == 1:
                export_df["Total liabilities & shareholder's equity check"] = "Total liabilities & shareholder's equity found & match"
                export_df["Total liabilities & shareholder's equity"] = total_amt
        
            # we have that "total asset" was found, but did not match correctly
            elif total_flag == 0:
                export_df["Total liabilities & shareholder's equity check"] = "Total liabilities & shareholder's equity found & no match"
                
            # stores the reported data frame 
            liable_concat[idx] = export_df
        
        # in the event we can't download file from s3 (i.e. does not exist, we ignore the )
        except botocore.exceptions.ClientError:
            
            # assign an empty DataFrame and print out error
            liable_concat[idx] = pd.DataFrame()
            
            print('\nCLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR {}\n'.format(fileName))
    
    # --------------------------------------------
    # Database exportation
    # --------------------------------------------
    
    # writing data frame to .csv file
    asset_df = pd.concat(asset_concat)        # asset dataframe combining all rows from 
    asset_df = reorder_columns(asset_df,      # re-order columns for dataframe
                               col_preserve=['CIK', 'Name', 'Filing Date', 'Filing Year', 
                                             'Total asset check'])      
    
    filename1 = 'unstructured_assets.csv'
    asset_df.to_csv(filename1, index=False)
    with open(filename1, 'rb') as data:
        s3.put_object(Bucket=bucket, Key=out_folder + filename1, Body=data)
    
    
    # writing data frame to .csv file
    liable_df = pd.concat(liable_concat)     
    liable_df = reorder_columns(liable_df, 
                                col_preserve=['CIK', 'Name', 'Filing Date', 'Filing Year', 
                                              "Total liabilities & shareholder's equity check"])    
    
    filename2 = 'unstructured_liable.csv'
    liable_df.to_csv(filename2, index=False)
    with open(filename2, 'rb') as data:
        s3.put_object(Bucket=bucket, Key=out_folder + filename2, Body=data)
    
    # remove local file after it has been created
    os.remove(filename1)
    os.remove(filename2)
    
    print('\nWe created an unstructured asset and liability & equity')

Assets Unstructured Database
Working on 1146184-2004-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 1987636228.0, our lookback sum is 1987636228.0
Working on 1146184-2006-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 5769615468.0, our lookback sum is 5769615468.0
Working on 1146184-2007-02-26
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 5691263000.0, our lookback sum is 5691263000.0
Working on 1146184-2008-02-29
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 6762481000.0, our lookback sum is 6762481000.0
Working on 1146184-2009-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12991558000.0, our lookback sum is 12991558000.0

CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 1146184-2010-02-25.csv


CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 1146184-2011-02-25.csv

Working on 1146184-2012-02-28
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 33246026000.0, our lookback sum is 33246026000.0
Working on 1146184-2015-02-25
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 45458849000.0, our lookback sum is 45458849000.0
Working on 1146184-2016-02-24
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 8853632000.0, our lookback sum is 8853632000.0
Working on 1146184-2017-02-24
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12110284000.0, our lookback sum is 12110284000.0
Working on 1146184-2019-02-28
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 34932000000.0, our lookback sum is 34932000000.0
Working on 1146184-2021-02-25
Working on 1215680-2004-03-01
	We dropped row 4, Total assets, with lookback window of 4.
		Our row is valued at 660165.0, our lookback sum is 660165.0
Working on 1215680-2005-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 6833103845.0, our lookback sum is 6833103845.0
Working on 1215680-2006-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 10164674966.0, our lookback sum is 10164674966.0
Working on 1215680-2007-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 1189531821.0, our lookback sum is 1189531821.0
Working on 1215680-2008-02-29
	We dropped row 5, Total assets, with lookback window of 5.
		Our row is valued at 2027297075.0, our lookback sum is 2027297075.0
Working on 1215680-2009-03-04
	We dropped row 5, Total assets, with lookback window of 5.
		Our row is valued at 4875259611.0, our lookback sum is 4875259611.0
Working on 1215680-2010-02-26
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 5770112344.0, our lookback sum is 5770112344.0
Working on 1215680-2011-03-01
	We dropped row 5, Total assets, with lookback window of 5.
		Our row is valued at 8377662236.0, our lookback sum is 8377662236.0
Working on 1215680-2012-02-29
	We dropped row 5, Total assets, with lookback window of 5.
		Our row is valued at 12172524773.0, our lookback sum is 12172524773.0
Working on 1215680-2013-03-01
	We dropped row 4, Total assets, with lookback window of 4.
		Our row is valued at 13703935385.0, our lookback sum is 13703935385.0
Working on 1215680-2014-02-28
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 19280252621.0, our lookback sum is 19280252621.0
Working on 1215680-2015-02-27
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 21364270780.0, our lookback sum is 21364270780.0
Working on 1215680-2016-06-16
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 25345649106.0, our lookback sum is 25345649106.0
Working on 1215680-2017-03-07
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 29267976468.0, our lookback sum is 29267976468.0
Working on 1215680-2018-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 32007204693.0, our lookback sum is 32007204693.0
Working on 1215680-2019-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 35316268917.0, our lookback sum is 35316268917.0
Working on 1215680-2020-03-02
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 39779281667.0, our lookback sum is 39779281667.0
Working on 1215680-2021-03-02
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 35824538684.0, our lookback sum is 35824538684.0
Working on 1224385-2004-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 21509787000.0, our lookback sum is 21509787000.0
Working on 1224385-2005-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 35611655000.0, our lookback sum is 35611655000.0
Working on 1224385-2006-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 24029490000.0, our lookback sum is 24029490000.0
Working on 1224385-2007-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 20879923000.0, our lookback sum is 20879923000.0
Working on 1224385-2008-02-29
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 21660817000.0, our lookback sum is 21660817000.0
Working on 1224385-2009-03-02
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 9580535000.0, our lookback sum is 9580535000.0
Working on 1224385-2010-03-12
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 17499658000.0, our lookback sum is 17499658000.0
Working on 1224385-2011-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 37609933000.0, our lookback sum is 37609933000.0
Working on 1224385-2012-02-29
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 39534067000.0, our lookback sum is 39534067000.0
Working on 1224385-2013-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 43524084000.0, our lookback sum is 43524084000.0
Working on 1224385-2014-03-04
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 48144895000.0, our lookback sum is 48144895000.0
Working on 1224385-2015-03-02
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 64835741000.0, our lookback sum is 64835741000.0
Working on 1224385-2016-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 90531855000.0, our lookback sum is 90531855000.0
Working on 1224385-2017-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 112940487000.0, our lookback sum is 112940487000.0
Working on 1224385-2018-02-28
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 131402200000.0, our lookback sum is 131402200000.0
Working on 1224385-2019-02-28
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 134323969000.0, our lookback sum is 134323969000.0
Working on 1224385-2020-02-28
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 141834542000.0, our lookback sum is 141834542000.0
Working on 1224385-2021-02-26
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 132758281000.0, our lookback sum is 132758281000.0
Working on 1261467-2005-03-08
	We dropped row 4, Total securities owned, with lookback window of 2.
		Our row is valued at 556328000.0, our lookback sum is 556328000.0
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 28698599000.0, our lookback sum is 28698599000.0
Working on 1261467-2006-03-01
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 36936239000.0, our lookback sum is 36936239000.0
Working on 1261467-2007-03-02
	We dropped row 4, Total securities owned, with lookback window of 2.
		Our row is valued at 6369731000.0, our lookback sum is 6369731000.0

	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 31397420000.0, our lookback sum is 31397420000.0
Working on 1261467-2008-02-29
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 8289560000.0, our lookback sum is 8289560000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 26950162000.0, our lookback sum is 26950162000.0
Working on 1261467-2009-03-02
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 2950385000.0, our lookback sum is 2950385000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 11333700000.0, our lookback sum is 11333700000.0
Working on 1261467-2010-03-01
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 6662217000.0, our lookback sum is 6662217000.0
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 22195196000.0, our lookback sum is 22195196000.0
Working on 1261467-2011-03-01
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 10402497000.0, our lookback sum is 10402497000.0
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 30724823000.0, our lookback sum is 30724823000.0
Working on 1261467-2012-02-29
	We dropped row 10, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 9204567000.0, our lookback sum is 9204567000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 35194155000.0, our lookback sum is 35194155000.0
Working on 1261467-2013-03-01
	We dropped row 10, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 10318858000.0, our lookback sum is 10318858000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 36449925000.0, our lookback sum is 36449925000.0
Working on 1261467-2014-03-04
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 15475995000.0, our lookback sum is 15475995000.0
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 54564461000.0, our lookback sum is 54564461000.0
Working on 1261467-2015-03-02
	We dropped row 10, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 21121732000.0, our lookback sum is 21121732000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 58687129000.0, our lookback sum is 58687129000.0
Working on 1261467-2016-03-01
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 5658215000.0, our lookback sum is 5658215000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 138124790000.0, our lookback sum is 38124790000.0
Working on 1261467-2017-03-01
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 5253851000.0, our lookback sum is 5253851000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 36077236000.0, our lookback sum is 36077236000.0
Working on 1261467-2018-02-28
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 5544847000.0, our lookback sum is 5544847000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 37009152000.0, our lookback sum is 37009152000.0
Working on 1261467-2018-04-13
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 5544847000.0, our lookback sum is 5544847000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 37009152000.0, our lookback sum is 37009152000.0
Working on 1261467-2019-03-01
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 6038317000.0, our lookback sum is 6038317000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 33307686000.0, our lookback sum is 33307686000.0
Working on 1261467-2021-03-01
	We dropped row 9, Total financial instruments owned - at fair value, with lookback window of 2.
		Our row is valued at 2751127000.0, our lookback sum is 2751127000.0
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 28853311000.0, our lookback sum is 28853311000.0
Working on 1591458-2015-02-20
	We dropped row 3, Total assets, with lookback window of 3.
		Our row is valued at 269774.0, our lookback sum is 269774.0
Working on 1591458-2018-02-28
	We dropped row 5, Total assets, with lookback window of 5.
		Our row is valued at 14104502591.0, our lookback sum is 14104502591.0
Working on 1591458-2019-02-28
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 35680380911.0, our lookback sum is 35680380911.0
Working on 1591458-2020-02-28
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 43693577132.0, our lookback sum is 43693577132.0
Working on 1591458-2021-02-26
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 15489295354.0, our lookback sum is 15489295354.0
Working on 1616344-2016-02-24
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 33570642000.0, our lookback sum is 33570642000.0
Working on 1616344-2017-02-24
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 35298086000.0, our lookback sum is 35298086000.0
Working on 1616344-2019-02-28
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 40109749000.0, our lookback sum is 40109749000.0
Working on 1616344-2020-02-27
Working on 1616344-2021-02-25
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 15555929000.0, our lookback sum is 15555929000.0
Working on 230611-2002-03-01
Working on 230611-2003-03-03
Working on 230611-2004-03-01
Working on 230611-2005-03-01
Working on 230611-2006-03-01
Working on 230611-2007-03-01
	We dropped row 7, Total securities owned, with lookback window of 2.
		Our row is valued at 153341587000.0, our lookback sum is 153341587000.0
Working on 230611-2008-02-29
	We dropped row 7, Total securities owned, with lookback window of 2.
		Our row is valued at 156300052000.0, our lookback sum is 156300052000.0
Working on 230611-2009-03-02
	We dropped row 7, Total securities owned, with lookback window of 2.
		Our row is valued at 54970626000.0, our lookback sum is 54970626000.0
Working on 230611-2009-03-09
	We dropped row 7, Total securities owned, with lookback window of 2.
		Our row is valued at 54970626000.0, our lookback sum is 54970626000.0
Working on 230611-2011-03-01
	We dropped row 7, Total securities owned, with lookback window of 2.
		Our row is valued at 49539508000.0, our lookback sum is 49539508000.0
Working on 230611-2012-02-29
	We dropped row 7, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 40538873000.0, our lookback sum is 40538873000.0
Working on 230611-2014-03-06
	We dropped row 8, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 12378935000.0, our lookback sum is 12378935000.0
Working on 230611-2015-03-02
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 8512314000.0, our lookback sum is 8512314000.0
Working on 230611-2016-02-29
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 6997687000.0, our lookback sum is 6997687000.0
Working on 230611-2017-03-03
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 10651430000.0, our lookback sum is 10651430000.0
Working on 230611-2018-03-01
	We dropped row 9, Total securities owned, at fair value, with lookback window of 2.
		Our row is valued at 10339029000.0, our lookback sum is 10339029000.0
Working on 230611-2020-03-03
	We dropped row 9, Total financial instruments, at fair value, with lookback window of 2.
		Our row is valued at 7354824000.0, our lookback sum is 7354824000.0

Working on 230611-2021-03-01
	We dropped row 9, Total financial instruments, at fair value, with lookback window of 2.
		Our row is valued at 9424271000.0, our lookback sum is 9424271000.0
Working on 26617-2002-05-30
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12964589.0, our lookback sum is 12964589.0
Working on 26617-2003-06-02
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 14870817000.0, our lookback sum is 14870817000.0
Working on 26617-2004-05-27
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 17911077000.0, our lookback sum is 17911077000.0
Working on 26617-2005-05-26
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 19437929000.0, our lookback sum is 19437929000.0
Working on 26617-2006-05-26
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 23998473000.0, our lookback sum is 23998473000.0
Working on 26617-2007-05-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 28323064000.0, our lookback sum is 28323064000.0
Working on 26617-2008-05-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 29338110000.0, our lookback sum is 29338110000.0
Working on 26617-2009-05-29
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 22727925000.0, our lookback sum is 22727925000.0
Working on 26617-2009-06-08
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 22727925000.0, our lookback sum is 22727925000.0
Working on 26617-2010-05-28
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 24996117000.0, our lookback sum is 24996117000.0
Working on 26617-2011-05-31
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 38578500000.0, our lookback sum is 38578500000.0
Working on 26617-2012-05-30
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 36092691000.0, our lookback sum is 36092691000.0
Working on 26617-2013-05-30
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 43433164000.0, our lookback sum is 43433164000.0
Working on 26617-2014-05-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 36925152000.0, our lookback sum is 36925152000.0
Working on 26617-2015-06-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 42113496000.0, our lookback sum is 42113496000.0
Working on 26617-2016-05-31
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 43278888000.0, our lookback sum is 43278888000.0
Working on 26617-2017-05-30
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 39072121000.0, our lookback sum is 39072121000.0
Working on 26617-2018-05-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 40167338000.0, our lookback sum is 40167338000.0
Working on 26617-2019-05-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 49857320000.0, our lookback sum is 49857320000.0
Working on 26617-2020-06-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 48687833000.0, our lookback sum is 48687833000.0
Working on 29648-2003-03-03
	We dropped row 14, Total Assets, with lookback window of 14.
		Our row is valued at 10048000000.0, our lookback sum is 10048000000.0
Working on 29648-2004-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 14323000000.0, our lookback sum is 14323000000.0
Working on 29648-2005-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 12274000000.0, our lookback sum is 12274000000.0
Working on 29648-2006-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 12201000000.0, our lookback sum is 12201000000.0
Working on 29648-2007-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 11467000000.0, our lookback sum is 11467000000.0
Working on 29648-2008-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12186000000.0, our lookback sum is 12186000000.0
Working on 29648-2008-04-07
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12186000000.0, our lookback sum is 12186000000.0
Working on 29648-2008-05-13
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12186000000.0, our lookback sum is 12186000000.0
Working on 29648-2009-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 15801000000.0, our lookback sum is 15801000000.0
Working on 29648-2010-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 16950000000.0, our lookback sum is 16950000000.0
Working on 29648-2011-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 18752000000.0, our lookback sum is 18752000000.0
Working on 29648-2011-03-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 18752000000.0, our lookback sum is 18752000000.0
Working on 29648-2012-02-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 21808000000.0, our lookback sum is 21808000000.0
Working on 29648-2013-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 26494000000.0, our lookback sum is 26494000000.0
Working on 29648-2014-02-28
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 26509000000.0, our lookback sum is 26509000000.0
Working on 29648-2015-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 33626000000.0, our lookback sum is 33626000000.0
Working on 29648-2016-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 32138000000.0, our lookback sum is 32138000000.0
Working on 29648-2017-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 32450000000.0, our lookback sum is 32450000000.0
Working on 29648-2018-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 32411000000.0, our lookback sum is 32411000000.0
Working on 29648-2019-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 33005000000.0, our lookback sum is 33005000000.0
Working on 29648-2021-02-26
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 36226000000.0, our lookback sum is 36226000000.0
Working on 318336-2003-03-03
	We dropped row 16, Total Assets, with lookback window of 16.
		Our row is valued at 185695000000.0, our lookback sum is 185695000000.0
Working on 318336-2004-02-27
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 202633000000.0, our lookback sum is 202633000000.0
Working on 318336-2004-04-07
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 202603000000.0, our lookback sum is 202603000000.0
Working on 318336-2005-03-01
	We dropped row 9, Commercial paper, with lookback window of 1.
		Our row is valued at 1171000000.0, our lookback sum is 1172000000.0
Working on 318336-2006-03-01
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 238894000000.0, our lookback sum is 238894000000.0
Working on 318336-2007-03-01
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 269834000000.0, our lookback sum is 269834000000.0
Working on 318336-2008-03-26
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 326437000000.0, our lookback sum is 326437000000.0
Working on 318336-2009-03-02
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 326348000000.0, our lookback sum is 326348000000.0
Working on 318336-2010-03-03
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 292388000000.0, our lookback sum is 292388000000.0

Working on 318336-2011-03-01
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 312685000000.0, our lookback sum is 312685000000.0
Working on 318336-2012-02-29
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 309495000000.0, our lookback sum is 309495000000.0
Working on 318336-2013-03-01
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 292165000000.0, our lookback sum is 292165000000.0
Working on 318336-2014-03-05
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 275929000000.0, our lookback sum is 275929000000.0
Working on 318336-2015-03-02
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 272892000000.0, our lookback sum is 272892000000.0
Working on 318336-2016-02-29
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 204426000000.0, our lookback sum is 204426000000.0
Working on 318336-2017-03-06
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 175116000000.0, our lookback sum is 175116000000.0
Working on 318336-2018-03-01
	We dropped row 7, Customers, with lookback window of 3.
		Our row is valued at 13482000000.0, our lookback sum is 13489000000.0
Working on 318336-2019-03-08
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 87452000000.0, our lookback sum is 87452000000.0
Working on 318336-2020-02-28
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 81039000000.0, our lookback sum is 81039000000.0
Working on 318336-2021-03-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 85954000000.0, our lookback sum is 85954000000.0
Working on 356628-2002-02-25
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 16547927000.0, our lookback sum is 16547927000.0
Working on 356628-2003-02-24
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 14238465000.0, our lookback sum is 14238465000.0
Working on 356628-2004-03-01
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 17280613000.0, our lookback sum is 17280613000.0
Working on 356628-2005-03-01
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 20668315000.0, our lookback sum is 20668315000.0
Working on 356628-2006-03-02
Working on 356628-2007-03-01
Working on 356628-2008-02-29
Working on 356628-2009-03-02
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 31035621000.0, our lookback sum is 31035621000.0
Working on 356628-2010-06-11
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 34306797000.0, our lookback sum is 34306797000.0
Working on 356628-2011-03-02
	We dropped row 7, Total receivables, with lookback window of 3.
		Our row is valued at 10322075000.0, our lookback sum is 10322075000.0
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 43615653000.0, our lookback sum is 43615653000.0
Working on 356628-2012-02-27
	We dropped row 7, Total Receivables, with lookback window of 3.
		Our row is valued at 10358000000.0, our lookback sum is 10358000000.0
	We dropped row 11, Total Assets, with lookback window of 11.
		Our row is valued at 54948000000.0, our lookback sum is 54948000000.0
Working on 356628-2013-02-25
	We dropped row 7, Total receivables, with lookback window of 2.
		Our row is valued at 11907000000.0, our lookback sum is 11907000000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 68698000000.0, our lookback sum is 68698000000.0
Working on 356628-2014-02-21
	We dropped row 7, Total receivables, with lookback window of 2.
		Our row is valued at 13860000000.0, our lookback sum is 13860000000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 77187000000.0, our lookback sum is 77187000000.0
Working on 356628-2015-02-26
	We dropped row 8, Total receivables, with lookback window of 3.
		Our row is valued at 16229000000.0, our lookback sum is 16229000000.0
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 86919000000.0, our lookback sum is 86919000000.0
Working on 356628-2016-02-24
	We dropped row 7, Total receivables, with lookback window of 3.
		Our row is valued at 17012000000.0, our lookback sum is 17012000000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 94086000000.0, our lookback sum is 94086000000.0
Working on 356628-2017-02-24
	We dropped row 7, Total receivables, with lookback window of 2.
		Our row is valued at 17446000000.0, our lookback sum is 17446000000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 93659000000.0, our lookback sum is 93659000000.0
Working on 356628-2019-02-25
	We dropped row 6, Total receivables, with lookback window of 2.
		Our row is valued at 23235000000.0, our lookback sum is 23235000000.0
	We dropped row 9, Total Assets, with lookback window of 9.
		Our row is valued at 73211000000.0, our lookback sum is 73211000000.0
Working on 356628-2021-02-25
	We dropped row 6, Total receivables, with lookback window of 2.
		Our row is valued at 32137000000.0, our lookback sum is 32137000000.0
	We dropped row 9, Total Assets, with lookback window of 9.
		Our row is valued at 89437000000.0, our lookback sum is 89437000000.0
Working on 42352-2002-01-30
Working on 42352-2003-01-28
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 40528247000.0, our lookback sum is 40528247000.0
Working on 42352-2004-01-27
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 53321469000.0, our lookback sum is 53321469000.0
Working on 42352-2005-01-25
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 65452780000.0, our lookback sum is 65452780000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 348590977000.0, our lookback sum is 348590977000.0
Working on 42352-2006-01-24
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 106354891000.0, our lookback sum is 106354891000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 475872139000.0, our lookback sum is 475872139000.0
Working on 42352-2007-01-23
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 105900570000.0, our lookback sum is 105900570000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 509250736000.0, our lookback sum is 509250736000.0
Working on 42352-2008-01-29
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 118741785000.0, our lookback sum is 118741785000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 632858770000.0, our lookback sum is 632858770000.0
Working on 42352-2010-03-01
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 132743000000.0, our lookback sum is 132743000000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 463755000000.0, our lookback sum is 463755000000.0
Working on 42352-2011-03-01
Working on 42352-2012-02-29
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 143357000000.0, our lookback sum is 143357000000.0
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 504694000000.0, our lookback sum is 504694000000.0
Working on 42352-2013-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 501095000000.0, our lookback sum is 501095000000.0
Working on 42352-2014-07-31
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 524526000000.0, our lookback sum is 524516000000.0
Working on 42352-2015-03-10

Working on 42352-2016-02-23
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 454751000000.0, our lookback sum is 454751000000.0
Working on 42352-2017-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 424849000000.0, our lookback sum is 424649000000.0
Working on 42352-2018-02-27
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 453927000000.0, our lookback sum is 453927000000.0
Working on 42352-2019-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 416665000000.0, our lookback sum is 416665000000.0
Working on 42352-2021-02-25
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 507647000000.0, our lookback sum is 507647000000.0
Working on 58056-2002-03-01
Working on 58056-2003-03-03
Working on 58056-2004-02-27
Working on 58056-2004-03-26
Working on 58056-2005-02-25
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 253278304000.0, our lookback sum is 253278304000.0
Working on 58056-2006-03-24
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 264444724000.0, our lookback sum is 264444714000.0
Working on 58056-2007-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 317870722000.0, our lookback sum is 317870722000.0
Working on 58056-2008-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 519780630000.0, our lookback sum is 519780630000.0
Working on 58056-2009-03-16
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 244413278000.0, our lookback sum is 244413278000.0
Working on 58056-2010-06-04
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 249693066000.0, our lookback sum is 249693066000.0
Working on 58056-2012-02-29
Working on 58056-2013-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 240046000000.0, our lookback sum is 240046000000.0
Working on 58056-2014-03-04
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 227451000000.0, our lookback sum is 227451000000.0
Working on 58056-2015-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 173638000000.0, our lookback sum is 173638000000.0
Working on 58056-2016-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 160325000000.0, our lookback sum is 160325000000.0
Working on 58056-2017-03-03
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 136083000000.0, our lookback sum is 136083000000.0
Working on 58056-2018-03-12
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 108091000000.0, our lookback sum is 108091000000.0
Working on 58056-2019-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 90946000000.0, our lookback sum is 90946000000.0
Working on 58056-2019-09-30
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 90946000000.0, our lookback sum is 90946000000.0
Working on 58056-2020-03-02
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 80071000000.0, our lookback sum is 80071000000.0
Working on 58056-2021-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 72130000000.0, our lookback sum is 72130000000.0
Working on 68136-2002-01-29
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 267625461000.0, our lookback sum is 267625461000.0
Working on 68136-2003-01-30
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 265334256000.0, our lookback sum is 265334256000.0
Working on 68136-2004-01-30
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 310888679000.0, our lookback sum is 310888679000.0
Working on 68136-2005-01-31
Working on 68136-2006-01-30
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 501699713000.0, our lookback sum is 501699713000.0
Working on 68136-2007-01-29
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 583404825000.0, our lookback sum is 583404825000.0
Working on 68136-2008-01-31
	We dropped row 19, Total assets, with lookback window of 19.
		Our row is valued at 604395450000.0, our lookback sum is 604395450000.0
Working on 68136-2009-01-29
	We dropped row 19, Total assets, with lookback window of 19.
		Our row is valued at 297422286000.0, our lookback sum is 297422286000.0
Working on 68136-2010-03-02
	We dropped row 8, Total financial instruments owned. at fair value, with lookback window of 6.
		Our row is valued at 86343225000.0, our lookback sum is 86343225000.0
	We dropped row 20, Total assets, with lookback window of 20.
		Our row is valued at 413032207000.0, our lookback sum is 413032207000.0
Working on 68136-2011-03-02
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 6.
		Our row is valued at 99110027000.0, our lookback sum is 99110027000.0
	We dropped row 20, Total assets, with lookback window of 20.
		Our row is valued at 372537340000.0, our lookback sum is 372537340000.0
Working on 68136-2012-02-29
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 6.
		Our row is valued at 94766842000.0, our lookback sum is 94766842000.0
	We dropped row 20, Total assets, with lookback window of 20.
		Our row is valued at 352293126000.0, our lookback sum is 352293126000.0
Working on 68136-2013-03-01
	We dropped row 8, Total financial instruments owned, at fair value, with lookback window of 6.
		Our row is valued at 90227260000.0, our lookback sum is 90227260000.0
	We dropped row 20, Section Total assets, with lookback window of 20.
		Our row is valued at 369066424000.0, our lookback sum is 369066424000.0
Working on 68136-2014-03-04
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 367496000000.0, our lookback sum is 367496000000.0
Working on 68136-2015-03-02
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 345134000000.0, our lookback sum is 345134000000.0
Working on 68136-2016-02-29
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 301341000000.0, our lookback sum is 301341000000.0
Working on 68136-2017-03-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 308038000000.0, our lookback sum is 308038000000.0
Working on 68136-2018-03-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 305281000000.0, our lookback sum is 305281000000.0
Working on 68136-2019-03-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 303806000000.0, our lookback sum is 303806000000.0
Working on 68136-2021-02-26
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 409239000000.0, our lookback sum is 409239000000.0
Working on 72267-2003-05-30
	We dropped row 8, Receivables:, with lookback window of 4.
		Our row is valued at 15993366000.0, our lookback sum is 15993366000.0
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 57702809000.0, our lookback sum is 57702809000.0
Working on 72267-2004-05-28
	We dropped row 4, Financial instruments owned (approximately $10,900,474 were, with lookback window of 2.
		Our row is valued at 44343153000.0, our lookback sum is 44343153000.0
	We dropped row 9, Receivables:, with lookback window of 4.
		Our row is valued at 17731470000.0, our lookback sum is 17731470000.0
	We dropped row 13, Furniture, equipment and leasehold improvements, net of, with lookback window of 3.
		Our row is valued at 535815000.0, our lookback sum is 535815000.0
Working on 72267-2005-05-31
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 78732111000.0, our lookback sum is 78732111000.0
Working on 72267-2006-05-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 74182935000.0, our lookback sum is 74182935000.0

Working on 72267-2007-05-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 87542832000.0, our lookback sum is 87542832000.0
Working on 72267-2008-05-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 16266635000.0, our lookback sum is 16266635000.0
Working on 72267-2009-06-03
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 14279792000.0, our lookback sum is 14279792000.0
Working on 72267-2010-06-01
	We dropped row 4, Trading assets ($7,567,059 were pledged to, with lookback window of 2.
		Our row is valued at 36294531000.0, our lookback sum is 36294531000.0
Working on 72267-2012-03-15
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 104827762000.0, our lookback sum is 104827762000.0
Working on 72267-2012-05-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 114059495000.0, our lookback sum is 114059495000.0
Working on 72267-2013-05-30
Working on 72267-2014-05-30
	We dropped row 1, Cash and cash equivalents, with lookback window of 1.
		Our row is valued at 1426073000.0, our lookback sum is 1426073000.0
	We dropped row 5, Trading assets ($19,918,091 were pledged to various parties and $335,455 related to, with lookback window of 2.
		Our row is valued at 76177986000.0, our lookback sum is 76177986000.0
Working on 72267-2015-06-01
	We dropped row 4, Trading assets ($16,658,256 were pledged to various parties and $437,502 related, with lookback window of 2.
		Our row is valued at 61224030000.0, our lookback sum is 61224030000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 108960337000.0, our lookback sum is 108960337000.0
Working on 72267-2016-05-31
	We dropped row 4, Trading assets ($14,976,358 were pledged to various parties and $497,099 related, with lookback window of 2.
		Our row is valued at 60908405000.0, our lookback sum is 60908405000.0
	We dropped row 9, Furniture, equipment, leasehold improvements and software, net (includes, with lookback window of 3.
		Our row is valued at 2548556000.0, our lookback sum is 2548556000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 117925405000.0, our lookback sum is 117925405000.0
Working on 72267-2017-05-30
	We dropped row 4, Trading assets ($6,815,721 were pledged to various parties and $15,802 related, with lookback window of 2.
		Our row is valued at 81225612000.0, our lookback sum is 81225612000.0
	We dropped row 9, Furniture, equipment, leasehold improvements and software, net (includes, with lookback window of 3.
		Our row is valued at 2230458000.0, our lookback sum is 2230458000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 141510330000.0, our lookback sum is 141510330000.0
Working on 72267-2018-05-25
	We dropped row 8, Furniture, equipment, leasehold improvements and software, net (includes, with lookback window of 3.
		Our row is valued at 3117334000.0, our lookback sum is 3117334000.0
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 141073948000.0, our lookback sum is 141073948000.0
Working on 72267-2019-05-28
	We dropped row 9, Furniture, equipment, leasehold improvements and software, net (includes, with lookback window of 3.
		Our row is valued at 2620041000.0, our lookback sum is 2620041000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 127542303000.0, our lookback sum is 127542303000.0
Working on 72267-2020-06-01
	We dropped row 9, Furniture, equipment, leasehold improvements and software, net (includes, with lookback window of 3.
		Our row is valued at 5258229000.0, our lookback sum is 5258229000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 142473148000.0, our lookback sum is 142473148000.0
Working on 782124-2002-01-29
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 140655621000.0, our lookback sum is 140655621000.0
Working on 782124-2003-01-30
	We dropped row 11, TOTAL ASSETS, with lookback window of 11.
		Our row is valued at 150559829000.0, our lookback sum is 150559829000.0
Working on 782124-2004-01-30
	We dropped row 11, TOTAL ASSETS, with lookback window of 11.
		Our row is valued at 164601243000.0, our lookback sum is 164601243000.0
Working on 782124-2004-05-07
	We dropped row 8, Net property and equipment, with lookback window of 3.
		Our row is valued at 107603000.0, our lookback sum is 107603000.0
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 25673078000.0, our lookback sum is 25673078000.0
Working on 782124-2005-01-31
	We dropped row 11, TOTAL ASSETS, with lookback window of 11.
		Our row is valued at 193433468000.0, our lookback sum is 193433468000.0
Working on 782124-2006-01-30
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 191806579000.0, our lookback sum is 191806579000.0
Working on 782124-2007-01-29
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 236190719000.0, our lookback sum is 236190719000.0
Working on 782124-2008-01-31
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 258125104000.0, our lookback sum is 258125104000.0
Working on 782124-2009-03-02
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 399544757000.0, our lookback sum is 399544757000.0
Working on 782124-2010-03-01
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 329205000000.0, our lookback sum is 329205000000.0
Working on 782124-2011-03-02
	We dropped row 12, Total assets (*), with lookback window of 12.
		Our row is valued at 362019000000.0, our lookback sum is 362019000000.0
Working on 782124-2012-02-29
	We dropped row 12, Total assets (a), with lookback window of 12.
		Our row is valued at 371293000000.0, our lookback sum is 371294000000.0
Working on 782124-2013-03-01
	We dropped row 12, Total assets (a), with lookback window of 12.
		Our row is valued at 451412000000.0, our lookback sum is 451412000000.0
Working on 782124-2014-03-05
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 372319000000.0, our lookback sum is 372319000000.0
Working on 782124-2015-02-27
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 397361000000.0, our lookback sum is 397361000000.0
Working on 782124-2016-02-29
	We dropped row 10, Total assets(i, with lookback window of 10.
		Our row is valued at 369680000000.0, our lookback sum is 369680000000.0
Working on 782124-2017-03-01
	We dropped row 10, Total assets(², with lookback window of 10.
		Our row is valued at 379355000000.0, our lookback sum is 379355000000.0
Working on 782124-2018-02-27
	We dropped row 9, Total assets(a, with lookback window of 9.
		Our row is valued at 351170000000.0, our lookback sum is 351170000000.0
Working on 782124-2018-02-28
	We dropped row 9, Total assets(a, with lookback window of 9.
		Our row is valued at 351170000000.0, our lookback sum is 351170000000.0
Working on 782124-2019-02-28
	We dropped row 9, Total assets(a, with lookback window of 9.
		Our row is valued at 460265000000.0, our lookback sum is 460265000000.0
Working on 782124-2020-04-01
	We dropped row 9, Total assets(a, with lookback window of 9.
		Our row is valued at 490945000000.0, our lookback sum is 490945000000.0
Working on 782124-2021-03-01
	We dropped row 9, Total assets (a), with lookback window of 9.
		Our row is valued at 609782000000.0, our lookback sum is 609782000000.0
Working on 803012-2002-12-31
Working on 803012-2003-12-31
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 6183990000.0, our lookback sum is 6183990000.0
Working on 803012-2005-01-03
Working on 803012-2006-01-03
Working on 803012-2007-01-29
Working on 803012-2007-12-28
Working on 803012-2008-12-30
Working on 803012-2009-12-29
Working on 803012-2010-12-27
Working on 803012-2011-12-21
Working on 803012-2012-12-26
Working on 803012-2013-12-26
	We dropped row 12, Total Assets, with lookback window of 12.
		Our row is valued at 33822818000.0, our lookback sum is 33822818000.0

Working on 803012-2014-12-30
	We dropped row 13, Total Assets, with lookback window of 13.
		Our row is valued at 35918709000.0, our lookback sum is 35918709000.0
Working on 803012-2015-12-22
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 34818830000.0, our lookback sum is 34818830000.0
Working on 803012-2016-12-22
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 37497845000.0, our lookback sum is 37497845000.0
Working on 803012-2018-03-22
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 46381560000.0, our lookback sum is 46381560000.0
Working on 803012-2019-12-20
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 32682640000.0, our lookback sum is 32682640000.0
Working on 803012-2020-12-22
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 39653089000.0, our lookback sum is 39653089000.0
Working on 851376-2002-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 72638615000.0, our lookback sum is 72638615000.0
Working on 851376-2003-03-03
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 103369408000.0, our lookback sum is 103369408000.0
Working on 851376-2004-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 113650937000.0, our lookback sum is 113650937000.0
Working on 851376-2005-03-02
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 174937091000.0, our lookback sum is 174937091000.0
Working on 851376-2006-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 194436796000.0, our lookback sum is 194436796000.0
Working on 851376-2007-03-14
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 236022658000.0, our lookback sum is 236022658000.0
Working on 851376-2008-02-29
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 297821416000.0, our lookback sum is 297821416000.0
Working on 851376-2009-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 240429127000.0, our lookback sum is 240429127000.0
Working on 851376-2010-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 326876000000.0, our lookback sum is 326876000000.0
Working on 851376-2011-03-15
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 330107000000.0, our lookback sum is 330107000000.0
Working on 851376-2012-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 306476000000.0, our lookback sum is 306476000000.0
Working on 851376-2013-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 309063000000.0, our lookback sum is 309063000000.0
Working on 851376-2014-03-04
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 303606000000.0, our lookback sum is 303606000000.0
Working on 851376-2015-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 248026000000.0, our lookback sum is 248026000000.0
Working on 851376-2016-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 172089000000.0, our lookback sum is 172089000000.0
Working on 851376-2017-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 152511000000.0, our lookback sum is 152511000000.0
Working on 851376-2018-02-28
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 106460000000.0, our lookback sum is 106460000000.0
Working on 851376-2019-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 105666000000.0, our lookback sum is 105666000000.0
Working on 851376-2020-03-06
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 99167000000.0, our lookback sum is 99167000000.0
Working on 851376-2021-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 112591000000.0, our lookback sum is 112591000000.0
Working on 853784-2002-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 35226132000.0, our lookback sum is 35226132000.0

CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 853784-2003-02-28.csv


CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 853784-2004-03-01.csv


CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 853784-2005-02-28.csv

Working on 853784-2006-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 50025689000.0, our lookback sum is 50025689000.0
Working on 853784-2007-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 81435436000.0, our lookback sum is 81435436000.0
Working on 853784-2007-03-09
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 81435436000.0, our lookback sum is 81435436000.0
Working on 853784-2008-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 68835607000.0, our lookback sum is 68835607000.0
Working on 853784-2009-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 61543858000.0, our lookback sum is 61543858000.0
Working on 853784-2010-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 60683961000.0, our lookback sum is 60683961000.0
Working on 853784-2011-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 83850980000.0, our lookback sum is 83850980000.0
Working on 853784-2012-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 55704086000.0, our lookback sum is 55704086000.0
Working on 853784-2013-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 77900039000.0, our lookback sum is 77900039000.0
Working on 853784-2014-03-04
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 74314954000.0, our lookback sum is 74314954000.0
Working on 853784-2015-03-09
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 81418513000.0, our lookback sum is 81418513000.0
Working on 853784-2016-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 71580510000.0, our lookback sum is 71580510000.0
Working on 853784-2017-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 71759167000.0, our lookback sum is 71759167000.0
Working on 853784-2018-03-05
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 91308598000.0, our lookback sum is 91308598000.0
Working on 853784-2019-03-01
	We dropped row 10, Total assets, with lookback window of 9.
		Our row is valued at 105062000000.0, our lookback sum is 105062000000.0
Working on 853784-2020-03-02
	We dropped row 9, Total assets, with lookback window of 8.
		Our row is valued at 77321000000.0, our lookback sum is 77321000000.0
Working on 853784-2021-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 47166000000.0, our lookback sum is 47166000000.0
Working on 867626-2004-04-28
	We dropped row 11, TOTAL ASSETS, with lookback window of 11.
		Our row is valued at 1530540679.0, our lookback sum is 1530540679.0
Working on 867626-2005-04-29
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 1669960396.0, our lookback sum is 1669960396.0
Working on 867626-2006-04-28
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 4441708222.0, our lookback sum is 4441708222.0
Working on 867626-2007-04-26
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 4422687194.0, our lookback sum is 4422687194.0
Working on 867626-2008-02-29
	We dropped row 11, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 3124952027.0, our lookback sum is 3124952027.0

Working on 867626-2009-03-02
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 6536706704.0, our lookback sum is 6536706704.0
Working on 867626-2011-03-01
	We dropped row 11, TOTAL ASSETS, with lookback window of 11.
		Our row is valued at 20895600220.0, our lookback sum is 20895600220.0
Working on 867626-2012-02-29
	We dropped row 11, TOTAL ASSETS, with lookback window of 11.
		Our row is valued at 29545945000.0, our lookback sum is 29545945000.0
Working on 867626-2014-03-04
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 29086436000.0, our lookback sum is 29086436000.0
Working on 867626-2016-02-26
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 34167171000.0, our lookback sum is 34167171000.0
Working on 867626-2017-02-28
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 29251885000.0, our lookback sum is 29251885000.0
Working on 867626-2018-02-27
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 32061810000.0, our lookback sum is 32061810000.0
Working on 867626-2019-02-27
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 33843523000.0, our lookback sum is 33843523000.0
Working on 867626-2020-02-27
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 34444680000.0, our lookback sum is 34444680000.0
Working on 867626-2021-02-26
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 32714255000.0, our lookback sum is 32714255000.0
Working on 87634-2002-03-15
Working on 87634-2003-02-27

CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 87634-2005-02-28.csv

Working on 87634-2006-02-28
	We dropped row 7, Total Assets, with lookback window of 7.
		Our row is valued at 28754000000.0, our lookback sum is 28754000000.0
Working on 87634-2006-09-21
	We dropped row 7, Total Assets, with lookback window of 7.
		Our row is valued at 28754000000.0, our lookback sum is 28754000000.0
Working on 87634-2007-03-01
	We dropped row 8, Total Assets, with lookback window of 8.
		Our row is valued at 24933000000.0, our lookback sum is 24933000000.0
Working on 87634-2008-03-03
	We dropped row 10, Total Assets, with lookback window of 10.
		Our row is valued at 25974000000.0, our lookback sum is 25974000000.0
Working on 87634-2009-02-27
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 25139000000.0, our lookback sum is 25139000000.0
Working on 87634-2010-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 30657000000.0, our lookback sum is 30657000000.0
Working on 87634-2011-02-28
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 36117000000.0, our lookback sum is 36117000000.0
Working on 87634-2012-03-05
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 39169000000.0, our lookback sum is 39169000000.0
Working on 87634-2013-02-26
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 44159000000.0, our lookback sum is 44159000000.0
Working on 87634-2014-02-26
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 40709000000.0, our lookback sum is 40709000000.0
Working on 87634-2015-02-25
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 39950000000.0, our lookback sum is 39950000000.0
Working on 87634-2017-02-27
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 42994000000.0, our lookback sum is 42994000000.0
Working on 87634-2018-02-27
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 39856000000.0, our lookback sum is 39856000000.0
Working on 87634-2019-02-26
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 42058000000.0, our lookback sum is 42058000000.0
Working on 87634-2020-02-27
	We dropped row 4, Goodwill, with lookback window of 1.
		Our row is valued at 935000000.0, our lookback sum is 937000000.0
Working on 87634-2021-02-26
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 74919000000.0, our lookback sum is 74919000000.0
Working on 877559-2002-03-01
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 8137085000.0, our lookback sum is 8137085000.0
Working on 877559-2003-03-03
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 7084535000.0, our lookback sum is 7084535000.0
Working on 877559-2004-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 11507401000.0, our lookback sum is 11507401000.0
Working on 877559-2005-03-01
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 20934619000.0, our lookback sum is 20934619000.0
Working on 877559-2006-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 25552961000.0, our lookback sum is 25552961000.0
Working on 877559-2007-03-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 57022134000.0, our lookback sum is 57022134000.0
Working on 877559-2008-02-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 79937739000.0, our lookback sum is 79937739000.0
Working on 877559-2009-03-02
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 43584859000.0, our lookback sum is 43584859000.0
Working on 877559-2010-03-01
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 37466004000.0, our lookback sum is 37466004000.0
Working on 877559-2011-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 32168739000.0, our lookback sum is 32168739000.0
Working on 877559-2012-02-29
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 30743833000.0, our lookback sum is 30743833000.0
Working on 877559-2013-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 25138886000.0, our lookback sum is 25138886000.0
Working on 877559-2014-03-04
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 33277278000.0, our lookback sum is 33277278000.0
Working on 877559-2015-03-02
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 32166280000.0, our lookback sum is 32166280000.0
Working on 877559-2016-02-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 33707317000.0, our lookback sum is 33707317000.0
Working on 877559-2016-04-25
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 33707317000.0, our lookback sum is 33707317000.0
Working on 877559-2018-04-02
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 34633973000.0, our lookback sum is 34633973000.0
Working on 877559-2018-04-05
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 27738603000.0, our lookback sum is 27738603000.0
Working on 877559-2019-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 53999487000.0, our lookback sum is 53999487000.0
Working on 877559-2020-03-02
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 31112712000.0, our lookback sum is 31112712000.0
Working on 877559-2021-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 32247849000.0, our lookback sum is 32247849000.0
Working on 890203-2002-03-01
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 19188117.0, our lookback sum is 19188117.0
Working on 890203-2003-02-28
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 11724897.0, our lookback sum is 11724897.0
Working on 890203-2004-05-03
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 11625224.0, our lookback sum is 11625224.0
Working on 890203-2005-02-22
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 10813826.0, our lookback sum is 10813826.0
Working on 890203-2006-02-28
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 12026605.0, our lookback sum is 12026605.0

Working on 890203-2007-05-30
	We dropped row 7, Total securities owned, with lookback window of 4.
		Our row is valued at 10830472.0, our lookback sum is 10830472.0
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 12382376.0, our lookback sum is 12382376.0
Working on 890203-2008-05-30
	We dropped row 7, Total securities owned, with lookback window of 4.
		Our row is valued at 11752295.0, our lookback sum is 11752295.0
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 13270613.0, our lookback sum is 13270613.0
Working on 890203-2009-05-28
	We dropped row 7, Total securities owned, with lookback window of 3.
		Our row is valued at 8963865.0, our lookback sum is 8963865.0
	We dropped row 10, TOTAL ASSETS, with lookback window of 10.
		Our row is valued at 14087251.0, our lookback sum is 14087251.0
Working on 890203-2010-05-28
	We dropped row 5, Total securities owned, with lookback window of 2.
		Our row is valued at 4593239.0, our lookback sum is 4593239.0
	We dropped row 8, TOTAL ASSETS, with lookback window of 8.
		Our row is valued at 13079371.0, our lookback sum is 13079371.0
Working on 890203-2011-05-31
	We dropped row 5, Total securities owned, with lookback window of 2.
		Our row is valued at 4187808.0, our lookback sum is 4187808.0
	We dropped row 8, TOTAL ASSETS, with lookback window of 8.
		Our row is valued at 10930496.0, our lookback sum is 10930496.0
Working on 890203-2012-05-30
	We dropped row 5, Total securities owned, with lookback window of 2.
		Our row is valued at 7019104.0, our lookback sum is 7019104.0
	We dropped row 8, Total assets, with lookback window of 8.
		Our row is valued at 9796191.0, our lookback sum is 9796191.0
Working on 890203-2013-05-29
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 9021755.0, our lookback sum is 9021755.0
Working on 890203-2014-02-28
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 8570759.0, our lookback sum is 8570759.0
Working on 890203-2015-03-02
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 8521164.0, our lookback sum is 8521164.0
Working on 890203-2016-02-26
	We dropped row 6, Total assets, with lookback window of 6.
		Our row is valued at 8258303.0, our lookback sum is 8258303.0
Working on 890203-2017-03-15
	We dropped row 7, Total assets, with lookback window of 7.
		Our row is valued at 250314009.0, our lookback sum is 250314009.0
Working on 890203-2018-03-01
	We dropped row 3, Receivable from affiliate, with lookback window of 1.
		Our row is valued at 88.0, our lookback sum is 88.0
Working on 890203-2019-03-07
	We dropped row 13, Total assets, with lookback window of 13.
		Our row is valued at 44559733.0, our lookback sum is 44559733.0
Working on 890203-2020-03-02
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 51830269.0, our lookback sum is 51830269.0
Working on 890203-2020-03-05
	We dropped row 15, Total assets, with lookback window of 15.
		Our row is valued at 51830269.0, our lookback sum is 51830269.0
Working on 890203-2021-03-01
	We dropped row 16, Total assets, with lookback window of 16.
		Our row is valued at 41256852.0, our lookback sum is 41256852.0
Working on 895502-1998-11-13
Working on 895502-2002-12-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 2991880000.0, our lookback sum is 2991880000.0
Working on 895502-2004-08-05
	We dropped row 7, Equipment and leasehold improvements, at cust, net of accumulated depreciation and amortization of $28,615 (Note: 2), with lookback window of 1.
		Our row is valued at 30045000.0, our lookback sum is 30045000.0
Working on 895502-2005-01-21
	We dropped row 7, Trading securities owned-al market value (Notes 2 and 4), with lookback window of 1.
		Our row is valued at 1518161000.0, our lookback sum is 1518161000.0
Working on 895502-2005-12-29
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 5515712000.0, our lookback sum is 5515712000.0
Working on 895502-2006-12-28
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 9193320000.0, our lookback sum is 9193320000.0
Working on 895502-2007-12-31
Working on 895502-2008-02-15
Working on 895502-2009-12-30
Working on 895502-2011-07-05
	We dropped row 14, TOTAL ASSETS, with lookback window of 14.
		Our row is valued at 41669501000.0, our lookback sum is 41669501000.0
Working on 895502-2011-12-29
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 43079890000.0, our lookback sum is 43079890000.0
Working on 895502-2012-12-28
	We dropped row 12, TOTAL ASSETS, with lookback window of 12.
		Our row is valued at 70266017000.0, our lookback sum is 70266017000.0
Working on 895502-2014-01-02
	We dropped row 13, TOTAL ASSETS, with lookback window of 13.
		Our row is valued at 67769234000.0, our lookback sum is 67769234000.0
Working on 895502-2014-12-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 75953329000.0, our lookback sum is 75953329000.0
Working on 895502-2015-12-30
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 82314225000.0, our lookback sum is 82314225000.0
Working on 895502-2016-12-28
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 82304140000.0, our lookback sum is 82304140000.0
Working on 895502-2017-12-26
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 78680916000.0, our lookback sum is 78680916000.0
Working on 895502-2019-06-17
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 60163611000.0, our lookback sum is 60163611000.0
Working on 895502-2019-12-23
	We dropped row 11, Total Assets, with lookback window of 11.
		Our row is valued at 60492227000.0, our lookback sum is 60492227000.0
Working on 91154-2002-03-01
	We dropped row 18, Total assets, with lookback window of 18.
		Our row is valued at 225279000000.0, our lookback sum is 225279000000.0
Working on 91154-2003-03-03
	We dropped row 13, Receivables:, with lookback window of 9.
		Our row is valued at 63048000000.0, our lookback sum is 63048000000.0
	We dropped row 21, Total assets, with lookback window of 21.
		Our row is valued at 197117000000.0, our lookback sum is 197117000000.0
Working on 91154-2004-02-27
	We dropped row 13, Receivables:, with lookback window of 9.
		Our row is valued at 93634000000.0, our lookback sum is 93634000000.0
	We dropped row 21, Total assets, with lookback window of 21.
		Our row is valued at 231204000000.0, our lookback sum is 231204000000.0
Working on 91154-2005-03-01
	We dropped row 13, Receivables:, with lookback window of 9.
		Our row is valued at 92322000000.0, our lookback sum is 92322000000.0
	We dropped row 21, Total assets, with lookback window of 21.
		Our row is valued at 278859000000.0, our lookback sum is 278859000000.0
Working on 91154-2007-03-01
	We dropped row 20, Total assets, with lookback window of 20.
		Our row is valued at 377951000000.0, our lookback sum is 377951000000.0
Working on 91154-2008-02-29
	We dropped row 4, Financial instruments owned and contractual commitments, at fair value:, with lookback window of 2.
		Our row is valued at 200500000000.0, our lookback sum is 200500000000.0
	We dropped row 14, Receivables:, with lookback window of 9.
		Our row is valued at 109682000000.0, our lookback sum is 109682000000.0
	We dropped row 22, Total assets, with lookback window of 22.
		Our row is valued at 363162000000.0, our lookback sum is 363162000000.0
Working on 91154-2009-03-02
	We dropped row 4, Financial instruments owned and contractual commitments, at fair value:, with lookback window of 2.
		Our row is valued at 163491000000.0, our lookback sum is 163491000000.0
	We dropped row 21, Total assets, with lookback window of 21.
		Our row is valued at 286825000000.0, our lookback sum is 286825000000.0
Working on 91154-2010-03-02
	We dropped row 4, Trading account assets (approximately $17 billion were pledged to various parties at December 31, 2009):, with lookback window of 2.
		Our row is valued at 183429000000.0, our lookback sum is 183429000000.0

	We dropped row 21, Total assets, with lookback window of 21.
		Our row is valued at 314356000000.0, our lookback sum is 314356000000.0
Working on 91154-2011-03-01
	We dropped row 4, Trading account assets (approximately $20 billion were pledged to various parties at December 31, 2010):, with lookback window of 2.
		Our row is valued at 156385000000.0, our lookback sum is 156385000000.0
	We dropped row 18, Property, equipment and leasehold improvements, net of, with lookback window of 3.
		Our row is valued at 22540000000.0, our lookback sum is 22540000000.0
	We dropped row 23, Total assets, with lookback window of 23.
		Our row is valued at 288409000000.0, our lookback sum is 288409000000.0
Working on 91154-2012-02-29
	We dropped row 4, Trading account assets (approximately $18 billion were pledged to, with lookback window of 2.
		Our row is valued at 157348000000.0, our lookback sum is 157348000000.0
	We dropped row 14, Receivables:, with lookback window of 9.
		Our row is valued at 71397000000.0, our lookback sum is 71397000000.0
	We dropped row 18, Property, equipment and leasehold improvements, net of, with lookback window of 3.
		Our row is valued at 23953000000.0, our lookback sum is 23953000000.0
	We dropped row 23, Total assets, with lookback window of 23.
		Our row is valued at 269150000000.0, our lookback sum is 269150000000.0
Working on 91154-2013-03-01
	We dropped row 4, Trading account assets (approximately $14 billion were pledged to various parties at December 31, 2012):, with lookback window of 2.
		Our row is valued at 153747000000.0, our lookback sum is 153747000000.0
	We dropped row 14, Receivables:, with lookback window of 9.
		Our row is valued at 70257000000.0, our lookback sum is 70257000000.0
	We dropped row 18, Property, equipment and leasehold improvements, net of, with lookback window of 3.
		Our row is valued at 11683000000.0, our lookback sum is 11683000000.0
	We dropped row 22, Total assets, with lookback window of 22.
		Our row is valued at 251522000000.0, our lookback sum is 251522000000.0
Working on 91154-2014-03-04
	We dropped row 19, Total assets, with lookback window of 19.
		Our row is valued at 253600000000.0, our lookback sum is 253600000000.0
Working on 91154-2016-03-01
	We dropped row 18, Total assets, with lookback window of 18.
		Our row is valued at 253416000000.0, our lookback sum is 253416000000.0
Working on 91154-2017-03-02
	We dropped row 19, Total assets, with lookback window of 19.
		Our row is valued at 261644000000.0, our lookback sum is 261644000000.0
Working on 91154-2018-03-05
	We dropped row 18, Total assets, with lookback window of 18.
		Our row is valued at 272544000000.0, our lookback sum is 272544000000.0
Working on 91154-2019-03-05
	We dropped row 11, Securities received as collateral, at fair value (all pledged to counterparties), with lookback window of 5.
		Our row is valued at 15877000000.0, our lookback sum is 15870000000.0
Working on 91154-2020-03-02
	We dropped row 17, Total assets, with lookback window of 17.
		Our row is valued at 289445000000.0, our lookback sum is 289445000000.0
Working on 920417-2015-03-02
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 32452777000.0, our lookback sum is 32452777000.0
Working on 920417-2016-02-29
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 31810325000.0, our lookback sum is 31810325000.0
Working on 920417-2017-03-01
	We dropped row 12, Total assets, with lookback window of 11.
		Our row is valued at 29809441000.0, our lookback sum is 29809440000.0
Working on 920417-2018-02-27
	We dropped row 12, Total assets, with lookback window of 11.
		Our row is valued at 38170352000.0, our lookback sum is 38170351000.0
Working on 920417-2019-02-28
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 42507970000.0, our lookback sum is 42507970000.0
Working on 920417-2020-02-28
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 44032681000.0, our lookback sum is 44032681000.0
Working on 920417-2021-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 88247203000.0, our lookback sum is 88247203000.0
Working on 922792-2002-03-04
	We dropped row 8, TOTAL ASSETS, with lookback window of 8.
		Our row is valued at 313922089.0, our lookback sum is 313922089.0
Working on 922792-2003-03-03
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 664292626.0, our lookback sum is 664292626.0
Working on 922792-2004-03-01
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 1247968829.0, our lookback sum is 1247968829.0
Working on 922792-2005-03-01
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 1764275076.0, our lookback sum is 1764275076.0
Working on 922792-2006-03-01
	We dropped row 9, TOTAL ASSETS, with lookback window of 9.
		Our row is valued at 2759809118.0, our lookback sum is 2759809118.0
Working on 922792-2007-03-01
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 4536097237.0, our lookback sum is 4536097237.0
Working on 922792-2008-02-29
	We dropped row 9, Total assets, with lookback window of 9.
		Our row is valued at 8676028952.0, our lookback sum is 8676028952.0
Working on 922792-2009-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 7996500333.0, our lookback sum is 7996500333.0
Working on 922792-2010-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 12069674947.0, our lookback sum is 12069674947.0
Working on 922792-2012-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 20362705552.0, our lookback sum is 20362705552.0
Working on 922792-2014-03-04
Working on 922792-2015-03-02
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 36189624000.0, our lookback sum is 36189624000.0
Working on 922792-2016-02-29
	We dropped row 10, Total assets, with lookback window of 10.
		Our row is valued at 40188000000.0, our lookback sum is 40188000000.0
Working on 922792-2017-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 44185000000.0, our lookback sum is 44185000000.0
Working on 922792-2018-03-01
	We dropped row 11, Total assets, with lookback window of 11.
		Our row is valued at 51613000000.0, our lookback sum is 51613000000.0
Working on 922792-2019-02-28
	We dropped row 7, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 1418000000.0, our lookback sum is 1418000000.0
	We dropped row 12, Total receivables, with lookback window of 4.
		Our row is valued at 26380000000.0, our lookback sum is 26380000000.0
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 50852000000.0, our lookback sum is 50852000000.0
Working on 922792-2019-03-01
	We dropped row 7, Total financial instruments owned, at fair value, with lookback window of 2.
		Our row is valued at 1418000000.0, our lookback sum is 1418000000.0
	We dropped row 12, Total receivables, with lookback window of 4.
		Our row is valued at 26380000000.0, our lookback sum is 26380000000.0
	We dropped row 14, Total assets, with lookback window of 14.
		Our row is valued at 50852000000.0, our lookback sum is 50852000000.0
Working on 922792-2020-02-28
	We dropped row 10, Total receivables, with lookback window of 4.
		Our row is valued at 30763000000.0, our lookback sum is 30763000000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 60395000000.0, our lookback sum is 60395000000.0
Working on 922792-2021-02-26
	We dropped row 10, Total receivables, with lookback window of 4.
		Our row is valued at 38372000000.0, our lookback sum is 38372000000.0
	We dropped row 12, Total assets, with lookback window of 12.
		Our row is valued at 77404000000.0, our lookback sum is 77404000000.0






Liability & Equity Unstructured Database
Working on 1146184-2004-03-01
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 1838533458.0, our lookback sum is 1838533458.0
	We dropped row 6, Total liabilities and members' capital, with lookback window of 6.
		Our row is valued at 1987636228.0, our lookback sum is 1987636228.0

Working on 1146184-2006-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 5195563754.0, our lookback sum is 5195563754.0
	We dropped row 11, Total liabilities and members' capital, with lookback window of 11.
		Our row is valued at 5769615468.0, our lookback sum is 5769615468.0
Working on 1146184-2007-02-26
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 5027462000.0, our lookback sum is 5027462000.0
	We dropped row 8, Total liabilities and members' capital, with lookback window of 8.
		Our row is valued at 5691263000.0, our lookback sum is 5691263000.0
Working on 1146184-2008-02-29
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 5902899000.0, our lookback sum is 5902899000.0
	We dropped row 6, Total liabilities and members' capital, with lookback window of 6.
		Our row is valued at 6762481000.0, our lookback sum is 6762481000.0
Working on 1146184-2009-03-02
	We dropped row 7, Total liabilities before subordinated borrowings from affiliate, with lookback window of 7.
		Our row is valued at 11720965000.0, our lookback sum is 11720965000.0
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 11840965000.0, our lookback sum is 11840965000.0
	We dropped row 11, Total liabilities and members' capital, with lookback window of 11.
		Our row is valued at 12991558000.0, our lookback sum is 12991558000.0

CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 1146184-2010-02-25.csv


CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 1146184-2011-02-25.csv

Working on 1146184-2012-02-28
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 32267391000.0, our lookback sum is 32267391000.0
	We dropped row 11, Total liabilities and member's capital, with lookback window of 11.
		Our row is valued at 33246026000.0, our lookback sum is 33246026000.0
Working on 1146184-2015-02-25
	We dropped row 12, Total liabilities, with lookback window of 11.
		Our row is valued at 44438640000.0, our lookback sum is 44438640000.0
	We dropped row 14, Total liabilities and member's capital, with lookback window of 13.
		Our row is valued at 45458849000.0, our lookback sum is 45458849000.0
Working on 1146184-2016-02-24
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 7882705000.0, our lookback sum is 7882705000.0
	We dropped row 11, Total liabilities and member's capital, with lookback window of 11.
		Our row is valued at 8853632000.0, our lookback sum is 8853632000.0
Working on 1146184-2017-02-24
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 11138486000.0, our lookback sum is 11138486000.0
	We dropped row 11, Total liabilities and member's capital, with lookback window of 11.
		Our row is valued at 12110284000.0, our lookback sum is 12110284000.0
Working on 1146184-2019-02-28
	We dropped row 10, Total liabilities before subordinated loans and accrued interest, with lookback window of 10.
		Our row is valued at 33009000000.0, our lookback sum is 33009000000.0
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 33366000000.0, our lookback sum is 33366000000.0
	We dropped row 14, Total liabilities and member's capital, with lookback window of 14.
		Our row is valued at 34932000000.0, our lookback sum is 34932000000.0
Working on 1146184-2021-02-25
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 67855000000.0, our lookback sum is 67855000000.0
	We dropped row 9, Total liabilities and member's capital, with lookback window of 9.
		Our row is valued at 71004000000.0, our lookback sum is 71004000000.0
Working on 1215680-2004-03-01
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 73952.0, our lookback sum is 73952.0
	We dropped row 6, Total members' equity, with lookback window of 3.
		Our row is valued at 586213.0, our lookback sum is 586213.0
	We dropped row 7, Total liabilities and members' equity, with lookback window of 7.
		Our row is valued at 660165.0, our lookback sum is 660165.0
Working on 1215680-2005-03-01
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 6634645177.0, our lookback sum is 6634645177.0
	We dropped row 5, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 6833103845.0, our lookback sum is 6833103845.0
Working on 1215680-2006-03-01
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 9898220190.0, our lookback sum is 9898220190.0
	We dropped row 4, Total liabilities and member's equity, with lookback window of 4.
		Our row is valued at 10164674966.0, our lookback sum is 10164674966.0
Working on 1215680-2007-03-01
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 1047932152.0, our lookback sum is 1047932152.0
	We dropped row 5, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 1189531821.0, our lookback sum is 1189531821.0
Working on 1215680-2008-02-29
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 1888160048.0, our lookback sum is 1888160048.0
	We dropped row 4, Total liabilities and member's equity, with lookback window of 4.
		Our row is valued at 2027297075.0, our lookback sum is 2027297075.0
Working on 1215680-2009-03-04
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 4721600508.0, our lookback sum is 4721600508.0
	We dropped row 5, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 4875259611.0, our lookback sum is 4875259611.0
Working on 1215680-2010-02-26
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 5629410944.0, our lookback sum is 5629410944.0
	We dropped row 5, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 5770112344.0, our lookback sum is 5770112344.0
Working on 1215680-2011-03-01
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 8317410349.0, our lookback sum is 8317410349.0
	We dropped row 4, Total liabilities and member's equity, with lookback window of 4.
		Our row is valued at 8377662236.0, our lookback sum is 8377662236.0
Working on 1215680-2012-02-29
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 12107598856.0, our lookback sum is 12107598856.0
Working on 1215680-2013-03-01
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 13601876471.0, our lookback sum is 13601876471.0
	We dropped row 4, Total liabilities and member's equity, with lookback window of 4.
		Our row is valued at 13703935385.0, our lookback sum is 13703935385.0
Working on 1215680-2014-02-28
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 19170738856.0, our lookback sum is 19170738856.0
	We dropped row 4, Total liabilities and member's equity, with lookback window of 4.
		Our row is valued at 19280252621.0, our lookback sum is 19280252621.0
Working on 1215680-2015-02-27
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 21249088625.0, our lookback sum is 21249088625.0
	We dropped row 6, Total liabilities and member's equity, with lookback window of 6.
		Our row is valued at 21364270780.0, our lookback sum is 21364270780.0
Working on 1215680-2016-06-16
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 25217168139.0, our lookback sum is 25217168139.0
	We dropped row 6, Total liabilities and member's equity, with lookback window of 6.
		Our row is valued at 25345649106.0, our lookback sum is 25345649106.0
Working on 1215680-2017-03-07
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 29106526580.0, our lookback sum is 29106526580.0
	We dropped row 5, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 29267976468.0, our lookback sum is 29267976468.0
Working on 1215680-2018-03-01
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 31829361158.0, our lookback sum is 31829361158.0
	We dropped row 5, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 32007204693.0, our lookback sum is 32007204693.0

Working on 1215680-2019-03-01
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 35140321140.0, our lookback sum is 35140321140.0
	We dropped row 6, Total liabilities and member's equity, with lookback window of 6.
		Our row is valued at 35316268917.0, our lookback sum is 35316268917.0
Working on 1215680-2020-03-02
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 39573830474.0, our lookback sum is 39573830474.0
	We dropped row 7, Total liabilities and member's equity, with lookback window of 7.
		Our row is valued at 39779281667.0, our lookback sum is 39779281667.0
Working on 1215680-2021-03-02
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 35583947619.0, our lookback sum is 35583947619.0
	We dropped row 7, Total liabilities and member's equity, with lookback window of 7.
		Our row is valued at 35824538684.0, our lookback sum is 35824538684.0
Working on 1224385-2004-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 19715370000.0, our lookback sum is 19715370000.0
	We dropped row 10, Total member's equity, with lookback window of 2.
		Our row is valued at 1255917000.0, our lookback sum is 1255917000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 21509787000.0, our lookback sum is 21509787000.0
Working on 1224385-2005-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 32320448000.0, our lookback sum is 32320448000.0
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 35611655000.0, our lookback sum is 35611655000.0
Working on 1224385-2006-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 20118057000.0, our lookback sum is 20118057000.0
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 24029490000.0, our lookback sum is 24029490000.0
Working on 1224385-2007-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 16498871000.0, our lookback sum is 16498871000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 3197552000.0, our lookback sum is 3197552000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 20879923000.0, our lookback sum is 20879923000.0
Working on 1224385-2008-02-29
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 17307282000.0, our lookback sum is 17307282000.0
	We dropped row 10, Total member's equity, with lookback window of 2.
		Our row is valued at 3020035000.0, our lookback sum is 3020035000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 21660817000.0, our lookback sum is 21660817000.0
Working on 1224385-2009-03-02
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 6311744000.0, our lookback sum is 6311744000.0
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 9580535000.0, our lookback sum is 9580535000.0
Working on 1224385-2010-03-12
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 13753891000.0, our lookback sum is 13753891000.0
	We dropped row 9, Total member's equity, with lookback window of 2.
		Our row is valued at 2262267000.0, our lookback sum is 2262267000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 17499658000.0, our lookback sum is 17499658000.0
Working on 1224385-2011-03-01
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 33345623000.0, our lookback sum is 33345623000.0
	We dropped row 9, Total member's equity, with lookback window of 2.
		Our row is valued at 2780810000.0, our lookback sum is 2780810000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 37609933000.0, our lookback sum is 37609933000.0
Working on 1224385-2012-02-29
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 34379197000.0, our lookback sum is 34379197000.0
	We dropped row 9, Total member's equity, with lookback window of 2.
		Our row is valued at 2831370000.0, our lookback sum is 2831370000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 39534067000.0, our lookback sum is 39534067000.0
Working on 1224385-2013-03-01
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 37889341000.0, our lookback sum is 37889341000.0
	We dropped row 9, Total member's equity, with lookback window of 2.
		Our row is valued at 3311243000.0, our lookback sum is 3311243000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 43524084000.0, our lookback sum is 43524084000.0
Working on 1224385-2014-03-04
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 41933521000.0, our lookback sum is 41933521000.0
	We dropped row 9, Total member's equity, with lookback window of 2.
		Our row is valued at 3887874000.0, our lookback sum is 3887874000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 48144895000.0, our lookback sum is 48144895000.0
Working on 1224385-2015-03-02
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 58237482000.0, our lookback sum is 58237482000.0
	We dropped row 9, Total member's equity, with lookback window of 2.
		Our row is valued at 4274759000.0, our lookback sum is 4274759000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 64835741000.0, our lookback sum is 64835741000.0
Working on 1224385-2016-02-29
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 83676648000.0, our lookback sum is 83676648000.0
	We dropped row 10, Total member's equity, with lookback window of 2.
		Our row is valued at 4531707000.0, our lookback sum is 4531707000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 90531855000.0, our lookback sum is 90531855000.0
Working on 1224385-2017-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 100620516000.0, our lookback sum is 100620516000.0
	We dropped row 10, Total member's equity, with lookback window of 2.
		Our row is valued at 5019971000.0, our lookback sum is 5019971000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 112940487000.0, our lookback sum is 112940487000.0
Working on 1224385-2018-02-28
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 119004538000.0, our lookback sum is 119004538000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 5097662000.0, our lookback sum is 5097662000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 131402200000.0, our lookback sum is 131402200000.0
Working on 1224385-2019-02-28
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 121679208000.0, our lookback sum is 121679208000.0
	We dropped row 13, Total member's equity, with lookback window of 2.
		Our row is valued at 5344761000.0, our lookback sum is 5344761000.0
	We dropped row 14, Total liabilities and member's equity, with lookback window of 14.
		Our row is valued at 134323969000.0, our lookback sum is 134323969000.0
Working on 1224385-2020-02-28
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 128932963000.0, our lookback sum is 128932963000.0
	We dropped row 13, Total member's equity, with lookback window of 2.
		Our row is valued at 5601579000.0, our lookback sum is 5601579000.0

	We dropped row 14, Total liabilities and member's equity, with lookback window of 14.
		Our row is valued at 141834542000.0, our lookback sum is 141834542000.0
Working on 1224385-2021-02-26
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 118977964000.0, our lookback sum is 118977964000.0
	We dropped row 13, Total member's equity, with lookback window of 2.
		Our row is valued at 9130317000.0, our lookback sum is 9130317000.0
	We dropped row 14, Total liabilities and member's equity, with lookback window of 14.
		Our row is valued at 132758281000.0, our lookback sum is 132758281000.0
Working on 1261467-2005-03-08
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 28302848000.0, our lookback sum is 28302848000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 28698599000.0, our lookback sum is 28698599000.0
Working on 1261467-2006-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 36370800000.0, our lookback sum is 36370800000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 36936239000.0, our lookback sum is 36936239000.0
Working on 1261467-2007-03-02
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 30120478000.0, our lookback sum is 30120478000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 31397420000.0, our lookback sum is 31397420000.0
Working on 1261467-2008-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 23797659000.0, our lookback sum is 23797659000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 26950162000.0, our lookback sum is 26950162000.0
Working on 1261467-2009-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 7777501000.0, our lookback sum is 7777501000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 11333700000.0, our lookback sum is 11333700000.0
Working on 1261467-2010-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 19380988000.0, our lookback sum is 19380988000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 22195196000.0, our lookback sum is 22195196000.0
Working on 1261467-2011-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 27876470000.0, our lookback sum is 27876470000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 30724823000.0, our lookback sum is 30724823000.0
Working on 1261467-2012-02-29
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 35194155000.0, our lookback sum is 35194155000.0
Working on 1261467-2013-03-01
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 36449925000.0, our lookback sum is 36449925000.0
Working on 1261467-2014-03-04
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 54564461000.0, our lookback sum is 54564461000.0
Working on 1261467-2015-03-02
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 58687129000.0, our lookback sum is 58687129000.0
Working on 1261467-2016-03-01
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 38124790000.0, our lookback sum is 38124790000.0
Working on 1261467-2017-03-01
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 36077236000.0, our lookback sum is 36077236000.0
Working on 1261467-2018-02-28
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 37009152000.0, our lookback sum is 37009152000.0
Working on 1261467-2018-04-13
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 37009152000.0, our lookback sum is 37009152000.0
Working on 1261467-2019-03-01
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 33307686000.0, our lookback sum is 33307686000.0
Working on 1261467-2021-03-01
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 28853311000.0, our lookback sum is 28853311000.0
Working on 1591458-2015-02-20
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 13459.0, our lookback sum is 13459.0
	We dropped row 3, Total liabilities and members' equity, with lookback window of 3.
		Our row is valued at 269774.0, our lookback sum is 269774.0
Working on 1591458-2018-02-28
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 14078313990.0, our lookback sum is 14078313990.0
	We dropped row 7, Total liabilities and member's equity, with lookback window of 7.
		Our row is valued at 14104502591.0, our lookback sum is 14104502591.0
Working on 1591458-2019-02-28
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 35649795055.0, our lookback sum is 35649795055.0
	We dropped row 7, Total liabilities and member's equity, with lookback window of 7.
		Our row is valued at 35680380911.0, our lookback sum is 35680380911.0
Working on 1591458-2020-02-28
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 43654319041.0, our lookback sum is 43654319041.0
	We dropped row 8, Total liabilities and member's equity, with lookback window of 8.
		Our row is valued at 43693577132.0, our lookback sum is 43693577132.0
Working on 1591458-2021-02-26
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 15437421406.0, our lookback sum is 15437421406.0
	We dropped row 8, Total liabilities and member's equity, with lookback window of 8.
		Our row is valued at 15489295354.0, our lookback sum is 15489295354.0
Working on 1616344-2016-02-24
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 33067938000.0, our lookback sum is 33067938000.0
	We dropped row 8, Total liabilities and member's capital, with lookback window of 8.
		Our row is valued at 33570642000.0, our lookback sum is 33570642000.0
Working on 1616344-2017-02-24
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 34787441000.0, our lookback sum is 34787441000.0
	We dropped row 9, Total liabilities and member's capital, with lookback window of 9.
		Our row is valued at 35298086000.0, our lookback sum is 35298086000.0
Working on 1616344-2019-02-28
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 39591383000.0, our lookback sum is 39591383000.0
	We dropped row 8, Total liabilities and member's capital, with lookback window of 8.
		Our row is valued at 40109749000.0, our lookback sum is 40109749000.0
Working on 1616344-2020-02-27
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 42680700000.0, our lookback sum is 42680700000.0
	We dropped row 8, Total liabilities and member's capital, with lookback window of 8.
		Our row is valued at 43212863000.0, our lookback sum is 43212863000.0
Working on 1616344-2021-02-25
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 15028412000.0, our lookback sum is 15028412000.0
	We dropped row 8, Total liabilities and member's capital, with lookback window of 8.
		Our row is valued at 15555929000.0, our lookback sum is 15555929000.0
Working on 230611-2002-03-01
Working on 230611-2003-03-03
Working on 230611-2004-03-01
Working on 230611-2005-03-01
Working on 230611-2006-03-01
Working on 230611-2007-03-01

Working on 230611-2008-02-29
Working on 230611-2009-03-02
Working on 230611-2009-03-09
Working on 230611-2011-03-01
Working on 230611-2012-02-29
Working on 230611-2014-03-06
Working on 230611-2015-03-02
Working on 230611-2016-02-29
Working on 230611-2017-03-03
Working on 230611-2018-03-01
Working on 230611-2020-03-03
Working on 230611-2021-03-01
Working on 26617-2002-05-30
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 12853568.0, our lookback sum is 12853568.0
Working on 26617-2003-06-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 14770817000.0, our lookback sum is 14770817000.0
	We dropped row 11, Accumulated deficit, with lookback window of 1.
		Our row is valued at -4402000.0, our lookback sum is 4402000.0
Working on 26617-2004-05-27
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 17813189000.0, our lookback sum is 17813189000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 97888000.0, our lookback sum is 97888000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 17911077000.0, our lookback sum is 17911077000.0
Working on 26617-2005-05-26
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 19325885000.0, our lookback sum is 19325885000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 112044000.0, our lookback sum is 12044000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 19437929000.0, our lookback sum is 19437929000.0
Working on 26617-2006-05-26
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 23859329000.0, our lookback sum is 23859329000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 139144000.0, our lookback sum is 39144000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 23998473000.0, our lookback sum is 23998473000.0
Working on 26617-2007-05-29
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 28174581000.0, our lookback sum is 28174581000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 148483000.0, our lookback sum is 48483000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 28323064000.0, our lookback sum is 28323064000.0
Working on 26617-2008-05-29
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 163642000.0, our lookback sum is 63642000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 29338110000.0, our lookback sum is 29338110000.0
Working on 26617-2009-05-29
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 200593000.0, our lookback sum is 200593000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 22727925000.0, our lookback sum is 22727925000.0
Working on 26617-2009-06-08
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 200593000.0, our lookback sum is 200593000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 22727925000.0, our lookback sum is 22727925000.0
Working on 26617-2010-05-28
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 214694000.0, our lookback sum is 214694000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 24996117000.0, our lookback sum is 24996117000.0
Working on 26617-2011-05-31
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 430384000.0, our lookback sum is 430384000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 38578500000.0, our lookback sum is 38578500000.0
Working on 26617-2012-05-30
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 35489457000.0, our lookback sum is 35489457000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 403234000.0, our lookback sum is 403234000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 36092691000.0, our lookback sum is 36092691000.0
Working on 26617-2013-05-30
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 42832835000.0, our lookback sum is 42832835000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 400329000.0, our lookback sum is 400329000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 43433164000.0, our lookback sum is 43433164000.0
Working on 26617-2014-05-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 36255210000.0, our lookback sum is 36255210000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 469942000.0, our lookback sum is 469942000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 36925152000.0, our lookback sum is 36925152000.0
Working on 26617-2015-06-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 41446911000.0, our lookback sum is 41446911000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 466585000.0, our lookback sum is 466585000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 42113496000.0, our lookback sum is 42113496000.0
Working on 26617-2016-05-31
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 42584459000.0, our lookback sum is 42584459000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 494429000.0, our lookback sum is 494429000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 43278888000.0, our lookback sum is 43278888000.0
Working on 26617-2017-05-30
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 38324722000.0, our lookback sum is 38324722000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 547399000.0, our lookback sum is 547399000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 39072121000.0, our lookback sum is 39072121000.0
Working on 26617-2018-05-30
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 39398052000.0, our lookback sum is 39398052000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 569286000.0, our lookback sum is 569286000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 40167338000.0, our lookback sum is 40167338000.0
Working on 26617-2019-05-30
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 48744408000.0, our lookback sum is 48744408000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 49857320000.0, our lookback sum is 49857320000.0
Working on 26617-2020-06-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 47433654000.0, our lookback sum is 47433654000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 48687833000.0, our lookback sum is 48687833000.0

Working on 29648-2003-03-03
	We dropped row 8, Other, with lookback window of 1.
		Our row is valued at 2000000.0, our lookback sum is 2000000.0
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 9112000000.0, our lookback sum is 9110000000.0
	We dropped row 16, Total member's equity, with lookback window of 2.
		Our row is valued at 904000000.0, our lookback sum is 904000000.0
	We dropped row 17, Total Liabilities and Member's Equity, with lookback window of 17.
		Our row is valued at 10048000000.0, our lookback sum is 10046000000.0
Working on 29648-2004-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 13044000000.0, our lookback sum is 13044000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 549000000.0, our lookback sum is 549000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 14323000000.0, our lookback sum is 14323000000.0
Working on 29648-2005-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 10982000000.0, our lookback sum is 10982000000.0
	We dropped row 10, Total member's equity, with lookback window of 2.
		Our row is valued at 562000000.0, our lookback sum is 562000000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 12274000000.0, our lookback sum is 12274000000.0
Working on 29648-2006-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 11482000000.0, our lookback sum is 11482000000.0
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 12201000000.0, our lookback sum is 12201000000.0
Working on 29648-2007-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 10529000000.0, our lookback sum is 10529000000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 11467000000.0, our lookback sum is 11467000000.0
Working on 29648-2008-02-29
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 10980000000.0, our lookback sum is 10980000000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 1206000000.0, our lookback sum is 1206000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 12186000000.0, our lookback sum is 12186000000.0
Working on 29648-2008-04-07
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 10980000000.0, our lookback sum is 10980000000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 1206000000.0, our lookback sum is 1206000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 12186000000.0, our lookback sum is 12186000000.0
Working on 29648-2008-05-13
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 10980000000.0, our lookback sum is 10980000000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 1206000000.0, our lookback sum is 1206000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 12186000000.0, our lookback sum is 12186000000.0
Working on 29648-2009-03-02
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 13891000000.0, our lookback sum is 13891000000.0
	We dropped row 13, Total member's equity, with lookback window of 2.
		Our row is valued at 1430000000.0, our lookback sum is 1430000000.0
	We dropped row 14, Total liabilities and member's equity, with lookback window of 14.
		Our row is valued at 15801000000.0, our lookback sum is 15801000000.0
Working on 29648-2010-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 15171000000.0, our lookback sum is 15171000000.0
	We dropped row 11, Accumulated earnings, with lookback window of 4.
		Our row is valued at 1030000000.0, our lookback sum is 1035000000.0
Working on 29648-2011-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 16992000000.0, our lookback sum is 16992000000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 1760000000.0, our lookback sum is 1760000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 18752000000.0, our lookback sum is 18752000000.0
Working on 29648-2011-03-30
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 1760000000.0, our lookback sum is 1760000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 4.
		Our row is valued at 18752000000.0, our lookback sum is 18752000000.0
Working on 29648-2012-02-29
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 19908000000.0, our lookback sum is 19908000000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 1900000000.0, our lookback sum is 1900000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 21808000000.0, our lookback sum is 21808000000.0
Working on 29648-2013-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 24384000000.0, our lookback sum is 24384000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 2110000000.0, our lookback sum is 2110000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 26494000000.0, our lookback sum is 26494000000.0
Working on 29648-2014-02-28
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 24185000000.0, our lookback sum is 24185000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 2324000000.0, our lookback sum is 2324000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 26509000000.0, our lookback sum is 26509000000.0
Working on 29648-2015-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 31045000000.0, our lookback sum is 31045000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 2581000000.0, our lookback sum is 2581000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 33626000000.0, our lookback sum is 33626000000.0
Working on 29648-2016-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 29221000000.0, our lookback sum is 29221000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 2917000000.0, our lookback sum is 2917000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 32138000000.0, our lookback sum is 32138000000.0
Working on 29648-2017-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 29541000000.0, our lookback sum is 29541000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 2909000000.0, our lookback sum is 2909000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 32450000000.0, our lookback sum is 32450000000.0
Working on 29648-2018-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 29221000000.0, our lookback sum is 29221000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 3190000000.0, our lookback sum is 3190000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 32411000000.0, our lookback sum is 32411000000.0
Working on 29648-2019-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 29556000000.0, our lookback sum is 29556000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 3449000000.0, our lookback sum is 3449000000.0

	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 33005000000.0, our lookback sum is 33005000000.0
Working on 29648-2021-02-26
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 32742000000.0, our lookback sum is 32742000000.0
	We dropped row 11, Total member's equity, with lookback window of 2.
		Our row is valued at 3484000000.0, our lookback sum is 3484000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 36226000000.0, our lookback sum is 36226000000.0
Working on 318336-2003-03-03
	We dropped row 14, Total Liabilities, with lookback window of 14.
		Our row is valued at 181259000000.0, our lookback sum is 181259000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 4436000000.0, our lookback sum is 4436000000.0
	We dropped row 19, Total Liabilities and Member's Equity, with lookback window of 19.
		Our row is valued at 185695000000.0, our lookback sum is 185695000000.0
Working on 318336-2004-02-27
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 197539000000.0, our lookback sum is 197539000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 5094000000.0, our lookback sum is 5094000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 202633000000.0, our lookback sum is 202633000000.0
Working on 318336-2004-04-07
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 197523000000.0, our lookback sum is 197523000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 5080000000.0, our lookback sum is 5080000000.0
	We dropped row 19, Total liabilities and member's equity., with lookback window of 19.
		Our row is valued at 202603000000.0, our lookback sum is 202603000000.0
Working on 318336-2005-03-01
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 219346000000.0, our lookback sum is 219346000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 6782000000.0, our lookback sum is 6782000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 226128000000.0, our lookback sum is 226128000000.0
Working on 318336-2006-03-01
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 231331000000.0, our lookback sum is 231331000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 7563000000.0, our lookback sum is 7563000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 238894000000.0, our lookback sum is 238894000000.0
Working on 318336-2007-03-01
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 260058000000.0, our lookback sum is 260058000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 9776000000.0, our lookback sum is 9776000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 269834000000.0, our lookback sum is 269834000000.0
Working on 318336-2008-03-26
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 315433000000.0, our lookback sum is 315433000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 11004000000.0, our lookback sum is 11004000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 326437000000.0, our lookback sum is 326437000000.0
Working on 318336-2009-03-02
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 315684000000.0, our lookback sum is 315684000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 10664000000.0, our lookback sum is 10664000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 326348000000.0, our lookback sum is 326348000000.0
Working on 318336-2010-03-03
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 280692000000.0, our lookback sum is 280692000000.0
	We dropped row 17, Total member's equity, with lookback window of 3.
		Our row is valued at 11696000000.0, our lookback sum is 11696000000.0
	We dropped row 18, Total liabilities and member's equity, with lookback window of 18.
		Our row is valued at 292388000000.0, our lookback sum is 292388000000.0
Working on 318336-2011-03-01
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 300090000000.0, our lookback sum is 300090000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 12595000000.0, our lookback sum is 12595000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 312685000000.0, our lookback sum is 312685000000.0
Working on 318336-2012-02-29
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 297909000000.0, our lookback sum is 297909000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 11586000000.0, our lookback sum is 11586000000.0
	We dropped row 19, Total liabilities and member's equity, with lookback window of 19.
		Our row is valued at 309495000000.0, our lookback sum is 309495000000.0
Working on 318336-2013-03-01
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 280489000000.0, our lookback sum is 280489000000.0
	We dropped row 18, Total member's equity, with lookback window of 3.
		Our row is valued at 11676000000.0, our lookback sum is 11676000000.0
	We dropped row 19, Total member's equity, with lookback window of 4.
		Our row is valued at 11676000000.0, our lookback sum is 11676000000.0
	We dropped row 20, Total liabilities and member's equity., with lookback window of 20.
		Our row is valued at 292165000000.0, our lookback sum is 292165000000.0
Working on 318336-2014-03-05
	We dropped row 4, Obligation to return securities received as collateral, at fair value, with lookback window of 1.
		Our row is valued at 26385000000.0, our lookback sum is 26385000000.0
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 263483000000.0, our lookback sum is 263483000000.0
	We dropped row 17, Total member's equity, with lookback window of 3.
		Our row is valued at 12446000000.0, our lookback sum is 12446000000.0
	We dropped row 18, Total liabilities and member's equity, with lookback window of 18.
		Our row is valued at 275929000000.0, our lookback sum is 275929000000.0
Working on 318336-2015-03-02
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 259373000000.0, our lookback sum is 259373000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 13519000000.0, our lookback sum is 13519000000.0
	We dropped row 16, Total liabilities and member's equity., with lookback window of 16.
		Our row is valued at 272892000000.0, our lookback sum is 272892000000.0
Working on 318336-2016-02-29
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 190325000000.0, our lookback sum is 190325000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 14101000000.0, our lookback sum is 14101000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 204426000000.0, our lookback sum is 204426000000.0
Working on 318336-2017-03-06
	We dropped row 6, Derivative contracts, with lookback window of 1.
		Our row is valued at 1030000000.0, our lookback sum is 1030000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 11253000000.0, our lookback sum is 11253000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 175116000000.0, our lookback sum is 175116000000.0

Working on 318336-2018-03-01
	We dropped row 2, Securities loaned, with lookback window of 1.
		Our row is valued at 12876000000.0, our lookback sum is 12776000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 11000000000.0, our lookback sum is 11000000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 5.
		Our row is valued at 109794000000.0, our lookback sum is 109794000000.0
Working on 318336-2019-03-08
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 76332000000.0, our lookback sum is 76332000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 11120000000.0, our lookback sum is 11120000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 87452000000.0, our lookback sum is 87452000000.0
Working on 318336-2020-02-28
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 68981000000.0, our lookback sum is 68981000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 12058000000.0, our lookback sum is 12058000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 81039000000.0, our lookback sum is 81039000000.0
Working on 318336-2021-03-01
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 73127000000.0, our lookback sum is 73127000000.0
	We dropped row 15, Total member's equity, with lookback window of 3.
		Our row is valued at 12827000000.0, our lookback sum is 12827000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 85954000000.0, our lookback sum is 85954000000.0
Working on 356628-2002-02-25
	We dropped row 8, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 8.
		Our row is valued at 16547927000.0, our lookback sum is 16547927000.0
Working on 356628-2003-02-24
	We dropped row 8, TOTAL LIABILITIES, with lookback window of 8.
		Our row is valued at 13249876000.0, our lookback sum is 13249876000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 14238465000.0, our lookback sum is 14238465000.0
Working on 356628-2004-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 15770101000.0, our lookback sum is 15770101000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 17280613000.0, our lookback sum is 17280613000.0
Working on 356628-2005-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 18947810000.0, our lookback sum is 18947810000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 20668315000.0, our lookback sum is 20668315000.0
Working on 356628-2006-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 17903566000.0, our lookback sum is 17903566000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 19729704000.0, our lookback sum is 19729704000.0
Working on 356628-2007-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 21945697000.0, our lookback sum is 21945697000.0
	We dropped row 9, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 9.
		Our row is valued at 24157117000.0, our lookback sum is 24157117000.0
Working on 356628-2008-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 25968981000.0, our lookback sum is 25968981000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 28537176000.0, our lookback sum is 28537176000.0
Working on 356628-2009-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 27934576000.0, our lookback sum is 27934576000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 31035621000.0, our lookback sum is 31035621000.0
Working on 356628-2010-06-11
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 31850269000.0, our lookback sum is 31850269000.0
	We dropped row 10, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 10.
		Our row is valued at 34306797000.0, our lookback sum is 34306797000.0
Working on 356628-2011-03-02
	We dropped row 5, Total Payables, with lookback window of 3.
		Our row is valued at 37976598000.0, our lookback sum is 37976598000.0
	We dropped row 10, TOTAL LIABILITIES, with lookback window of 10.
		Our row is valued at 41248365000.0, our lookback sum is 41248365000.0
	We dropped row 12, TOTAL LIABILITIES AND MEMBER'S EQUITY, with lookback window of 12.
		Our row is valued at 43615653000.0, our lookback sum is 43615653000.0
Working on 356628-2012-02-27
	We dropped row 5, Total Payables, with lookback window of 3.
		Our row is valued at 49274000000.0, our lookback sum is 49274000000.0
	We dropped row 9, Accrued expenses and other liabilities, with lookback window of 1.
		Our row is valued at 149000000.0, our lookback sum is 149000000.0
	We dropped row 12, Total Liabilities and Member's Equity, with lookback window of 2.
		Our row is valued at 54948000000.0, our lookback sum is 54948000000.0
Working on 356628-2013-02-25
	We dropped row 7, Total payables, with lookback window of 4.
		Our row is valued at 62692000000.0, our lookback sum is 62692000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 65929000000.0, our lookback sum is 65929000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 68698000000.0, our lookback sum is 68698000000.0
Working on 356628-2014-02-21
	We dropped row 7, Total payables, with lookback window of 4.
		Our row is valued at 70400000000.0, our lookback sum is 70400000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 74202000000.0, our lookback sum is 74202000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 77187000000.0, our lookback sum is 77187000000.0
Working on 356628-2015-02-26
	We dropped row 7, Total payables, with lookback window of 4.
		Our row is valued at 79976000000.0, our lookback sum is 79976000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 83687000000.0, our lookback sum is 83687000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 86919000000.0, our lookback sum is 86919000000.0
Working on 356628-2016-02-24
	We dropped row 6, Total payables, with lookback window of 4.
		Our row is valued at 85860000000.0, our lookback sum is 85860000000.0
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 90177000000.0, our lookback sum is 90177000000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 94086000000.0, our lookback sum is 94086000000.0
Working on 356628-2017-02-24
	We dropped row 7, Total payables, with lookback window of 4.
		Our row is valued at 85679000000.0, our lookback sum is 85679000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 89429000000.0, our lookback sum is 89429000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 93659000000.0, our lookback sum is 93659000000.0
Working on 356628-2019-02-25
	We dropped row 6, Total payables, with lookback window of 4.
		Our row is valued at 64521000000.0, our lookback sum is 64521000000.0
	We dropped row 9, Total Liabilities, with lookback window of 9.
		Our row is valued at 68611000000.0, our lookback sum is 68611000000.0
	We dropped row 11, Total Liabilities and Member's Equity, with lookback window of 11.
		Our row is valued at 73211000000.0, our lookback sum is 73211000000.0
Working on 356628-2021-02-25
	We dropped row 6, Total payables, with lookback window of 4.
		Our row is valued at 79292000000.0, our lookback sum is 79292000000.0
	We dropped row 8, Accrued expenses and other liabilities, with lookback window of 3.
		Our row is valued at 258000000.0, our lookback sum is 259000000.0
	We dropped row 11, Total Liabilities and Member's Equity, with lookback window of 2.
		Our row is valued at 89437000000.0, our lookback sum is 89437000000.0

Working on 42352-2002-01-30
Working on 42352-2003-01-28
Working on 42352-2004-01-27
Working on 42352-2005-01-25
	We dropped row 11, Total partners' capital, with lookback window of 2.
		Our row is valued at 4210751000.0, our lookback sum is 4210751000.0
	We dropped row 12, Total liabilities and partners' capital, with lookback window of 12.
		Our row is valued at 348590977000.0, our lookback sum is 348590977000.0
Working on 42352-2006-01-24
	We dropped row 11, Total partners' capital, with lookback window of 2.
		Our row is valued at 4535899000.0, our lookback sum is 4535899000.0
	We dropped row 12, Total liabilities and partners' capital, with lookback window of 12.
		Our row is valued at 475872139000.0, our lookback sum is 475872139000.0
Working on 42352-2007-01-23
	We dropped row 12, Total partners' capital, with lookback window of 2.
		Our row is valued at 4685687000.0, our lookback sum is 4685687000.0
	We dropped row 13, Total liabilities and partners' capital, with lookback window of 13.
		Our row is valued at 509250736000.0, our lookback sum is 509250736000.0
Working on 42352-2008-01-29
	We dropped row 12, Total partners' capital, with lookback window of 2.
		Our row is valued at 6247937000.0, our lookback sum is 6247937000.0
	We dropped row 13, Total liabilities and partners' capital, with lookback window of 13.
		Our row is valued at 632858770000.0, our lookback sum is 632858770000.0
Working on 42352-2010-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 438306000000.0, our lookback sum is 438306000000.0
	We dropped row 13, Total partners' capital, with lookback window of 2.
		Our row is valued at 7199000000.0, our lookback sum is 7199000000.0
	We dropped row 14, Total liabilities and partners' capital, with lookback window of 14.
		Our row is valued at 463755000000.0, our lookback sum is 463755000000.0
Working on 42352-2011-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 496216000000.0, our lookback sum is 496219000000.0
	We dropped row 13, Total partners' capital, with lookback window of 2.
		Our row is valued at 9286000000.0, our lookback sum is 9286000000.0
Working on 42352-2012-02-29
	We dropped row 12, Total partners' capital, with lookback window of 2.
		Our row is valued at 6598000000.0, our lookback sum is 6598000000.0
	We dropped row 13, Total liabilities and partners' capital, with lookback window of 13.
		Our row is valued at 504694000000.0, our lookback sum is 504694000000.0
Working on 42352-2013-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 471520000000.0, our lookback sum is 471520000000.0
	We dropped row 12, Total partners' capital, with lookback window of 2.
		Our row is valued at 8075000000.0, our lookback sum is 8075000000.0
	We dropped row 13, Total liabilities and partners' capital, with lookback window of 13.
		Our row is valued at 501095000000.0, our lookback sum is 501095000000.0
Working on 42352-2014-07-31
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 493128000000.0, our lookback sum is 493128000000.0
	We dropped row 13, Total partners' capital, with lookback window of 2.
		Our row is valued at 9898000000.0, our lookback sum is 9898000000.0
	We dropped row 14, Total liabilities and partners' capital, with lookback window of 14.
		Our row is valued at 524526000000.0, our lookback sum is 524526000000.0
Working on 42352-2015-03-10
	We dropped row 5, Customers and counterparies, with lookback window of 1.
		Our row is valued at 149046000000.0, our lookback sum is 149046000000.0
	We dropped row 14, Total partners' capital, with lookback window of 2.
		Our row is valued at 11377000000.0, our lookback sum is 11377000000.0
	We dropped row 15, Total liabilities and partners' capital, with lookback window of 4.
		Our row is valued at 477078000000.0, our lookback sum is 477076000000.0
Working on 42352-2016-02-23
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 444847000000.0, our lookback sum is 444848000000.0
	We dropped row 13, Total partners' capital, with lookback window of 2.
		Our row is valued at 9904000000.0, our lookback sum is 9904000000.0
	We dropped row 14, Total liabilities and partners' capital, with lookback window of 14.
		Our row is valued at 454751000000.0, our lookback sum is 454752000000.0
Working on 42352-2017-03-01
	We dropped row 1, Securities sold under agreements to repurchase at fair value, with lookback window of 1.
		Our row is valued at 91297000000.0, our lookback sum is 91297000000.0
	We dropped row 5, Brokers, deaters and clearing organizations, with lookback window of 1.
		Our row is valued at 4244000000.0, our lookback sum is 4244000000.0
	We dropped row 9, Unsecured shorl-lerm bonrowings (includes $20 at fair value), with lookback window of 1.
		Our row is valued at 7244000000.0, our lookback sum is 7244000000.0
	We dropped row 16, Total partners' capital, with lookback window of 2.
		Our row is valued at 11609000000.0, our lookback sum is 11609000000.0
	We dropped row 17, Total liabilities and partners' capital, with lookback window of 4.
		Our row is valued at 424649000000.0, our lookback sum is 424649000000.0
Working on 42352-2018-02-27
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 442913000000.0, our lookback sum is 442913000000.0
	We dropped row 12, Total member's equity, with lookback window of 2.
		Our row is valued at 11014000000.0, our lookback sum is 11014000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 453927000000.0, our lookback sum is 453927000000.0
Working on 42352-2019-03-01
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 406148000000.0, our lookback sum is 406148000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 416665000000.0, our lookback sum is 416665000000.0
Working on 42352-2021-02-25
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 495653000000.0, our lookback sum is 495653000000.0
Working on 58056-2002-03-01
Working on 58056-2003-03-03
Working on 58056-2004-02-27
Working on 58056-2004-03-26
Working on 58056-2005-02-25
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 248468415000.0, our lookback sum is 248468415000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 253278304000.0, our lookback sum is 253278304000.0
Working on 58056-2006-03-24
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 255495717000.0, our lookback sum is 255495717000.0
	We dropped row 13, Common stock par per Authorized, outstanding 2,000 shares, with lookback window of 1.
		Our row is valued at 2000.0, our lookback sum is 2000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 4675607000.0, our lookback sum is 4675605000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 264444724000.0, our lookback sum is 264444724000.0
Working on 58056-2007-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 306258803000.0, our lookback sum is 306258803000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 317870722000.0, our lookback sum is 317870722000.0
Working on 58056-2008-02-29
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 501757063000.0, our lookback sum is 501757063000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 519780630000.0, our lookback sum is 519780630000.0
Working on 58056-2009-03-16
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 229275201000.0, our lookback sum is 229275201000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 244413278000.0, our lookback sum is 244413278000.0

Working on 58056-2010-06-04
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 232082804000.0, our lookback sum is 232082804000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 249693066000.0, our lookback sum is 249693066000.0
Working on 58056-2012-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 225973793000.0, our lookback sum is 225973793000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 244079398000.0, our lookback sum is 244079398000.0
Working on 58056-2013-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 221339000000.0, our lookback sum is 221339000000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 240046000000.0, our lookback sum is 240046000000.0
Working on 58056-2014-03-04
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 208844000000.0, our lookback sum is 208844000000.0
	We dropped row 12, Total liabilities and stockholder's equity, with lookback window of 12.
		Our row is valued at 227451000000.0, our lookback sum is 227451000000.0
Working on 58056-2015-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 155023000000.0, our lookback sum is 155023000000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 11892000000.0, our lookback sum is 11892000000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 173638000000.0, our lookback sum is 173638000000.0
Working on 58056-2016-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 142370000000.0, our lookback sum is 142370000000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 11232000000.0, our lookback sum is 11232000000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 160325000000.0, our lookback sum is 160325000000.0
Working on 58056-2017-03-03
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 118799000000.0, our lookback sum is 118799000000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 10561000000.0, our lookback sum is 10561000000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 136083000000.0, our lookback sum is 136083000000.0
Working on 58056-2018-03-12
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 90884000000.0, our lookback sum is 90884000000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 10484000000.0, our lookback sum is 10484000000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 108091000000.0, our lookback sum is 108091000000.0
Working on 58056-2019-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 73384000000.0, our lookback sum is 73384000000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 10839000000.0, our lookback sum is 10839000000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 90946000000.0, our lookback sum is 90946000000.0
Working on 58056-2019-09-30
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 73384000000.0, our lookback sum is 73384000000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 10839000000.0, our lookback sum is 10839000000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 90946000000.0, our lookback sum is 90946000000.0
Working on 58056-2020-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 68805000000.0, our lookback sum is 68805000000.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 11266000000.0, our lookback sum is 11266000000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 80071000000.0, our lookback sum is 80071000000.0
Working on 58056-2021-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 60277000000.0, our lookback sum is 60277000000.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 11853000000.0, our lookback sum is 11853000000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 72130000000.0, our lookback sum is 72130000000.0
Working on 68136-2002-01-29
	We dropped row 17, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 4261550000.0, our lookback sum is 4261550000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 267625461000.0, our lookback sum is 267625461000.0
Working on 68136-2003-01-30
	We dropped row 17, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 4664554000.0, our lookback sum is 4664554000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 265334256000.0, our lookback sum is 265334256000.0
Working on 68136-2004-01-30
	We dropped row 17, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 4869317000.0, our lookback sum is 4869317000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 310888679000.0, our lookback sum is 310888679000.0
Working on 68136-2005-01-31
	We dropped row 17, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 5231188000.0, our lookback sum is 5231188000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 412415148000.0, our lookback sum is 412415148000.0
Working on 68136-2006-01-30
	We dropped row 18, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 5232895000.0, our lookback sum is 5232895000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 501699713000.0, our lookback sum is 501699713000.0
Working on 68136-2007-01-29
	We dropped row 18, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 5519488000.0, our lookback sum is 5519488000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 583404825000.0, our lookback sum is 583404825000.0
Working on 68136-2008-01-31
Working on 68136-2009-01-29
	We dropped row 15, Total Liabilities, with lookback window of 15.
		Our row is valued at 277037343000.0, our lookback sum is 277037343000.0
	We dropped row 22, Total stockholder's equity, with lookback window of 4.
		Our row is valued at 5759943000.0, our lookback sum is 5739943000.0
	We dropped row 23, Total liabilities and stockholder's equity, with lookback window of 23.
		Our row is valued at 297422286000.0, our lookback sum is 297422286000.0
Working on 68136-2010-03-02
	We dropped row 7, Total financial instruments sold, not yet purchased. at fair value, with lookback window of 5.
		Our row is valued at 29500843000.0, our lookback sum is 29500843000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 395237551000.0, our lookback sum is 395237551000.0
	We dropped row 22, Total stockholder's equity, with lookback window of 4.
		Our row is valued at 8269656000.0, our lookback sum is 8269656000.0
	We dropped row 23, Total liabilities and stockholder's equity, with lookback window of 23.
		Our row is valued at 413032207000.0, our lookback sum is 413032207000.0
Working on 68136-2011-03-02
	We dropped row 7, Total financial instruments sold, not yet purchased, at fair value, with lookback window of 5.
		Our row is valued at 37759983000.0, our lookback sum is 37759983000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 352810071000.0, our lookback sum is 352810071000.0
	We dropped row 22, Total Morgan Stanley & Co. Incorporated stockholder's equity, with lookback window of 4.
		Our row is valued at 9694769000.0, our lookback sum is 9694769000.0
	We dropped row 24, Total stockholder's equity, with lookback window of 6.
		Our row is valued at 9702269000.0, our lookback sum is 9702269000.0
	We dropped row 25, Total liabilities and stockholder's equity, with lookback window of 25.
		Our row is valued at 372537340000.0, our lookback sum is 372537340000.0

Working on 68136-2012-02-29
	We dropped row 7, Total financial instruments sold, not yet purchased, at fair value, with lookback window of 5.
		Our row is valued at 32850811000.0, our lookback sum is 32850811000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 332970945000.0, our lookback sum is 332970945000.0
	We dropped row 20, Total Morgan Stanley & Co. LLC member's equity, with lookback window of 2.
		Our row is valued at 9293431000.0, our lookback sum is 9293431000.0
	We dropped row 22, Total member's equity, with lookback window of 4.
		Our row is valued at 9297181000.0, our lookback sum is 9297181000.0
	We dropped row 23, Total liabilities and member's equity, with lookback window of 23.
		Our row is valued at 352293126000.0, our lookback sum is 352293126000.0
Working on 68136-2013-03-01
	We dropped row 7, Total financial instruments sold, not yet purchased, at fair value, with lookback window of 5.
		Our row is valued at 34047352000.0, our lookback sum is 34047352000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 346942685000.0, our lookback sum is 346942685000.0
	We dropped row 20, Total Morgan Stanley & Co. LLC member's equity, with lookback window of 2.
		Our row is valued at 12097489000.0, our lookback sum is 12097489000.0
	We dropped row 22, Total member's equity, with lookback window of 4.
		Our row is valued at 12098739000.0, our lookback sum is 12098739000.0
	We dropped row 23, Total liabilities and member's equity, with lookback window of 23.
		Our row is valued at 369066424000.0, our lookback sum is 369066424000.0
Working on 68136-2014-03-04
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 351045000000.0, our lookback sum is 351045000000.0
	We dropped row 15, Total Morgan Stanley & Co. LLC member's equity, with lookback window of 2.
		Our row is valued at 6451000000.0, our lookback sum is 6451000000.0
	We dropped row 17, Total member's equity, with lookback window of 4.
		Our row is valued at 6451000000.0, our lookback sum is 6451000000.0
	We dropped row 18, Total liabilities and member's equity, with lookback window of 18.
		Our row is valued at 367496000000.0, our lookback sum is 367496000000.0
Working on 68136-2015-03-02
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 331231000000.0, our lookback sum is 331231000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 3903000000.0, our lookback sum is 3903000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 345134000000.0, our lookback sum is 345134000000.0
Working on 68136-2016-02-29
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 284402000000.0, our lookback sum is 284402000000.0
	We dropped row 16, Total member's equity, with lookback window of 2.
		Our row is valued at 5639000000.0, our lookback sum is 5639000000.0
	We dropped row 17, Total liabilities and member's equity, with lookback window of 17.
		Our row is valued at 301341000000.0, our lookback sum is 301341000000.0
Working on 68136-2017-03-01
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 291443000000.0, our lookback sum is 291443000000.0
	We dropped row 16, Total member's equity, with lookback window of 2.
		Our row is valued at 5295000000.0, our lookback sum is 5295000000.0
	We dropped row 17, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 308038000000.0, our lookback sum is 308034000000.0
Working on 68136-2018-03-01
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 288649000000.0, our lookback sum is 288649000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 5332000000.0, our lookback sum is 5332000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 305281000000.0, our lookback sum is 305281000000.0
Working on 68136-2019-03-01
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 282485000000.0, our lookback sum is 282485000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 8021000000.0, our lookback sum is 8021000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 303806000000.0, our lookback sum is 303806000000.0
Working on 68136-2021-02-26
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 385847000000.0, our lookback sum is 385847000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 10092000000.0, our lookback sum is 10092000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 409239000000.0, our lookback sum is 409239000000.0
Working on 72267-2003-05-30
	We dropped row 8, Payables and accrued liabilities:, with lookback window of 4.
		Our row is valued at 2781603000.0, our lookback sum is 2781603000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 57292974000.0, our lookback sum is 57292974000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 57702809000.0, our lookback sum is 57702809000.0
Working on 72267-2004-05-28
	We dropped row 7, Payables:, with lookback window of 4.
		Our row is valued at 3046503000.0, our lookback sum is 3046503000.0
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 62018809000.0, our lookback sum is 62018809000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 482409000.0, our lookback sum is 482409000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 63951218000.0, our lookback sum is 63951218000.0
Working on 72267-2005-05-31
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 76906488000.0, our lookback sum is 76906488000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 325623000.0, our lookback sum is 325623000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 78732111000.0, our lookback sum is 78732111000.0
Working on 72267-2006-05-30
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 73945334000.0, our lookback sum is 73945334000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 237601000.0, our lookback sum is 237601000.0
	We dropped row 16, Total liabilities and stockholder's equity, with lookback window of 16.
		Our row is valued at 174182935000.0, our lookback sum is 74182935000.0
Working on 72267-2007-05-29
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 87485932000.0, our lookback sum is 87485932000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 56900000.0, our lookback sum is 56900000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 87542832000.0, our lookback sum is 87542832000.0
Working on 72267-2008-05-30
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 16192669000.0, our lookback sum is 16192669000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 73966000.0, our lookback sum is 73966000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 16266635000.0, our lookback sum is 16266635000.0
Working on 72267-2009-06-03
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 14196392000.0, our lookback sum is 14196392000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 83400000.0, our lookback sum is 83400000.0
	We dropped row 16, Total liabilities and stockholder's equity, with lookback window of 16.
		Our row is valued at 14279792000.0, our lookback sum is 14279792000.0

Working on 72267-2010-06-01
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 67030133000.0, our lookback sum is 67030133000.0
	We dropped row 17, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 1072171000.0, our lookback sum is 1072171000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 68102304000.0, our lookback sum is 68102304000.0
Working on 72267-2012-03-15
	We dropped row 13, Total liabilities, with lookback window of 11.
		Our row is valued at 102085358000.0, our lookback sum is 102085358000.0
	We dropped row 17, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2742404000.0, our lookback sum is 2742404000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 16.
		Our row is valued at 104827762000.0, our lookback sum is 104827762000.0
Working on 72267-2012-05-30
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 111518220000.0, our lookback sum is 111518220000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2541275000.0, our lookback sum is 2541275000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 114059495000.0, our lookback sum is 114059495000.0
Working on 72267-2013-05-30
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 118681714000.0, our lookback sum is 118681714000.0
	We dropped row 17, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 3020100000.0, our lookback sum is 3020100000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 121701814000.0, our lookback sum is 121701814000.0
Working on 72267-2014-05-30
	We dropped row 13, Total liabilities, with lookback window of 12.
		Our row is valued at 124317519000.0, our lookback sum is 124317519000.0
	We dropped row 17, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 3067937000.0, our lookback sum is 3067937000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 127385456000.0, our lookback sum is 127385456000.0
Working on 72267-2015-06-01
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 106030731000.0, our lookback sum is 106030731000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2929606000.0, our lookback sum is 2929606000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 108960337000.0, our lookback sum is 108960337000.0
Working on 72267-2016-05-31
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 115346030000.0, our lookback sum is 115346030000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2579375000.0, our lookback sum is 2579375000.0
	We dropped row 16, Total liabilities and stockholder's equity, with lookback window of 16.
		Our row is valued at 117925405000.0, our lookback sum is 117925405000.0
Working on 72267-2017-05-30
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 138528489000.0, our lookback sum is 138528489000.0
	We dropped row 14, Additional paid-in capital, with lookback window of 1.
		Our row is valued at 3650000000.0, our lookback sum is 3650000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 2981841000.0, our lookback sum is 2981841000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 141510330000.0, our lookback sum is 141510330000.0
Working on 72267-2018-05-25
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 137925403000.0, our lookback sum is 137925403000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 3148545000.0, our lookback sum is 3148545000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 141073948000.0, our lookback sum is 141073948000.0
Working on 72267-2019-05-28
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 124457897000.0, our lookback sum is 124457897000.0
	We dropped row 16, Additional paid-in capital, with lookback window of 1.
		Our row is valued at 3716866000.0, our lookback sum is 3716866000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 3084406000.0, our lookback sum is 3084406000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 127542303000.0, our lookback sum is 127542303000.0
Working on 72267-2020-06-01
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 139007241000.0, our lookback sum is 139007241000.0
	We dropped row 17, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 3465907000.0, our lookback sum is 3465907000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 142473148000.0, our lookback sum is 142473148000.0
Working on 782124-2002-01-29
	We dropped row 16, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 3462488000.0, our lookback sum is 3462488000.0
	We dropped row 17, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 17.
		Our row is valued at 140655621000.0, our lookback sum is 140655621000.0
Working on 782124-2003-01-30
	We dropped row 16, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 3704442000.0, our lookback sum is 3704442000.0
	We dropped row 17, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 17.
		Our row is valued at 150559829000.0, our lookback sum is 150559829000.0
Working on 782124-2004-01-30
	We dropped row 17, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 4096046000.0, our lookback sum is 4096046000.0
	We dropped row 18, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 18.
		Our row is valued at 164601243000.0, our lookback sum is 164601243000.0
Working on 782124-2004-05-07
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 10913196000.0, our lookback sum is 10913196000.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 14759882000.0, our lookback sum is 14759872000.0
	We dropped row 11, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 11.
		Our row is valued at 25673078000.0, our lookback sum is 25673078000.0
Working on 782124-2005-01-31
	We dropped row 17, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 3272491000.0, our lookback sum is 3272491000.0
	We dropped row 18, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 18.
		Our row is valued at 193433468000.0, our lookback sum is 193433468000.0
Working on 782124-2006-01-30
	We dropped row 18, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 3727485000.0, our lookback sum is 3727485000.0
	We dropped row 19, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 19.
		Our row is valued at 191806579000.0, our lookback sum is 191806579000.0
Working on 782124-2007-01-29
	We dropped row 18, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 3658729000.0, our lookback sum is 3658729000.0
	We dropped row 19, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 19.
		Our row is valued at 236190719000.0, our lookback sum is 236190719000.0
Working on 782124-2008-01-31
	We dropped row 18, Total Stockholder's Equity, with lookback window of 5.
		Our row is valued at 2921003000.0, our lookback sum is 2921003000.0
	We dropped row 19, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 19.
		Our row is valued at 258125104000.0, our lookback sum is 258125104000.0
Working on 782124-2009-03-02
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 395123286000.0, our lookback sum is 395123286000.0
	We dropped row 12, Total liabilities and stockholder's equity, with lookback window of 12.
		Our row is valued at 399544757000.0, our lookback sum is 399544757000.0

Working on 782124-2010-03-01
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 320976000000.0, our lookback sum is 320976000000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 329205000000.0, our lookback sum is 329205000000.0
Working on 782124-2011-03-02
	We dropped row 10, Total liabilities (*), with lookback window of 10.
		Our row is valued at 351776000000.0, our lookback sum is 351776000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 362019000000.0, our lookback sum is 362019000000.0
Working on 782124-2012-02-29
	We dropped row 10, Total liabilities (A), with lookback window of 10.
		Our row is valued at 360040000000.0, our lookback sum is 360040000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 371293000000.0, our lookback sum is 371293000000.0
Working on 782124-2013-03-01
	We dropped row 10, Total liabilities (a), with lookback window of 10.
		Our row is valued at 437466000000.0, our lookback sum is 437466000000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 451412000000.0, our lookback sum is 451412000000.0
Working on 782124-2014-03-05
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 355063000000.0, our lookback sum is 355063000000.0
	We dropped row 13, Total liabilities and member's equity, with lookback window of 13.
		Our row is valued at 372319000000.0, our lookback sum is 372319000000.0
Working on 782124-2015-02-27
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 367038000000.0, our lookback sum is 367038000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 15293000000.0, our lookback sum is 15293000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 397361000000.0, our lookback sum is 397361000000.0
Working on 782124-2016-02-29
	We dropped row 11, Total liabilities(a), with lookback window of 11.
		Our row is valued at 340539000000.0, our lookback sum is 340539000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 14511000000.0, our lookback sum is 14511000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 369680000000.0, our lookback sum is 369680000000.0
Working on 782124-2017-03-01
	We dropped row 11, Total liabilities(a, with lookback window of 11.
		Our row is valued at 347908000000.0, our lookback sum is 347908000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 17447000000.0, our lookback sum is 17447000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 379355000000.0, our lookback sum is 379355000000.0
Working on 782124-2018-02-27
	We dropped row 11, Total liabilities(a, with lookback window of 11.
		Our row is valued at 317412000000.0, our lookback sum is 317412000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 19758000000.0, our lookback sum is 19758000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 351170000000.0, our lookback sum is 351170000000.0
Working on 782124-2018-02-28
	We dropped row 11, Total liabilities(a, with lookback window of 11.
		Our row is valued at 317412000000.0, our lookback sum is 317412000000.0
	We dropped row 15, Total member's equity, with lookback window of 2.
		Our row is valued at 19758000000.0, our lookback sum is 19758000000.0
	We dropped row 16, Total liabilities and member's equity, with lookback window of 16.
		Our row is valued at 351170000000.0, our lookback sum is 351170000000.0
Working on 782124-2019-02-28
	We dropped row 10, Total liabilities³, with lookback window of 10.
		Our row is valued at 427075000000.0, our lookback sum is 427075000000.0
	We dropped row 14, Total member's equity, with lookback window of 2.
		Our row is valued at 9190000000.0, our lookback sum is 9190000000.0
	We dropped row 15, Total liabilities and member's equity, with lookback window of 15.
		Our row is valued at 460265000000.0, our lookback sum is 460265000000.0
Working on 782124-2020-04-01
	We dropped row 10, Total liabilities(a, with lookback window of 10.
		Our row is valued at 455162000000.0, our lookback sum is 455162000000.0
	We dropped row 14, Total member's equity, with lookback window of 2.
		Our row is valued at 11783000000.0, our lookback sum is 11783000000.0
	We dropped row 15, Total liabilities and member's equity, with lookback window of 15.
		Our row is valued at 490945000000.0, our lookback sum is 490945000000.0
Working on 782124-2021-03-01
	We dropped row 10, Total liabilities (a), with lookback window of 10.
		Our row is valued at 567851000000.0, our lookback sum is 567851000000.0
	We dropped row 14, Total member's equity, with lookback window of 2.
		Our row is valued at 12931000000.0, our lookback sum is 12931000000.0
	We dropped row 15, Total liabilities and member's equity, with lookback window of 15.
		Our row is valued at 609782000000.0, our lookback sum is 609782000000.0
Working on 803012-2002-12-31
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 3301933000.0, our lookback sum is 3301933000.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 161199000.0, our lookback sum is 161199000.0
Working on 803012-2003-12-31
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 4928672000.0, our lookback sum is 4928672000.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 170318000.0, our lookback sum is 170318000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 6183990000.0, our lookback sum is 6183990000.0
Working on 803012-2005-01-03
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 198908000.0, our lookback sum is 198908000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 8114219000.0, our lookback sum is 8114219000.0
Working on 803012-2006-01-03
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 220689000.0, our lookback sum is 220689000.0
	We dropped row 12, Total liabilities and stockholder's equity, with lookback window of 12.
		Our row is valued at 9125399000.0, our lookback sum is 9125399000.0
Working on 803012-2007-01-29
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 210968000.0, our lookback sum is 210968000.0
	We dropped row 12, Total liabilities and stockholder's equity, with lookback window of 12.
		Our row is valued at 11506606000.0, our lookback sum is 11506606000.0
Working on 803012-2007-12-28
	We dropped row 7, Total liabilities and stockholder's equity, with lookback window of 7.
		Our row is valued at 10048531000.0, our lookback sum is 10048531000.0
Working on 803012-2008-12-30
	We dropped row 7, Total liabilities and member's equity, with lookback window of 7.
		Our row is valued at 7518789000.0, our lookback sum is 7518789000.0
Working on 803012-2009-12-29
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 11434030000.0, our lookback sum is 11434030000.0
Working on 803012-2010-12-27
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 23023259000.0, our lookback sum is 23023259000.0
Working on 803012-2011-12-21
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 25623617000.0, our lookback sum is 25623617000.0
Working on 803012-2012-12-26
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 35860733000.0, our lookback sum is 35860733000.0

Working on 803012-2013-12-26
	We dropped row 8, Total Liabilities, with lookback window of 8.
		Our row is valued at 32334728000.0, our lookback sum is 32334728000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 33822818000.0, our lookback sum is 33822818000.0
Working on 803012-2014-12-30
	We dropped row 7, Total Liabilities, with lookback window of 7.
		Our row is valued at 34444714000.0, our lookback sum is 34444714000.0
	We dropped row 10, Total Liabilities and Member's Equity, with lookback window of 10.
		Our row is valued at 35918709000.0, our lookback sum is 35918709000.0
Working on 803012-2015-12-22
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 34138609000.0, our lookback sum is 34138609000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 34818830000.0, our lookback sum is 34818830000.0
Working on 803012-2016-12-22
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 36774819000.0, our lookback sum is 36774819000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 37497845000.0, our lookback sum is 37497845000.0
Working on 803012-2018-03-22
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 45629060000.0, our lookback sum is 45629060000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 46381560000.0, our lookback sum is 46381560000.0
Working on 803012-2019-12-20
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 31820835000.0, our lookback sum is 31820835000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 32682640000.0, our lookback sum is 32682640000.0
Working on 803012-2020-12-22
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 38627508000.0, our lookback sum is 38627508000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 39653089000.0, our lookback sum is 39653089000.0
Working on 851376-2002-03-01
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 72638615000.0, our lookback sum is 72638615000.0
Working on 851376-2003-03-03
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 103369408000.0, our lookback sum is 103369408000.0
Working on 851376-2004-03-01
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 113650937000.0, our lookback sum is 113650937000.0
Working on 851376-2005-03-02
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 174937091000.0, our lookback sum is 174937091000.0
Working on 851376-2006-03-01
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 194436796000.0, our lookback sum is 194436796000.0
Working on 851376-2007-03-14
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 234088093000.0, our lookback sum is 234088093000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 236022658000.0, our lookback sum is 236022658000.0
Working on 851376-2008-02-29
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 295746672000.0, our lookback sum is 295746672000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 2074744000.0, our lookback sum is 2074734000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 297821416000.0, our lookback sum is 297821416000.0
Working on 851376-2009-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 231480140000.0, our lookback sum is 231480140000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 6448987000.0, our lookback sum is 6448977000.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 240429127000.0, our lookback sum is 240429127000.0
Working on 851376-2010-03-01
	We dropped row 9, Total, with lookback window of 9.
		Our row is valued at 316546000000.0, our lookback sum is 316546000000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7830000000.0, our lookback sum is 7830000000.0
	We dropped row 16, Total liabilities and stockholder's equity, with lookback window of 16.
		Our row is valued at 326876000000.0, our lookback sum is 326876000000.0
Working on 851376-2011-03-15
	We dropped row 9, Total, with lookback window of 9.
		Our row is valued at 320264000000.0, our lookback sum is 320264000000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7343000000.0, our lookback sum is 7343000000.0
	We dropped row 16, Total liabilities and stockhoider's equity, with lookback window of 16.
		Our row is valued at 330107000000.0, our lookback sum is 330107000000.0
Working on 851376-2012-02-29
	We dropped row 10, Total, with lookback window of 10.
		Our row is valued at 296990000000.0, our lookback sum is 296990000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 6986000000.0, our lookback sum is 6986000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 306476000000.0, our lookback sum is 306476000000.0
Working on 851376-2013-03-01
	We dropped row 10, Total, with lookback window of 10.
		Our row is valued at 299299000000.0, our lookback sum is 299299000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7264000000.0, our lookback sum is 7264000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 309063000000.0, our lookback sum is 309063000000.0
Working on 851376-2014-03-04
Working on 851376-2015-03-02
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7857000000.0, our lookback sum is 7857000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 248026000000.0, our lookback sum is 248026000000.0
Working on 851376-2016-02-29
	We dropped row 12, Total liabilities, with lookback window of 12.
		Our row is valued at 164983000000.0, our lookback sum is 164983000000.0
	We dropped row 17, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7106000000.0, our lookback sum is 7106000000.0
	We dropped row 18, Total liabilities and stockholder's equity, with lookback window of 18.
		Our row is valued at 172089000000.0, our lookback sum is 172089000000.0
Working on 851376-2017-03-01
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 145080000000.0, our lookback sum is 145080000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7431000000.0, our lookback sum is 7431000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 152511000000.0, our lookback sum is 152511000000.0
Working on 851376-2018-02-28
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 98948000000.0, our lookback sum is 98948000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7512000000.0, our lookback sum is 7512000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 106460000000.0, our lookback sum is 106460000000.0

Working on 851376-2019-03-01
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 98750000000.0, our lookback sum is 98750000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 6916000000.0, our lookback sum is 6916000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 105666000000.0, our lookback sum is 105666000000.0
Working on 851376-2020-03-06
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 91805000000.0, our lookback sum is 91805000000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7362000000.0, our lookback sum is 7362000000.0
	We dropped row 16, Total liabilities and stockholder's equity, with lookback window of 16.
		Our row is valued at 99167000000.0, our lookback sum is 99167000000.0
Working on 851376-2021-03-01
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 106492000000.0, our lookback sum is 106492000000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 6099000000.0, our lookback sum is 6099000000.0
	We dropped row 17, Total liabilities and stockholder's equity, with lookback window of 17.
		Our row is valued at 112591000000.0, our lookback sum is 112591000000.0
Working on 853784-2002-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 34644573000.0, our lookback sum is 34644573000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 35226132000.0, our lookback sum is 35226132000.0

CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 853784-2003-02-28.csv


CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 853784-2004-03-01.csv


CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 853784-2005-02-28.csv

Working on 853784-2006-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 48256356000.0, our lookback sum is 48256356000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 50025689000.0, our lookback sum is 50025689000.0
Working on 853784-2007-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 79757021000.0, our lookback sum is 79757021000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 1578415000.0, our lookback sum is 1578415000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 81435436000.0, our lookback sum is 81435436000.0
Working on 853784-2007-03-09
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 79757021000.0, our lookback sum is 79757021000.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 1578415000.0, our lookback sum is 1578415000.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 81435436000.0, our lookback sum is 81435436000.0
Working on 853784-2008-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 66877360000.0, our lookback sum is 66877360000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 68835607000.0, our lookback sum is 68835607000.0
Working on 853784-2009-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 59918632000.0, our lookback sum is 59918632000.0
	We dropped row 11, Total liabilities and stockholders' equity, with lookback window of 11.
		Our row is valued at 61543858000.0, our lookback sum is 61543858000.0
Working on 853784-2010-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 59140672000.0, our lookback sum is 59140672000.0
	We dropped row 11, Total liabilities and stockholders' equity, with lookback window of 11.
		Our row is valued at 60683961000.0, our lookback sum is 60683961000.0
Working on 853784-2011-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 82287659000.0, our lookback sum is 82287659000.0
	We dropped row 11, Total liabilities and stockholders' equity, with lookback window of 11.
		Our row is valued at 83850980000.0, our lookback sum is 83850980000.0
Working on 853784-2012-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 54161306000.0, our lookback sum is 54161306000.0
	We dropped row 11, Total liabilities and stockholder's equity, with lookback window of 11.
		Our row is valued at 55704086000.0, our lookback sum is 55704086000.0
Working on 853784-2013-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 76340920000.0, our lookback sum is 76340920000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 77900039000.0, our lookback sum is 77900039000.0
Working on 853784-2014-03-04
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 72839292000.0, our lookback sum is 72839292000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 74314954000.0, our lookback sum is 74314954000.0
Working on 853784-2015-03-09
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 80024434000.0, our lookback sum is 80024434000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 81418513000.0, our lookback sum is 81418513000.0
Working on 853784-2016-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 70097715000.0, our lookback sum is 70097715000.0
	We dropped row 9, Total liabilities and stockholder's equity, with lookback window of 9.
		Our row is valued at 71580510000.0, our lookback sum is 71580510000.0
Working on 853784-2017-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 70269822000.0, our lookback sum is 70269822000.0
	We dropped row 9, Total liabilities and shareholder's equity, with lookback window of 9.
		Our row is valued at 71759167000.0, our lookback sum is 71759167000.0
Working on 853784-2018-03-05
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 89723445000.0, our lookback sum is 89723445000.0
	We dropped row 12, Shareholder's equity, with lookback window of 3.
		Our row is valued at 835153000.0, our lookback sum is 835153000.0
	We dropped row 13, Total liabilities and shareholder's equity, with lookback window of 13.
		Our row is valued at 91308598000.0, our lookback sum is 91308598000.0
Working on 853784-2019-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 103306000000.0, our lookback sum is 103306000000.0
	We dropped row 12, Shareholder's equity, with lookback window of 3.
		Our row is valued at 781000000.0, our lookback sum is 781000000.0
	We dropped row 13, Total liabilities and shareholder's equity, with lookback window of 13.
		Our row is valued at 105062000000.0, our lookback sum is 105062000000.0
Working on 853784-2020-03-02
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 75479000000.0, our lookback sum is 75479000000.0
	We dropped row 12, Shareholder's equity, with lookback window of 3.
		Our row is valued at 942000000.0, our lookback sum is 942000000.0
	We dropped row 13, Total liabilities and shareholder's equity, with lookback window of 13.
		Our row is valued at 77321000000.0, our lookback sum is 77321000000.0
Working on 853784-2021-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 45452000000.0, our lookback sum is 45452000000.0
	We dropped row 12, Shareholder's equity, with lookback window of 3.
		Our row is valued at 914000000.0, our lookback sum is 914000000.0
	We dropped row 13, Total liabilities and shareholder's equity, with lookback window of 13.
		Our row is valued at 47166000000.0, our lookback sum is 47166000000.0
Working on 867626-2004-04-28
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 1454415871.0, our lookback sum is 1454415871.0
	We dropped row 11, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 76124808.0, our lookback sum is 76124808.0
	We dropped row 12, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 12.
		Our row is valued at 1530540679.0, our lookback sum is 1530540679.0

Working on 867626-2005-04-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 1593624686.0, our lookback sum is 1593624686.0
	We dropped row 12, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 76335710.0, our lookback sum is 76335710.0
	We dropped row 13, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 13.
		Our row is valued at 1669960396.0, our lookback sum is 1669960396.0
Working on 867626-2006-04-28
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 4362115901.0, our lookback sum is 4362115901.0
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 79592321.0, our lookback sum is 79592321.0
	We dropped row 12, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 12.
		Our row is valued at 4441708222.0, our lookback sum is 4441708222.0
Working on 867626-2007-04-26
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 4341724743.0, our lookback sum is 4341724743.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 80962451.0, our lookback sum is 80962451.0
	We dropped row 11, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 11.
		Our row is valued at 4422687194.0, our lookback sum is 4422687194.0
Working on 867626-2008-02-29
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 3040207669.0, our lookback sum is 3040207669.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 84744358.0, our lookback sum is 84744358.0
	We dropped row 11, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 11.
		Our row is valued at 3124952027.0, our lookback sum is 3124952027.0
Working on 867626-2009-03-02
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 6438543382.0, our lookback sum is 6438543382.0
	We dropped row 7, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 98163322.0, our lookback sum is 98163322.0
	We dropped row 8, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 8.
		Our row is valued at 6536706704.0, our lookback sum is 6536706704.0
Working on 867626-2011-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 20692423809.0, our lookback sum is 20692423809.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 133176411.0, our lookback sum is 133176411.0
	We dropped row 13, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 13.
		Our row is valued at 20895600220.0, our lookback sum is 20895600220.0
Working on 867626-2012-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 29199862000.0, our lookback sum is 29199862000.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 126083000.0, our lookback sum is 126083000.0
	We dropped row 13, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 13.
		Our row is valued at 29545945000.0, our lookback sum is 29545945000.0
Working on 867626-2014-03-04
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 160612000.0, our lookback sum is 160612000.0
	We dropped row 13, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 13.
		Our row is valued at 29086436000.0, our lookback sum is 29086436000.0
Working on 867626-2016-02-26
	We dropped row 10, Total liabilities, with lookback window of 9.
		Our row is valued at 33328008000.0, our lookback sum is 33328008000.0
	We dropped row 16, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 619163000.0, our lookback sum is 619163000.0
	We dropped row 17, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 16.
		Our row is valued at 34167171000.0, our lookback sum is 34167171000.0
Working on 867626-2017-02-28
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 28385236000.0, our lookback sum is 28385236000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 681649000.0, our lookback sum is 681649000.0
	We dropped row 15, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 15.
		Our row is valued at 29251885000.0, our lookback sum is 29251885000.0
Working on 867626-2018-02-27
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 31113291000.0, our lookback sum is 31113291000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 763519000.0, our lookback sum is 763519000.0
	We dropped row 16, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 16.
		Our row is valued at 32061810000.0, our lookback sum is 32061810000.0
Working on 867626-2019-02-27
	We dropped row 1, Short-termborowings, with lookback window of 1.
		Our row is valued at 1386100000.0, our lookback sum is 1386100000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 32565006000.0, our lookback sum is 32565006000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 803517000.0, our lookback sum is 803517000.0
	We dropped row 16, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 16.
		Our row is valued at 33843523000.0, our lookback sum is 33843523000.0
Working on 867626-2020-02-27
	We dropped row 1, Short-termborowings, with lookback window of 1.
		Our row is valued at 507008000.0, our lookback sum is 507008000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 32802814000.0, our lookback sum is 32802814000.0
	We dropped row 15, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 866866000.0, our lookback sum is 866866000.0
	We dropped row 16, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 16.
		Our row is valued at 34444680000.0, our lookback sum is 34444680000.0
Working on 867626-2021-02-26
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 30900008000.0, our lookback sum is 30900008000.0
	We dropped row 14, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 1039247000.0, our lookback sum is 1039247000.0
	We dropped row 15, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 15.
		Our row is valued at 32714255000.0, our lookback sum is 32714255000.0
Working on 87634-2002-03-15
	We dropped row 7, Total liabilities, with lookback window of 6.
		Our row is valued at 27928000000.0, our lookback sum is 27928000000.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2014000000.0, our lookback sum is 2014000000.0
	We dropped row 11, Total, with lookback window of 10.
		Our row is valued at 29942000000.0, our lookback sum is 29942000000.0
Working on 87634-2003-02-27
	We dropped row 7, Total liabilities, with lookback window of 6.
		Our row is valued at 28108000000.0, our lookback sum is 28108000000.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 1787000000.0, our lookback sum is 1787000000.0
	We dropped row 11, Total, with lookback window of 10.
		Our row is valued at 29895000000.0, our lookback sum is 29895000000.0

CLIENT-ERROR: WE COULD NOT DOWNLOAD SPLIT DATA FOR 87634-2005-02-28.csv

Working on 87634-2006-02-28
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 26837000000.0, our lookback sum is 26837000000.0
	We dropped row 9, Common stock - 7,000,000 shares authorized; $.10 par value per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 12, Total stockhobier's equity, with lookback window of 2.
		Our row is valued at 1697000000.0, our lookback sum is 1697000000.0
	We dropped row 13, Total, with lookback window of 13.
		Our row is valued at 28754000000.0, our lookback sum is 28754000000.0

Working on 87634-2006-09-21
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 26837000000.0, our lookback sum is 26837000000.0
	We dropped row 9, Common stock - 7,000,000 shares authorized; $.10 par value per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 1697000000.0, our lookback sum is 1697000000.0
	We dropped row 13, Total, with lookback window of 13.
		Our row is valued at 28754000000.0, our lookback sum is 28754000000.0
Working on 87634-2007-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 23124000000.0, our lookback sum is 23124000000.0
	We dropped row 9, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 12, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 1589000000.0, our lookback sum is 1589000000.0
	We dropped row 13, Total liabilities and stockholder's equity, with lookback window of 13.
		Our row is valued at 24933000000.0, our lookback sum is 24933000000.0
Working on 87634-2008-03-03
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 23422000000.0, our lookback sum is 23422000000.0
	We dropped row 8, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2332000000.0, our lookback sum is 2332000000.0
	We dropped row 12, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 12.
		Our row is valued at 25974000000.0, our lookback sum is 25974000000.0
Working on 87634-2009-02-27
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 22691000000.0, our lookback sum is 22691000000.0
	We dropped row 8, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2228000000.0, our lookback sum is 2228000000.0
	We dropped row 12, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 12.
		Our row is valued at 25139000000.0, our lookback sum is 25139000000.0
Working on 87634-2010-03-01
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 28281000000.0, our lookback sum is 28281000000.0
	We dropped row 7, Common stock 7,000,000 shares authorized; $.10 par value per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 9, Retained earnings, with lookback window of 1.
		Our row is valued at 1079000000.0, our lookback sum is 1077000000.0
Working on 87634-2011-02-28
	We dropped row 4, Total, with lookback window of 4.
		Our row is valued at 33658000000.0, our lookback sum is 33658000000.0
	We dropped row 7, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2239000000.0, our lookback sum is 2239000000.0
	We dropped row 11, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 11.
		Our row is valued at 36117000000.0, our lookback sum is 36117000000.0
Working on 87634-2012-03-05
	We dropped row 4, Total, with lookback window of 4.
		Our row is valued at 36650000000.0, our lookback sum is 36650000000.0
	We dropped row 7, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2274000000.0, our lookback sum is 2274000000.0
	We dropped row 11, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 11.
		Our row is valued at 39169000000.0, our lookback sum is 39169000000.0
Working on 87634-2013-02-26
	We dropped row 4, Total, with lookback window of 4.
		Our row is valued at 41427000000.0, our lookback sum is 41427000000.0
	We dropped row 7, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2417000000.0, our lookback sum is 2417000000.0
	We dropped row 11, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 11.
		Our row is valued at 44159000000.0, our lookback sum is 44159000000.0
Working on 87634-2014-02-26
	We dropped row 5, Total, with lookback window of 5.
		Our row is valued at 37740000000.0, our lookback sum is 37740000000.0
	We dropped row 8, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2654000000.0, our lookback sum is 2654000000.0
	We dropped row 12, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 12.
		Our row is valued at 40709000000.0, our lookback sum is 40709000000.0
Working on 87634-2015-02-25
	We dropped row 4, Total, with lookback window of 4.
		Our row is valued at 36715000000.0, our lookback sum is 36715000000.0
	We dropped row 7, Preferred stock - 3,000,000 shares authorized; $.10 par value per share; none issued, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 8, per share; 2,823,000 shares issued and outstanding, with lookback window of 2.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 2920000000.0, our lookback sum is 2920000000.0
	We dropped row 12, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 12.
		Our row is valued at 39950000000.0, our lookback sum is 39950000000.0
Working on 87634-2017-02-27
	We dropped row 4, Total, with lookback window of 4.
		Our row is valued at 39254000000.0, our lookback sum is 39254000000.0
	We dropped row 6, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 9, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 3740000000.0, our lookback sum is 3740000000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 42994000000.0, our lookback sum is 42994000000.0
Working on 87634-2018-02-27
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 35197000000.0, our lookback sum is 35197000000.0
	We dropped row 6, per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 9, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 4659000000.0, our lookback sum is 4659000000.0
	We dropped row 10, Total liabilities and stockholder's equity, with lookback window of 10.
		Our row is valued at 39856000000.0, our lookback sum is 39856000000.0
Working on 87634-2019-02-26
	We dropped row 4, Total, with lookback window of 4.
		Our row is valued at 36928000000.0, our lookback sum is 36928000000.0
	We dropped row 7, Common stock - 7,000,000 shares authorized; $.10 par value per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 10, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 4945000000.0, our lookback sum is 4945000000.0
	We dropped row 11, Total liabilities, subordinated borrowings, and stockholder's equity, with lookback window of 11.
		Our row is valued at 42058000000.0, our lookback sum is 42058000000.0
Working on 87634-2020-02-27
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 43888000000.0, our lookback sum is 43888000000.0
	We dropped row 4, Common stock - 7,000,000 shares authorized; $.10 par value per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 7, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 6546000000.0, our lookback sum is 6546000000.0
	We dropped row 8, Total liabilities and stockholder's equity, with lookback window of 8.
		Our row is valued at 50434000000.0, our lookback sum is 50434000000.0

Working on 87634-2021-02-26
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 67246000000.0, our lookback sum is 67246000000.0
	We dropped row 4, Common stock - 7,000,000 shares authorized; $.10 par value per share; 2,823,000 shares issued and outstanding, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 7, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 7673000000.0, our lookback sum is 7673000000.0
	We dropped row 8, Total liabilities and stockholder's equity, with lookback window of 8.
		Our row is valued at 74919000000.0, our lookback sum is 74919000000.0
Working on 877559-2002-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 7841718000.0, our lookback sum is 7841718000.0
	We dropped row 14, Total shareholder's equity, with lookback window of 5.
		Our row is valued at 212367000.0, our lookback sum is 212367000.0
	We dropped row 15, Total liabilities and shareholder's equity, with lookback window of 15.
		Our row is valued at 8137085000.0, our lookback sum is 8137085000.0
Working on 877559-2003-03-03
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 6785644000.0, our lookback sum is 6785644000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 7084535000.0, our lookback sum is 7084535000.0
Working on 877559-2004-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 11202549000.0, our lookback sum is 11202549000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 11507401000.0, our lookback sum is 11507401000.0
Working on 877559-2005-03-01
	We dropped row 6, Total liabilities, with lookback window of 6.
		Our row is valued at 20322431000.0, our lookback sum is 20322431000.0
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 20934619000.0, our lookback sum is 20934619000.0
Working on 877559-2006-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 24937850000.0, our lookback sum is 24937850000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 25552961000.0, our lookback sum is 25552961000.0
Working on 877559-2007-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 56391017000.0, our lookback sum is 56391017000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 57022134000.0, our lookback sum is 57022134000.0
Working on 877559-2008-02-29
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 79272746000.0, our lookback sum is 79272746000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 79937739000.0, our lookback sum is 79937739000.0
Working on 877559-2009-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 42857705000.0, our lookback sum is 42857705000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 43584859000.0, our lookback sum is 43584859000.0
Working on 877559-2010-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 36720213000.0, our lookback sum is 36720213000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 37466004000.0, our lookback sum is 37466004000.0
Working on 877559-2011-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 31007221000.0, our lookback sum is 31007221000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 32168739000.0, our lookback sum is 32168739000.0
Working on 877559-2012-02-29
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 29555972000.0, our lookback sum is 29555972000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 30743833000.0, our lookback sum is 30743833000.0
Working on 877559-2013-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 24006958000.0, our lookback sum is 24006958000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 25138886000.0, our lookback sum is 25138886000.0
Working on 877559-2014-03-04
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 32106565000.0, our lookback sum is 32106565000.0
	We dropped row 9, Total liabilities and member's equity, with lookback window of 9.
		Our row is valued at 33277278000.0, our lookback sum is 33277278000.0
Working on 877559-2015-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 30962897000.0, our lookback sum is 30962897000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 32166280000.0, our lookback sum is 32166280000.0
Working on 877559-2016-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 32471009000.0, our lookback sum is 32471009000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 33707317000.0, our lookback sum is 33707317000.0
Working on 877559-2016-04-25
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 32471009000.0, our lookback sum is 32471009000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 33707317000.0, our lookback sum is 33707317000.0
Working on 877559-2018-04-02
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 33288927000.0, our lookback sum is 33288927000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 34633973000.0, our lookback sum is 34633973000.0
Working on 877559-2018-04-05
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 26446132000.0, our lookback sum is 26446132000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 27738603000.0, our lookback sum is 27738603000.0
Working on 877559-2019-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 52607191000.0, our lookback sum is 52607191000.0
	We dropped row 11, Total Member's Equity, with lookback window of 2.
		Our row is valued at 1392296000.0, our lookback sum is 1392296000.0
	We dropped row 12, Total liabilities and member's equity, with lookback window of 12.
		Our row is valued at 53999487000.0, our lookback sum is 53999487000.0
Working on 877559-2020-03-02
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 29650201000.0, our lookback sum is 29650201000.0
	We dropped row 10, Total Member's Equity, with lookback window of 2.
		Our row is valued at 1462511000.0, our lookback sum is 1462511000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 31112712000.0, our lookback sum is 31112712000.0
Working on 877559-2021-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 30742881000.0, our lookback sum is 30742881000.0
	We dropped row 10, Total Member's Equity, with lookback window of 2.
		Our row is valued at 1504968000.0, our lookback sum is 1504968000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 32247849000.0, our lookback sum is 32247849000.0
Working on 890203-2002-03-01
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 8014792.0, our lookback sum is 8014792.0
	We dropped row 7, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 11173325.0, our lookback sum is 11173325.0
	We dropped row 8, Total liabilities and stockholder's equity, with lookback window of 8.
		Our row is valued at 19188117.0, our lookback sum is 19188117.0

Working on 890203-2003-02-28
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 176877.0, our lookback sum is 176877.0
	We dropped row 5, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 11548020.0, our lookback sum is 11548020.0
	We dropped row 6, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 11724897.0, our lookback sum is 11724897.0
Working on 890203-2004-05-03
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 344602.0, our lookback sum is 344602.0
	We dropped row 6, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 11280622.0, our lookback sum is 11280622.0
	We dropped row 7, Total liabilities and stockholder's equity, with lookback window of 7.
		Our row is valued at 11625224.0, our lookback sum is 11625224.0
Working on 890203-2005-02-22
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 120250.0, our lookback sum is 120250.0
	We dropped row 5, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 10693576.0, our lookback sum is 10693576.0
	We dropped row 6, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 10813826.0, our lookback sum is 10813826.0
Working on 890203-2006-02-28
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 470369.0, our lookback sum is 470369.0
	We dropped row 6, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 11556236.0, our lookback sum is 11556236.0
	We dropped row 7, Total liabilities and stockholder's equity, with lookback window of 7.
		Our row is valued at 12026605.0, our lookback sum is 12026605.0
Working on 890203-2007-05-30
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 209921.0, our lookback sum is 209921.0
	We dropped row 6, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 12172455.0, our lookback sum is 12172455.0
	We dropped row 7, TOTAL LIABILITIES AND STOCKHOLDERS EQUITY, with lookback window of 7.
		Our row is valued at 12382376.0, our lookback sum is 12382376.0
Working on 890203-2008-05-30
	We dropped row 2, Total liabilities, with lookback window of 2.
		Our row is valued at 914864.0, our lookback sum is 914864.0
	We dropped row 6, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 12355749.0, our lookback sum is 12355749.0
	We dropped row 7, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 7.
		Our row is valued at 13270613.0, our lookback sum is 13270613.0
Working on 890203-2009-05-28
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 1635054.0, our lookback sum is 1635054.0
	We dropped row 7, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 12452197.0, our lookback sum is 12452197.0
	We dropped row 8, TOTAL LIABILITIES AND STOCKHOLDERS EQUITY, with lookback window of 8.
		Our row is valued at 14087251.0, our lookback sum is 14087251.0
Working on 890203-2010-05-28
	We dropped row 4, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 12457835.0, our lookback sum is 12457835.0
	We dropped row 5, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 5.
		Our row is valued at 13079371.0, our lookback sum is 13079371.0
Working on 890203-2011-05-31
	We dropped row 4, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 10796533.0, our lookback sum is 10796533.0
	We dropped row 5, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 5.
		Our row is valued at 10930496.0, our lookback sum is 10930496.0
Working on 890203-2012-05-30
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 134176.0, our lookback sum is 134176.0
	We dropped row 5, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 9662015.0, our lookback sum is 9662015.0
	We dropped row 6, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 9796191.0, our lookback sum is 9796191.0
Working on 890203-2013-05-29
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 201430.0, our lookback sum is 201430.0
	We dropped row 5, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 8820325.0, our lookback sum is 8820325.0
	We dropped row 6, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 9021755.0, our lookback sum is 9021755.0
Working on 890203-2014-02-28
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 420050.0, our lookback sum is 420050.0
	We dropped row 5, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 8150709.0, our lookback sum is 8150709.0
	We dropped row 6, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 8570759.0, our lookback sum is 8570759.0
Working on 890203-2015-03-02
	We dropped row 1, Total liabilities, with lookback window of 1.
		Our row is valued at 290739.0, our lookback sum is 290739.0
	We dropped row 5, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 8230425.0, our lookback sum is 8230425.0
	We dropped row 6, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 8521164.0, our lookback sum is 8521164.0
Working on 890203-2016-02-26
	We dropped row 4, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7850972.0, our lookback sum is 7850972.0
	We dropped row 5, Total liability and stockholder's equity, with lookback window of 5.
		Our row is valued at 8258303.0, our lookback sum is 8258303.0
Working on 890203-2017-03-15
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 1853513.0, our lookback sum is 1853513.0
	We dropped row 7, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 248460496.0, our lookback sum is 248460496.0
	We dropped row 8, Total liabilities and stockholder's equity, with lookback window of 8.
		Our row is valued at 250314009.0, our lookback sum is 250314009.0
Working on 890203-2018-03-01
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 29725203.0, our lookback sum is 29725203.0
	We dropped row 11, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 228685.0, our lookback sum is 228684.0
	We dropped row 12, Total liabilities and stockholder's equity, with lookback window of 12.
		Our row is valued at 29953888.0, our lookback sum is 29953888.0
Working on 890203-2019-03-07
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 44327774.0, our lookback sum is 44327774.0
	We dropped row 13, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 231959.0, our lookback sum is 231958.0
	We dropped row 14, Total liabilities and stockholder's equity, with lookback window of 14.
		Our row is valued at 44559733.0, our lookback sum is 44559733.0
Working on 890203-2020-03-02
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 51598227.0, our lookback sum is 51598227.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 232042.0, our lookback sum is 232041.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 51830269.0, our lookback sum is 51830269.0
Working on 890203-2020-03-05
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 51598227.0, our lookback sum is 51598227.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 232042.0, our lookback sum is 232041.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 51830269.0, our lookback sum is 51830269.0

Working on 890203-2021-03-01
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 40998286.0, our lookback sum is 40998286.0
	We dropped row 14, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 258566.0, our lookback sum is 258565.0
	We dropped row 15, Total liabilities and stockholder's equity, with lookback window of 15.
		Our row is valued at 41256852.0, our lookback sum is 41256852.0
Working on 895502-1998-11-13
	We dropped row 10, 35,000 shares; issued and outstanding 200 shares, with lookback window of 1.
		Our row is valued at 0.0, our lookback sum is 0.0
	We dropped row 13, Total shareholder's equity, with lookback window of 2.
		Our row is valued at 103485000.0, our lookback sum is 103485000.0
	We dropped row 14, Total liabilities and shareholder's equity, with lookback window of 14.
		Our row is valued at 1582979000.0, our lookback sum is 1582979000.0
Working on 895502-2002-12-30
	We dropped row 13, Total liabilities and shareholder's equity, with lookback window of 13.
		Our row is valued at 2991880000.0, our lookback sum is 2991880000.0
Working on 895502-2004-08-05
	We dropped row 5, Securities sold under repurchase agreements (Note 2), with lookback window of 1.
		Our row is valued at 289605000.0, our lookback sum is 289605000.0
	We dropped row 12, Other accnied expenses, with lookback window of 1.
		Our row is valued at 108175000.0, our lookback sum is 108175000.0
	We dropped row 20, Retained carnings, with lookback window of 1.
		Our row is valued at 250272000.0, our lookback sum is 250272000.0
Working on 895502-2005-01-21
	We dropped row 5, Payble to brokers. dealers and clearing organizations (Note 3), with lookback window of 1.
		Our row is valued at 87141000.0, our lookback sum is 87141000.0
	We dropped row 20, Total liabilities and shareholders' equity, with lookback window of 5.
		Our row is valued at 5233749000.0, our lookback sum is 5233749000.0
Working on 895502-2005-12-29
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 4789515000.0, our lookback sum is 4789515000.0
	We dropped row 17, Total shareholder's equity, with lookback window of 3.
		Our row is valued at 726197000.0, our lookback sum is 726197000.0
	We dropped row 18, Total liabilities and shareholder's equity, with lookback window of 18.
		Our row is valued at 5515712000.0, our lookback sum is 5515712000.0
Working on 895502-2006-12-28
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 8371150000.0, our lookback sum is 8371150000.0
	We dropped row 17, Total shareholder's equity, with lookback window of 3.
		Our row is valued at 822170000.0, our lookback sum is 822170000.0
	We dropped row 18, Total liabilities and shareholder's equity, with lookback window of 18.
		Our row is valued at 9193320000.0, our lookback sum is 9193320000.0
Working on 895502-2007-12-31
	We dropped row 15, Total liabilities, with lookback window of 14.
		Our row is valued at 7330819000.0, our lookback sum is 7330819000.0
	We dropped row 19, Total shareholder's equity, with lookback window of 3.
		Our row is valued at 1004849000.0, our lookback sum is 1004849000.0
	We dropped row 20, TOTAL, with lookback window of 19.
		Our row is valued at 8335668000.0, our lookback sum is 8335668000.0
Working on 895502-2008-02-15
	We dropped row 15, Total liabilities, with lookback window of 14.
		Our row is valued at 7330819000.0, our lookback sum is 7330819000.0
	We dropped row 19, Total shareholder's equity, with lookback window of 3.
		Our row is valued at 1004849000.0, our lookback sum is 1004849000.0
	We dropped row 20, TOTAL, with lookback window of 19.
		Our row is valued at 8335668000.0, our lookback sum is 8335668000.0
Working on 895502-2009-12-30
	We dropped row 11, TOTAL LIABILTIES, with lookback window of 11.
		Our row is valued at 33214787000.0, our lookback sum is 33214787000.0
	We dropped row 16, TOTAL STOCKHOLDER'S EQUITY, with lookback window of 4.
		Our row is valued at 2943700000.0, our lookback sum is 2943700000.0
	We dropped row 17, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 17.
		Our row is valued at 36158487000.0, our lookback sum is 36158487000.0
Working on 895502-2011-07-05
	We dropped row 11, TOTAL LIABILTIES, with lookback window of 11.
		Our row is valued at 38485650000.0, our lookback sum is 38485650000.0
	We dropped row 16, TOTAL STOCKHOLDER'S EQUITY, with lookback window of 3.
		Our row is valued at 3183851000.0, our lookback sum is 3183841000.0
	We dropped row 17, TOTAL LIABILITIES AND STOCKHOLDER'S EQUITY, with lookback window of 17.
		Our row is valued at 41669501000.0, our lookback sum is 41669501000.0
Working on 895502-2011-12-29
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 39393754000.0, our lookback sum is 39393754000.0
	We dropped row 15, Total members' equity, with lookback window of 2.
		Our row is valued at 3686136000.0, our lookback sum is 3686126000.0
	We dropped row 16, TOTAL LIABILITIES AND MEMBERS' EQUITY, with lookback window of 16.
		Our row is valued at 43079890000.0, our lookback sum is 43079890000.0
Working on 895502-2012-12-28
	We dropped row 11, Liabilities subordinated to claims of general creditors from affiliates, with lookback window of 1.
		Our row is valued at 1400000000.0, our lookback sum is 400000000.0
	We dropped row 16, Total members' equity, with lookback window of 2.
		Our row is valued at 3839199000.0, our lookback sum is 3839189000.0
	We dropped row 17, TOTAL LIABILITIES AND MEMBERS EQUITY, with lookback window of 5.
		Our row is valued at 70266017000.0, our lookback sum is 70266017000.0
Working on 895502-2014-01-02
	We dropped row 12, Liabilities subordinated to claims of general creditors from affiliates, with lookback window of 1.
		Our row is valued at 1400000000.0, our lookback sum is 400000000.0
	We dropped row 16, Total members' equity, with lookback window of 2.
		Our row is valued at 4056280000.0, our lookback sum is 4056270000.0
Working on 895502-2014-12-29
	We dropped row 13, Total members' equity, with lookback window of 1.
		Our row is valued at 4328296000.0, our lookback sum is 4328286000.0
	We dropped row 14, Total liabilities and members' equity, with lookback window of 14.
		Our row is valued at 75953329000.0, our lookback sum is 75953329000.0
Working on 895502-2015-12-30
	We dropped row 12, Total members' equity, with lookback window of 1.
		Our row is valued at 4739586000.0, our lookback sum is 4739576000.0
	We dropped row 13, Total liabilities and members' equity, with lookback window of 13.
		Our row is valued at 82314225000.0, our lookback sum is 82314225000.0
Working on 895502-2016-12-28
	We dropped row 13, Total members' equity, with lookback window of 1.
		Our row is valued at 5085885000.0, our lookback sum is 5085875000.0
	We dropped row 14, Total liabilities and members' equity, with lookback window of 14.
		Our row is valued at 82304140000.0, our lookback sum is 82304140000.0
Working on 895502-2017-12-26
	We dropped row 12, Total members' equity, with lookback window of 1.
		Our row is valued at 5318540000.0, our lookback sum is 5318540000.0
	We dropped row 13, Total liabilities and members' equity, with lookback window of 13.
		Our row is valued at 78680916000.0, our lookback sum is 78680916000.0
Working on 895502-2019-06-17
	We dropped row 11, Total members' equity, with lookback window of 1.
		Our row is valued at 5666056000.0, our lookback sum is 5666056000.0
	We dropped row 12, Total liabilities and members' equity, with lookback window of 12.
		Our row is valued at 60163611000.0, our lookback sum is 60163611000.0
Working on 895502-2019-12-23
	We dropped row 12, Total Members' equity, with lookback window of 1.
		Our row is valued at 5905876000.0, our lookback sum is 5905876000.0
	We dropped row 13, Total liabilities and members' equity, with lookback window of 13.
		Our row is valued at 60492227000.0, our lookback sum is 60492227000.0
Working on 91154-2002-03-01
	We dropped row 4, Financial instruments sold, not yet purchased,, with lookback window of 2.
		Our row is valued at 121985000000.0, our lookback sum is 121985000000.0
	We dropped row 11, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 25226000000.0, our lookback sum is 25226000000.0
	We dropped row 17, Total liabilities, with lookback window of 17.
		Our row is valued at 218419000000.0, our lookback sum is 218419000000.0
	We dropped row 22, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 6860000000.0, our lookback sum is 6850000000.0
	We dropped row 23, Total liabilities and stockholder's equity, with lookback window of 23.
		Our row is valued at 225279000000.0, our lookback sum is 225279000000.0

Working on 91154-2003-03-03
	We dropped row 4, Financial instruments sold, not yet purchased,, with lookback window of 2.
		Our row is valued at 114159000000.0, our lookback sum is 114159000000.0
	We dropped row 11, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 18012000000.0, our lookback sum is 18012000000.0
	We dropped row 18, Total liabilities, with lookback window of 18.
		Our row is valued at 189981000000.0, our lookback sum is 189981000000.0
	We dropped row 23, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7136000000.0, our lookback sum is 7126000000.0
	We dropped row 24, Total liabilities and stockholder's equity, with lookback window of 24.
		Our row is valued at 197117000000.0, our lookback sum is 197117000000.0
Working on 91154-2004-02-27
	We dropped row 10, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 24756000000.0, our lookback sum is 24756000000.0
	We dropped row 17, Total liabilities, with lookback window of 17.
		Our row is valued at 223965000000.0, our lookback sum is 223965000000.0
	We dropped row 22, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 7239000000.0, our lookback sum is 7229000000.0
	We dropped row 23, Total liabilities and stockholder's equity, with lookback window of 23.
		Our row is valued at 231204000000.0, our lookback sum is 231204000000.0
Working on 91154-2005-03-01
	We dropped row 4, Financial instruments sold, not yet purchased,, with lookback window of 2.
		Our row is valued at 138285000000.0, our lookback sum is 138285000000.0
	We dropped row 11, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 30788000000.0, our lookback sum is 30788000000.0
	We dropped row 17, Total liabilities, with lookback window of 17.
		Our row is valued at 270455000000.0, our lookback sum is 270455000000.0
	We dropped row 22, Total stockholder's equity, with lookback window of 4.
		Our row is valued at 8404000000.0, our lookback sum is 8404000000.0
	We dropped row 23, Total liabilities and stockholder's equity, with lookback window of 23.
		Our row is valued at 278859000000.0, our lookback sum is 278859000000.0
Working on 91154-2007-03-01
	We dropped row 10, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 29668000000.0, our lookback sum is 29668000000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 367118000000.0, our lookback sum is 367118000000.0
	We dropped row 21, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 10833000000.0, our lookback sum is 10823000000.0
	We dropped row 22, Total liabilities and stockholder's equity, with lookback window of 22.
		Our row is valued at 377951000000.0, our lookback sum is 377951000000.0
Working on 91154-2008-02-29
	We dropped row 4, Financial instruments sold, not yet purchased, and, with lookback window of 2.
		Our row is valued at 205309000000.0, our lookback sum is 205309000000.0
	We dropped row 11, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 26313000000.0, our lookback sum is 26313000000.0
	We dropped row 16, Total liabilities, with lookback window of 16.
		Our row is valued at 354820000000.0, our lookback sum is 354820000000.0
	We dropped row 21, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 8342000000.0, our lookback sum is 8332000000.0
	We dropped row 22, Total liabilities and stockholder's equity, with lookback window of 22.
		Our row is valued at 363162000000.0, our lookback sum is 363162000000.0
Working on 91154-2009-03-02
	We dropped row 4, Financial instruments sold, not yet purchased, and, with lookback window of 2.
		Our row is valued at 167462000000.0, our lookback sum is 167462000000.0
	We dropped row 10, Other financial instruments, with lookback window of 1.
		Our row is valued at 125000000.0, our lookback sum is 124000000.0
	We dropped row 21, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 6383000000.0, our lookback sum is 6373000000.0
	We dropped row 22, Total liabilities and stockholder's equity, with lookback window of 6.
		Our row is valued at 286825000000.0, our lookback sum is 286825000000.0
Working on 91154-2010-03-02
	We dropped row 2, Collateralized short-term financing agreements:, with lookback window of 2.
		Our row is valued at 56832000000.0, our lookback sum is 56832000000.0
	We dropped row 12, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 27328000000.0, our lookback sum is 27328000000.0
	We dropped row 18, Total liabilities, with lookback window of 18.
		Our row is valued at 296359000000.0, our lookback sum is 296359000000.0
	We dropped row 23, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 17997000000.0, our lookback sum is 17987000000.0
	We dropped row 24, Total liabilities and stockholder's equity, with lookback window of 24.
		Our row is valued at 314356000000.0, our lookback sum is 314356000000.0
Working on 91154-2011-03-01
	We dropped row 2, Collateralized short-term financing agreements:, with lookback window of 2.
		Our row is valued at 15835000000.0, our lookback sum is 15835000000.0
	We dropped row 5, Trading account liabilities:, with lookback window of 2.
		Our row is valued at 131419000000.0, our lookback sum is 131419000000.0
	We dropped row 12, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 27875000000.0, our lookback sum is 27875000000.0
	We dropped row 18, Total liabilities, with lookback window of 18.
		Our row is valued at 272389000000.0, our lookback sum is 272389000000.0
	We dropped row 23, Total stockholder's equity, with lookback window of 3.
		Our row is valued at 16020000000.0, our lookback sum is 16010000000.0
	We dropped row 24, Total liabilities and stockholder's equity, with lookback window of 24.
		Our row is valued at 288409000000.0, our lookback sum is 288409000000.0
Working on 91154-2012-02-29
	We dropped row 4, Trading account liabilities:, with lookback window of 2.
		Our row is valued at 133872000000.0, our lookback sum is 133872000000.0
	We dropped row 11, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 25871000000.0, our lookback sum is 25871000000.0
	We dropped row 17, Total liabilities, with lookback window of 17.
		Our row is valued at 261317000000.0, our lookback sum is 261317000000.0
	We dropped row 21, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 7833000000.0, our lookback sum is 7823000000.0
	We dropped row 22, Total liabilities and stockholder's equity, with lookback window of 22.
		Our row is valued at 269150000000.0, our lookback sum is 269150000000.0
Working on 91154-2013-03-01
	We dropped row 2, Collateralized short-term financing agreements:, with lookback window of 2.
		Our row is valued at 19943000000.0, our lookback sum is 19943000000.0
	We dropped row 5, Trading account liabilities:, with lookback window of 2.
		Our row is valued at 136775000000.0, our lookback sum is 136775000000.0
	We dropped row 12, Payables and accrued liabilities:, with lookback window of 6.
		Our row is valued at 20694000000.0, our lookback sum is 20694000000.0
	We dropped row 18, Total liabilities, with lookback window of 18.
		Our row is valued at 242830000000.0, our lookback sum is 242830000000.0
	We dropped row 22, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 8692000000.0, our lookback sum is 8682000000.0
	We dropped row 23, Total liabilities and stockholder's equity, with lookback window of 23.
		Our row is valued at 251522000000.0, our lookback sum is 251522000000.0
Working on 91154-2014-03-04
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 235464000000.0, our lookback sum is 235464000000.0
	We dropped row 19, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 9691000000.0, our lookback sum is 9681000000.0
	We dropped row 20, Total liabilities and stockholder's equity, with lookback window of 20.
		Our row is valued at 253600000000.0, our lookback sum is 253600000000.0

Working on 91154-2016-03-01
	We dropped row 13, Total liabilities, with lookback window of 13.
		Our row is valued at 234329000000.0, our lookback sum is 234329000000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 9142000000.0, our lookback sum is 9132000000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 253416000000.0, our lookback sum is 253416000000.0
Working on 91154-2017-03-02
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 252450000000.0, our lookback sum is 252450000000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 9194000000.0, our lookback sum is 9184000000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 261644000000.0, our lookback sum is 261644000000.0
Working on 91154-2018-03-05
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 263529000000.0, our lookback sum is 263529000000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 9015000000.0, our lookback sum is 9005000000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 272544000000.0, our lookback sum is 272544000000.0
Working on 91154-2019-03-05
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 290048000000.0, our lookback sum is 290048000000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 8860000000.0, our lookback sum is 8850000000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 298908000000.0, our lookback sum is 298908000000.0
Working on 91154-2020-03-02
	We dropped row 14, Total liabilities, with lookback window of 14.
		Our row is valued at 280372000000.0, our lookback sum is 280372000000.0
	We dropped row 18, Total stockholder's equity, with lookback window of 2.
		Our row is valued at 9073000000.0, our lookback sum is 9063000000.0
	We dropped row 19, Total liabilities and stockholder's equity, with lookback window of 19.
		Our row is valued at 289445000000.0, our lookback sum is 289445000000.0
Working on 920417-2015-03-02
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 29420949000.0, our lookback sum is 29420949000.0
	We dropped row 10, Total liabilities and partners' capital, with lookback window of 10.
		Our row is valued at 32452777000.0, our lookback sum is 32452777000.0
Working on 920417-2016-02-29
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 27903087000.0, our lookback sum is 27903087000.0
	We dropped row 10, Total liabilities and partners' capital, with lookback window of 10.
		Our row is valued at 31810325000.0, our lookback sum is 31810325000.0
Working on 920417-2017-03-01
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 26854961000.0, our lookback sum is 26854961000.0
	We dropped row 10, Total liabilities and partners' capital, with lookback window of 10.
		Our row is valued at 29809441000.0, our lookback sum is 29809441000.0
Working on 920417-2018-02-27
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 34672926000.0, our lookback sum is 34672926000.0
	We dropped row 10, Total liabilities and partners' capital, with lookback window of 10.
		Our row is valued at 38170352000.0, our lookback sum is 38170352000.0
Working on 920417-2019-02-28
	We dropped row 7, Total liabilities, with lookback window of 7.
		Our row is valued at 38346263000.0, our lookback sum is 38346263000.0
	We dropped row 9, Total liabilities and partners' capital, with lookback window of 9.
		Our row is valued at 42507970000.0, our lookback sum is 42507970000.0
Working on 920417-2020-02-28
	We dropped row 8, Total liabilities, with lookback window of 8.
		Our row is valued at 39466270000.0, our lookback sum is 39466270000.0
	We dropped row 10, Total liabilities and member's equity, with lookback window of 10.
		Our row is valued at 44032681000.0, our lookback sum is 44032681000.0
Working on 920417-2021-03-01
	We dropped row 9, Total liabilities, with lookback window of 9.
		Our row is valued at 83173930000.0, our lookback sum is 83173930000.0
	We dropped row 11, Total liabilities and member's equity, with lookback window of 11.
		Our row is valued at 88247203000.0, our lookback sum is 88247203000.0
Working on 922792-2002-03-04
	We dropped row 3, Total liabilities, with lookback window of 3.
		Our row is valued at 246399753.0, our lookback sum is 246399753.0
	We dropped row 5, TOTAL LIABILITIES AND MEMBERS' CAPITAL, with lookback window of 5.
		Our row is valued at 313922089.0, our lookback sum is 313922089.0
Working on 922792-2003-03-03
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 558604237.0, our lookback sum is 558604237.0
	We dropped row 7, TOTAL LIABILITIES AND MEMBERS' CAPITAL, with lookback window of 7.
		Our row is valued at 664292626.0, our lookback sum is 664292626.0
Working on 922792-2004-03-01
	We dropped row 5, Total liabilities, with lookback window of 5.
		Our row is valued at 1097272438.0, our lookback sum is 1097272438.0
	We dropped row 7, TOTAL LIABILITIES AND MEMBERS' CAPITAL, with lookback window of 7.
		Our row is valued at 1247968829.0, our lookback sum is 1247968829.0
Working on 922792-2005-03-01
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 1569877542.0, our lookback sum is 1569877542.0
	We dropped row 6, TOTAL LIABILITIES AND MEMBERS' CAPITAL, with lookback window of 6.
		Our row is valued at 1764275076.0, our lookback sum is 1764275076.0
Working on 922792-2006-03-01
	We dropped row 4, Total liabilities, with lookback window of 4.
		Our row is valued at 2509137371.0, our lookback sum is 2509137371.0
	We dropped row 6, TOTAL LIABILITIES AND MEMBERS' CAPITAL, with lookback window of 6.
		Our row is valued at 2759809118.0, our lookback sum is 2759809118.0
Working on 922792-2007-03-01
	We dropped row 6, Total liabilities and members' capital, with lookback window of 6.
		Our row is valued at 4536097237.0, our lookback sum is 4536097237.0
Working on 922792-2008-02-29
	We dropped row 9, Total liabilities and members' capital, with lookback window of 9.
		Our row is valued at 8676028952.0, our lookback sum is 8676028952.0
Working on 922792-2009-03-02
	We dropped row 8, Total liabilities and members' capital, with lookback window of 8.
		Our row is valued at 7996500333.0, our lookback sum is 7996500333.0
Working on 922792-2010-03-02
	We dropped row 7, Total liabilities and members' capital, with lookback window of 7.
		Our row is valued at 12069674947.0, our lookback sum is 12069674947.0
Working on 922792-2012-02-29
	We dropped row 8, Total liabilities and members' capital, with lookback window of 8.
		Our row is valued at 20362705552.0, our lookback sum is 20362705552.0
Working on 922792-2014-03-04
	We dropped row 8, Total liabilities and members' capital, with lookback window of 8.
		Our row is valued at 29450361000.0, our lookback sum is 29450361000.0
Working on 922792-2015-03-02
	We dropped row 8, Total liabilities and members' capital, with lookback window of 8.
		Our row is valued at 36189624000.0, our lookback sum is 36189624000.0
Working on 922792-2016-02-29
	We dropped row 7, Total liabilities and members' capital, with lookback window of 7.
		Our row is valued at 40188000000.0, our lookback sum is 40188000000.0
Working on 922792-2017-03-01
	We dropped row 9, Total liabilities and members' capital, with lookback window of 9.
		Our row is valued at 44185000000.0, our lookback sum is 44185000000.0
Working on 922792-2018-03-01
	We dropped row 9, Total liabilities and members' capital, with lookback window of 9.
		Our row is valued at 51613000000.0, our lookback sum is 51613000000.0
Working on 922792-2019-02-28
	We dropped row 7, Accounts payable, accrued expenses and other liabilities, with lookback window of 1.
		Our row is valued at 59000000.0, our lookback sum is 59000000.0
	We dropped row 10, Total other payables, with lookback window of 5.
		Our row is valued at 354000000.0, our lookback sum is 354000000.0
	We dropped row 11, Total liabilities, with lookback window of 11.
		Our row is valued at 45591000000.0, our lookback sum is 45591000000.0
	We dropped row 13, Total liabilities and members' capital, with lookback window of 13.
		Our row is valued at 50852000000.0, our lookback sum is 50852000000.0

Working on 922792-2019-03-01
	We dropped row 9, Total other payables, with lookback window of 4.
		Our row is valued at 354000000.0, our lookback sum is 354000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 45591000000.0, our lookback sum is 45591000000.0
	We dropped row 12, Total liabilities and members' capital, with lookback window of 12.
		Our row is valued at 50852000000.0, our lookback sum is 50852000000.0
Working on 922792-2020-02-28
	We dropped row 9, Total other payables, with lookback window of 4.
		Our row is valued at 282000000.0, our lookback sum is 282000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 54636000000.0, our lookback sum is 54636000000.0
	We dropped row 12, Total liabilities and members' capital, with lookback window of 12.
		Our row is valued at 60395000000.0, our lookback sum is 60395000000.0
Working on 922792-2021-02-26
	We dropped row 9, Total other payables, with lookback window of 4.
		Our row is valued at 294000000.0, our lookback sum is 294000000.0
	We dropped row 10, Total liabilities, with lookback window of 10.
		Our row is valued at 71756000000.0, our lookback sum is 71756000000.0
	We dropped row 12, Total liabilities and members' capital, with lookback window of 12.
		Our row is valued at 77404000000.0, our lookback sum is 77404000000.0

We created an unstructured asset and liability & equity

In [9]:
# work on combining columns that are issued seperately
s3 = boto3.client('s3')
session = Session()
bucket = "ran-s3-systemic-risk"

# e.g. file name = 1224385-2004-03-01, 42352-2003-01-28
s3.download_file(bucket, 'Output/X-17A-5-SPLIT-PDFS/Assets/72267-2004-05-28.csv', 'temp.csv')
pdf_df = pd.read_csv('temp.csv')
s3.download_file(bucket, 'Output/X-17A-5-SPLIT-PNGS/Assets/72267-2004-05-28.csv', 'temp.csv')
png_df = pd.read_csv('temp.csv')
os.remove('temp.csv')

# do a special merge that combines unique line items names between PDF & PNG
temp_df1 = special_merge(pdf_df, png_df, '0')

# run accounting check to remove sub-totals for each respective line-item
df, total_flag, total_amt = totals_check(temp_df1)

	We dropped row 4, Financial instruments owned (approximately $10,900,474 were, with lookback window of 2.
		Our row is valued at 44343153000.0, our lookback sum is 44343153000.0
	We dropped row 9, Receivables:, with lookback window of 4.
		Our row is valued at 17731470000.0, our lookback sum is 17731470000.0
	We dropped row 13, Furniture, equipment and leasehold improvements, net of, with lookback window of 3.
		Our row is valued at 535815000.0, our lookback sum is 535815000.0

In [35]:
pdf_df

                                                    0             1
0                           Cash and cash equivalents  9.182030e+08
1   Cash and securities segregated pursuant to fed...  3.651780e+08
2     Securities purchased under agreements to resell  2.566025e+10
3                                 Securities borrowed  1.868290e+10
4   Financial instruments owned (approximately $10...  4.434315e+10
5                                   Equity securities  7.965816e+09
6               U.S. government and agency securities  7.277881e+09
7   Corporate debt and collateralized mortgage obl...  2.446369e+09
8                                             Options  4.140400e+07
9                                        Receivables:  1.773147e+10
10        Brokers, dealers and clearing organizations  3.985370e+08
11                             Interest and dividends  1.007450e+08
12                                          Customers  3.653300e+07
13  Furniture, equipment and leasehold improvement...  5.358150e+08
14  accumulated depreciation and amortization of $...  1.709300e+07
15                                       Other assets  4.030600e+07
16                                       Total assets  6.395122e+10

In [37]:
special_merge(pdf_df, png_df, '0')

['U.S. government and agency securities'] ['U. S. government and agency securities']
                                       0             1
6  U.S. government and agency securities  7.277881e+09
['Furniture, equipment and leasehold improvements, net of'
 'accumulated depreciation and amortization of $40,523'] ['Furniture, equipment and leasehold improvements, net of accumulated depreciation and amortization of $40,523']
                                                    0            1
13  Furniture, equipment and leasehold improvement...  535815000.0

                                                    0             1
0                           Cash and cash equivalents  9.182030e+08
1   Cash and securities segregated pursuant to fed...  3.651780e+08
2     Securities purchased under agreements to resell  2.566025e+10
3                                 Securities borrowed  1.868290e+10
4   Financial instruments owned (approximately $10...  4.434315e+10
5                                   Equity securities  7.965816e+09
6               U.S. government and agency securities  7.277881e+09
7   Corporate debt and collateralized mortgage obl...  2.446369e+09
8                                             Options  4.140400e+07
9                                        Receivables:  1.773147e+10
10        Brokers, dealers and clearing organizations  3.985370e+08
11                             Interest and dividends  1.007450e+08
12                                          Customers  3.653300e+07
13  Furniture, equipment and leasehold improvement...  5.358150e+08
14                                       Other assets  4.030600e+07
15                                       Total assets  6.395122e+10

In [38]:
a = ['Furniture, equipment and leasehold improvements, net of', 'accumulated depreciation and amortization of $40,523'] 
b = ['Furniture, equipment and leasehold improvements, net of accumulated depreciation and amortization of $40,523']

In [42]:
for idx, i in enumerate(zip(a, b)):
    print(idx, i)

0 ('Furniture, equipment and leasehold improvements, net of', 'Furniture, equipment and leasehold improvements, net of accumulated depreciation and amortization of $40,523')

In [43]:
i

('Furniture, equipment and leasehold improvements, net of',
 'Furniture, equipment and leasehold improvements, net of accumulated depreciation and amortization of $40,523')